//! Generated by tools/gen_k6_bench.py from abi/schema/k6-bench-v1.json.
//! Do not edit.
//!
//! The K6 paired benchmarks, as the native supervisor encodes them. Both C
//! builds of the benchmark read the same layout from
//! `user/native/include/thalyx/k6.h`, with static assertions on every offset.

// The schema is generated whole; a program uses the part it needs.
#![allow(dead_code)]

use thalyx_user_k4fmt::Pod;

/// Protocol version this revision speaks.
pub const VERSION_MAJOR: u32 = 1;
/// Minor version.
pub const VERSION_MINOR: u32 = 0;

/// Schema constant `PLAN_MAGIC`.
pub const PLAN_MAGIC: u64 = 3544385891052868683;
/// Schema constant `PLAN_VERSION`.
pub const PLAN_VERSION: u64 = 1;
/// Schema constant `PLAN_ENTRIES`.
pub const PLAN_ENTRIES: u64 = 32;
/// Schema constant `SAMPLES_MAX`.
pub const SAMPLES_MAX: u64 = 16384;
/// Schema constant `CAL_WINDOW_NS`.
pub const CAL_WINDOW_NS: u64 = 200000000;
/// Schema constant `SLICE_NS`.
pub const SLICE_NS: u64 = 10000000;
/// Schema constant `LOST_SAMPLE`.
pub const LOST_SAMPLE: u64 = 4294967295;
/// Schema constant `ENGINE_PROMPTS`.
pub const ENGINE_PROMPTS: u64 = 5;
/// Schema constant `ROLE_CLIENT`.
pub const ROLE_CLIENT: u64 = 16;
/// Schema constant `ROLE_SERVER`.
pub const ROLE_SERVER: u64 = 17;
/// Schema constant `ROLE_SPIN`.
pub const ROLE_SPIN: u64 = 18;
/// Schema constant `ROLE_ASKER`.
pub const ROLE_ASKER: u64 = 19;
/// Schema constant `ROLE_IDLE`.
pub const ROLE_IDLE: u64 = 20;
/// Schema constant `SLOT_PAIR0`.
pub const SLOT_PAIR0: u64 = 2;
/// Schema constant `SLOT_PAIR1`.
pub const SLOT_PAIR1: u64 = 9;
/// Schema constant `SLOT_PAIR2`.
pub const SLOT_PAIR2: u64 = 10;
/// Schema constant `SLOT_PAIR3`.
pub const SLOT_PAIR3: u64 = 11;
/// Schema constant `SLOT_ENGINE`.
pub const SLOT_ENGINE: u64 = 12;
/// Schema constant `SLOT_HANDOFF`.
pub const SLOT_HANDOFF: u64 = 13;
/// Schema constant `HANDOFF_REQUEST_BIT`.
pub const HANDOFF_REQUEST_BIT: u64 = 1;
/// Schema constant `HANDOFF_DONE_BIT`.
pub const HANDOFF_DONE_BIT: u64 = 2;
/// Schema constant `ASKER_ASKING_BIT`.
pub const ASKER_ASKING_BIT: u64 = 4;
/// Schema constant `IDLE_READY_BIT`.
pub const IDLE_READY_BIT: u64 = 8;
/// Schema constant `SHARED_PLAN_OFFSET`.
pub const SHARED_PLAN_OFFSET: u64 = 0;
/// Schema constant `SHARED_HANDOFF_OFFSET`.
pub const SHARED_HANDOFF_OFFSET: u64 = 2048;
/// Schema constant `SHARED_BYTES`.
pub const SHARED_BYTES: u64 = 4096;
/// Schema constant `WAKE_BIT`.
pub const WAKE_BIT: u64 = 1099511627776;
/// Schema constant `MAP_VADDR`.
pub const MAP_VADDR: u64 = 1879048192;
/// Schema constant `SEAL_VADDR`.
pub const SEAL_VADDR: u64 = 1946157056;
/// Schema constant `PROMPT_VADDR`.
pub const PROMPT_VADDR: u64 = 2013265920;

/// Notes the K6 programs emit on the diagnostic plane, in their own range.
pub mod note {
    /// The plan this run follows. Value: its seed.
    pub const PLAN: u64 = 0x6000;
    /// Time-stamp-counter frequency calibrated against this backend's monotonic clock over CAL_WINDOW_NS.
    pub const TSC_HZ: u64 = 0x6001;
    /// A benchmark starts. Value: id | param << 16 | samples << 32.
    pub const BEGIN: u64 = 0x6002;
    /// Two samples, the earlier in the low 32 bits. LOST_SAMPLE marks a sample that was not taken.
    pub const SAMPLE: u64 = 0x6003;
    /// A benchmark ended. Value: id | errors << 32.
    pub const END: u64 = 0x6004;
    /// An operation under measurement failed. Value: id | (status & 0xffffffff) << 32.
    pub const ERROR: u64 = 0x6005;
    /// An engine answer was not the reference completion. Value: prompt index.
    pub const MISMATCH: u64 = 0x6006;
    /// A correctness check the benchmark makes on its own work passed. Value: id | count << 32.
    pub const CHECK: u64 = 0x6007;
    /// A benchmark-specific quantity. Value: id | quantity index << 16 | value << 32.
    pub const AUX: u64 = 0x6008;
    /// The plan ran to its end. Value: benchmarks run.
    pub const DONE: u64 = 0x60FF;
    /// FNV-1a of the first answer an engine gave to one prompt. Value: the digest; the prompt is the AUX note before it.
    pub const DIGEST: u64 = 0x6009;
}

/// Benchmark identities.
pub mod bench {
    /// `entry.version`: primitive, equivalent.
    pub const ENTRY_VERSION: u32 = 1;
    /// `entry.clock`: primitive, equivalent.
    pub const ENTRY_CLOCK: u32 = 2;
    /// `ipc.call`: primitive, comparable.
    pub const IPC_CALL: u32 = 3;
    /// `ipc.caps`: primitive, comparable.
    pub const IPC_CAPS: u32 = 4;
    /// `mem.map`: primitive, comparable.
    pub const MEM_MAP: u32 = 5;
    /// `mem.seal`: primitive, comparable.
    pub const MEM_SEAL: u32 = 6;
    /// `cap.derive`: primitive, comparable.
    pub const CAP_DERIVE: u32 = 7;
    /// `sched.wake`: sched, equivalent.
    pub const SCHED_WAKE: u32 = 8;
    /// `quota.share`: quota, equivalent.
    pub const QUOTA_SHARE: u32 = 9;
    /// `scale.ipc`: scale, comparable.
    pub const SCALE_IPC: u32 = 10;
    /// `scale.compute`: scale, equivalent.
    pub const SCALE_COMPUTE: u32 = 11;
    /// `closure.unit`: closure, different.
    pub const CLOSURE_UNIT: u32 = 12;
    /// `engine.load`: engine, comparable.
    pub const ENGINE_LOAD: u32 = 13;
    /// `engine.infer`: engine, equivalent.
    pub const ENGINE_INFER: u32 = 14;
    /// `engine.cancel`: engine, different.
    pub const ENGINE_CANCEL: u32 = 15;
    /// `ipc.lineage`: v0, native_only.
    pub const IPC_LINEAGE: u32 = 16;
    /// `audit.drain`: v0, native_only.
    pub const AUDIT_DRAIN: u32 = 17;
}

/// The engine's questions, from the K5 fixture, case by case and prompt by
/// prompt. `engine.infer`'s parameter indexes them.
pub const ENGINE_PROMPT: [&str; 5] = [
    "hola hola",
    "hola",
    "adios",
    "adios adios",
    "hola hola hola hola hola hola",
];
/// Tokens each of those questions may be answered with.
pub const ENGINE_PREDICT: [u32; 5] = [12, 12, 12, 12, 400];

/// What one boot runs, in order. The same bytes reach both backends: a module of the native package, a file of the Linux one.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Plan {
    /// PLAN_MAGIC.
    pub magic: u64,
    /// PLAN_VERSION.
    pub version: u32,
    /// Entries in use.
    pub count: u32,
    /// Seed the host drew for this boot; it decided the order of the entries.
    pub seed: u64,
    /// Which round of the paired design this boot is.
    pub round: u32,
    /// Reserved, zero.
    pub flags: u32,
    /// Bytes of the engine model the package carries; a sealed module is whole pages, so the length is said here and checked against the object. Zero when no entry asks the engine. Linux reads the file and ignores it.
    pub model_bytes: u64,
    /// Benchmark ids, in the order they run.
    pub bench: [u32; 32],
    /// The parameter of each entry.
    pub param: [u32; 32],
    /// Samples each entry takes.
    pub samples: [u32; 32],
    /// Unrecorded iterations before them.
    pub warmup: [u32; 32],
}

const _: () = assert!(size_of::<Plan>() == 552);
const _: () = assert!(align_of::<Plan>() == 8);

// SAFETY: `repr(C)`, integers and integer arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for Plan {}

/// An entry the native program hands to its supervisor, which runs it and answers with HANDOFF_DONE_BIT. At SHARED_HANDOFF_OFFSET.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct Handoff {
    /// Benchmark id.
    pub bench: u32,
    /// Its parameter.
    pub param: u32,
    /// Samples to take.
    pub samples: u32,
    /// Written by the supervisor: zero, or the negated status it stopped with.
    pub status: u32,
}

const _: () = assert!(size_of::<Handoff>() == 16);
const _: () = assert!(align_of::<Handoff>() == 4);

// SAFETY: `repr(C)`, integers and integer arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for Handoff {}
