//! Generated by tools/gen_k5_proto.py from abi/schema/k5-proto-v1.json.
//! Do not edit.
//!
//! The K5 protocols, as the Rust side of the package encodes them. The C
//! side has the same layout in `user/native/include/thalyx/k5.h`, derived
//! from the same schema, with static assertions on every offset.

use thalyx_user_k4fmt::Pod;

/// Protocol version this revision speaks.
pub const VERSION_MAJOR: u32 = 1;
/// Minor version.
pub const VERSION_MINOR: u32 = 0;

/// Schema constant `CHANNEL_REQUEST_OFFSET`.
pub const CHANNEL_REQUEST_OFFSET: usize = 0;
/// Schema constant `CHANNEL_REQUEST_MAX`.
pub const CHANNEL_REQUEST_MAX: usize = 8192;
/// Schema constant `CHANNEL_ANSWER_OFFSET`.
pub const CHANNEL_ANSWER_OFFSET: usize = 8192;
/// Schema constant `CHANNEL_ANSWER_MAX`.
pub const CHANNEL_ANSWER_MAX: usize = 16384;
/// Schema constant `CHANNEL_PROGRAM_OFFSET`.
pub const CHANNEL_PROGRAM_OFFSET: usize = 24576;
/// Schema constant `CHANNEL_PROGRAM_MAX`.
pub const CHANNEL_PROGRAM_MAX: usize = 8192;
/// Schema constant `PROMPT_MAX`.
pub const PROMPT_MAX: usize = 4096;
/// Schema constant `ANSWER_MAX`.
pub const ANSWER_MAX: usize = 4096;
/// Schema constant `CANDIDATE_MAX`.
pub const CANDIDATE_MAX: usize = 16384;
/// Schema constant `CANDIDATE_MAGIC_LOW`.
pub const CANDIDATE_MAGIC_LOW: usize = 893668931;
/// Schema constant `CANDIDATE_ENTRIES`.
pub const CANDIDATE_ENTRIES: usize = 8;
/// Schema constant `CANDIDATE_FLAG_FUNCTION_BODY`.
pub const CANDIDATE_FLAG_FUNCTION_BODY: usize = 1;

/// Notes the K5 programs emit on the diagnostic plane.
///
/// Their own range, so a K5 note can never be read as a K2, K3 or K4 one by
/// a gate looking at one log. Two integers each, which is all the plane
/// carries: anything a program wants remembered goes into managed state.
pub mod note {
    /// The work read the published version. Value: the generation.
    pub const VERSION_SEEN: u64 = 0x5200;
    /// The work asked for context about a name. Value: uses found.
    pub const CONTEXT_ANSWERED: u64 = 0x5201;
    /// A private workspace was opened over a version. Value: the workspace id.
    pub const WORKSPACE_OPEN: u64 = 0x5202;
    /// A name was bound in the workspace. Value: bytes of the object.
    pub const WORKSPACE_WROTE: u64 = 0x5203;
    /// The workspace was frozen into a candidate. Value: entries.
    pub const CANDIDATE_FROZEN: u64 = 0x5204;
    /// A candidate was sealed into a memory object. Value: bytes.
    pub const CANDIDATE_SEALED: u64 = 0x5205;
    /// A tool ran over the candidate. Value: its exit code.
    pub const TOOL_VERDICT: u64 = 0x5206;
    /// The tool's own accounting, as the launcher measured it. Value: ns.
    pub const TOOL_COST: u64 = 0x5207;
    /// A validation record was staged. Value: its result.
    pub const VALIDATION_STAGED: u64 = 0x5208;
    /// A publication succeeded. Value: the new generation.
    pub const PUBLISHED: u64 = 0x5209;
    /// A publication was refused. Value: the store status.
    pub const PUBLISH_REFUSED: u64 = 0x520A;
    /// The work abandoned on purpose. Value: the workspace it discarded.
    pub const ABANDONED: u64 = 0x520B;
    /// Evidence was written durably. Value: bytes.
    pub const EVIDENCE_WRITTEN: u64 = 0x520C;
    /// Evidence was read back from a published version. Value: bytes.
    pub const EVIDENCE_READ: u64 = 0x520D;
    /// The work finished its script. Value: the role.
    pub const WORK_DONE: u64 = 0x520E;
    /// The state service refused something. Value: the store status.
    pub const STORE_REFUSED: u64 = 0x520F;
    /// The published version after the work ended. Value: the generation.
    pub const FINAL_GENERATION: u64 = 0x5210;
    /// The work was asked to stop and did. Value: where it was.
    pub const CANCELLED: u64 = 0x5211;
    /// The work's own scope accounting. Value: nanoseconds it was charged.
    pub const WORK_CPU: u64 = 0x5212;
    /// A step the work did not expect. Value: what it saw.
    pub const WORK_UNEXPECTED: u64 = 0x5213;
    /// The digest of the root this work published or tried to. Value: prefix.
    pub const ROOT_PREFIX: u64 = 0x5214;
    /// The runtime compiled the program. Value: bytes of source.
    pub const PROGRAM_COMPILED: u64 = 0x5300;
    /// The runtime refused to compile the program. Value: where.
    pub const PROGRAM_REFUSED: u64 = 0x5301;
    /// The program made a hostcall. Value: the verb.
    pub const HOSTCALL: u64 = 0x5302;
    /// The program finished. Value: the finish kind.
    pub const PROGRAM_FINISH: u64 = 0x5303;
    /// A ceiling the runtime enforced. Value: which one.
    pub const PROGRAM_CEILING: u64 = 0x5304;
    /// An assertion latched. Value: the call it latched on.
    pub const PROGRAM_LATCHED: u64 = 0x5305;
    /// The runtime's own memory ceiling, as the engine reports it. Value: bytes.
    pub const PROGRAM_MEMORY: u64 = 0x5306;
    /// A hostcall was refused after the latch. Value: the verb.
    pub const REFUSED_AFTER_LATCH: u64 = 0x5307;
    /// The tool started over a candidate. Value: bytes it was given.
    pub const TOOL_START: u64 = 0x5400;
    /// The tool parsed a file. Value: bytes.
    pub const TOOL_PARSED: u64 = 0x5401;
    /// The tool refused a file. Value: where the syntax error was.
    pub const TOOL_PARSE_FAILED: u64 = 0x5402;
    /// The tool ran a check. Value: which.
    pub const TOOL_CHECK: u64 = 0x5403;
    /// A check did not hold. Value: which.
    pub const TOOL_CHECK_FAILED: u64 = 0x5404;
    /// The tool finished. Value: its exit code.
    pub const TOOL_DONE: u64 = 0x5405;
    /// The engine loaded its weights. Value: nanoseconds it took.
    pub const ENGINE_LOADED: u64 = 0x5500;
    /// Bytes of weights the engine holds. Value: bytes.
    pub const ENGINE_WEIGHTS: u64 = 0x5501;
    /// An inference was served. Value: which one since loading.
    pub const ENGINE_SERVED: u64 = 0x5502;
    /// The first token of an answer. Value: the token identifier.
    pub const ENGINE_TOKEN: u64 = 0x5503;
    /// The margin the first decision won by, in parts per million.
    pub const ENGINE_MARGIN: u64 = 0x5504;
    /// A digest over every token of one answer.
    pub const ENGINE_DIGEST: u64 = 0x5505;
    /// The engine bound a worker to the invocation. Value: the invocation.
    pub const ENGINE_BOUND: u64 = 0x5506;
    /// Nanoseconds one inference took, by the engine's own clock.
    pub const ENGINE_ELAPSED: u64 = 0x5507;
    /// The engine refused a request. Value: the status.
    pub const ENGINE_REFUSED: u64 = 0x5508;
    /// The prompt the engine actually read, as a digest of its bytes.
    pub const ENGINE_PROMPT: u64 = 0x5509;
    /// llama.cpp refused the weights. Value: a digest of the reason it gave.
    pub const ENGINE_LOAD_FAILED: u64 = 0x550A;
    /// An inference stopped because the caller's scope was closed. Value: tokens made before it stopped.
    pub const ENGINE_CANCELLED: u64 = 0x550B;
    /// A request was read and could not be served. Value: a digest of the reason.
    pub const ENGINE_FAILED: u64 = 0x550C;
    /// The context the engine built, in tokens.
    pub const ENGINE_CONTEXT: u64 = 0x550D;
    /// A C++ exception was thrown inside a request and caught by the engine. Value: a digest of what() said.
    pub const ENGINE_EXCEPTION: u64 = 0x550E;
    /// The highest raw logit of the first decision, computed before sampling, so the sampler's choice can be checked against it.
    pub const ENGINE_ARGMAX: u64 = 0x550F;
    /// Lines llama.cpp and ggml logged while loading. They go nowhere; the count says how many.
    pub const ENGINE_LOG_LINES: u64 = 0x5510;
    /// Bytes of /bulk the engine was given, before it loaded anything.
    pub const ENGINE_MODEL_BYTES: u64 = 0x5511;
    /// FNV-1a over those bytes, computed by the engine, so the weights it loaded can be named from the host's copy.
    pub const ENGINE_MODEL_DIGEST: u64 = 0x5512;
    /// A tool domain was built. Value: the tool identity.
    pub const LAUNCH_BUILT: u64 = 0x5600;
    /// A tool domain was retired. Value: pages its scope had held.
    pub const LAUNCH_RETIRED: u64 = 0x5601;
    /// A launch was refused. Value: the launcher status.
    pub const LAUNCH_REFUSED: u64 = 0x5602;
    /// The candidate a launch was given was not sealed. Value: its state.
    pub const LAUNCH_NOT_SEALED: u64 = 0x5603;
    /// Bytes of the candidate the tool read, with the checks it ran and failed.
    pub const TOOL_READ: u64 = 0x5215;
    /// The digest the tool computed over the bytes it actually read.
    pub const TOOL_SUM: u64 = 0x5216;
    /// After a cut, the work asked the service what became of each request identity it may have spent. Value: identities spent, with the last outcome in bits 8 and up.
    pub const WORK_RESUMED: u64 = 0x5217;
    /// The version this work would have published is already published with its change in it: nothing to redo. Value: the generation.
    pub const WORK_RECOVERED: u64 = 0x5218;
    /// The work is about to ask the engine for a long inference and has raised its signal to say so. Value: tokens asked for.
    pub const WORK_ASKING: u64 = 0x5219;
    /// A publication was refused for a stale generation and the work started again over the version that won. Value: the generation it now stands on.
    pub const WORK_REBASED: u64 = 0x521A;
    /// A check the program asked for needs a tool this backend does not have, and the launcher refused it rather than answering with a weaker one. Value: the tool identity asked for.
    pub const PROFILE_REFUSED: u64 = 0x521B;
}

/// `HostOp` values crossing the boundary as integers.
pub mod host_op {
    /// One Thalyx request: a verb and its arguments.
    /// `HostOp::REQUEST`.
    pub const REQUEST: u32 = 1;
    /// One validation, through the tool the whole verb uses.
    /// `HostOp::VALIDATE`.
    pub const VALIDATE: u32 = 2;
    /// What the workspace really shows changed.
    /// `HostOp::CHANGED`.
    pub const CHANGED: u32 = 3;
    /// One inference from the resident engine.
    /// `HostOp::MODEL`.
    pub const MODEL: u32 = 4;
    /// A line the program printed.
    /// `HostOp::LOG`.
    pub const LOG: u32 = 5;
    /// An assertion that did not hold. The latch is on the other side of this call.
    /// `HostOp::ASSERT_FAILED`.
    pub const ASSERT_FAILED: u32 = 6;
    /// The program has finished, and this is how.
    /// `HostOp::FINISH`.
    pub const FINISH: u32 = 7;
    /// The program stopped and asked for a decision it would not make.
    /// `HostOp::NEEDS_MODEL`.
    pub const NEEDS_MODEL: u32 = 8;
}

/// `Finish` values crossing the boundary as integers.
pub mod finish {
    /// It ran to the end and returned a value.
    /// `Finish::RETURNED`.
    pub const RETURNED: u32 = 1;
    /// It asked for a decision a machine should not make. Not a success.
    /// `Finish::NEEDS_MODEL`.
    pub const NEEDS_MODEL: u32 = 2;
    /// An assertion said no. Everything after it did not run.
    /// `Finish::ASSERTION`.
    pub const ASSERTION: u32 = 3;
    /// It threw something it did not catch.
    /// `Finish::THREW`.
    pub const THREW: u32 = 4;
    /// A ceiling was reached.
    /// `Finish::EXHAUSTED`.
    pub const EXHAUSTED: u32 = 5;
    /// It could not be read, or the engine could not be built.
    /// `Finish::REFUSED`.
    pub const REFUSED: u32 = 6;
}

/// `Verdict` values crossing the boundary as integers.
pub mod verdict {
    /// `Verdict::PASSED`.
    pub const PASSED: u32 = 1;
    /// `Verdict::FAILED`.
    pub const FAILED: u32 = 2;
    /// The check could not run. Never a pass.
    /// `Verdict::NOT_PROVEN`.
    pub const NOT_PROVEN: u32 = 3;
}

/// `LaunchOp` values crossing the boundary as integers.
pub mod launch_op {
    /// Run a tool over the sealed candidate lent with this message and report what it did.
    /// `LaunchOp::RUN_TOOL`.
    pub const RUN_TOOL: u32 = 1;
    /// What this launcher is and which tools it has images for.
    /// `LaunchOp::QUERY`.
    pub const QUERY: u32 = 2;
    /// Build and activate the language runtime over the shared channel, and answer at once: the caller has to be free to serve the calls it will make.
    /// `LaunchOp::START_RUNTIME`.
    pub const START_RUNTIME: u32 = 3;
    /// Stop it and retire its scope, whether or not it finished.
    /// `LaunchOp::STOP_RUNTIME`.
    pub const STOP_RUNTIME: u32 = 4;
}

/// `LaunchStatus` values crossing the boundary as integers.
pub mod launch_status {
    /// `LaunchStatus::OK`.
    pub const OK: u32 = 0;
    /// `LaunchStatus::NO_SUCH_TOOL`.
    pub const NO_SUCH_TOOL: u32 = 1;
    /// The candidate was not a sealed object, or was not lent at all.
    /// `LaunchStatus::NOT_SEALED`.
    pub const NOT_SEALED: u32 = 2;
    /// `LaunchStatus::UNAVAILABLE`.
    pub const UNAVAILABLE: u32 = 3;
    /// `LaunchStatus::TIMED_OUT`.
    pub const TIMED_OUT: u32 = 4;
    /// `LaunchStatus::FAULTED`.
    pub const FAULTED: u32 = 5;
}

/// `EngineOp` values crossing the boundary as integers.
pub mod engine_op {
    /// `EngineOp::INFER`.
    pub const INFER: u32 = 1;
    /// `EngineOp::QUERY`.
    pub const QUERY: u32 = 2;
}

/// `EngineStatus` values crossing the boundary as integers.
pub mod engine_status {
    /// `EngineStatus::OK`.
    pub const OK: u32 = 0;
    /// `EngineStatus::INVALID`.
    pub const INVALID: u32 = 1;
    /// The prompt did not fit the context, and was not silently cut.
    /// `EngineStatus::TOO_LONG`.
    pub const TOO_LONG: u32 = 2;
    /// `EngineStatus::NOT_READY`.
    pub const NOT_READY: u32 = 3;
    /// `EngineStatus::NO_BUFFER`.
    pub const NO_BUFFER: u32 = 4;
    /// The work that asked was closed while this was running.
    /// `EngineStatus::CANCELLED`.
    pub const CANCELLED: u32 = 5;
    /// The request was read and could not be served; the answer bytes are the reason, as Thalyx's engine reports one.
    /// `EngineStatus::FAILED`.
    pub const FAILED: u32 = 6;
}

/// `Scenario` values crossing the boundary as integers.
pub mod scenario {
    /// One work carries the vertical through.
    /// `Scenario::BASELINE`.
    pub const BASELINE: u32 = 1;
    /// Two works over the same version, both asking the same engine, both publishing against the same generation. One is refused and starts again over the version that won.
    /// `Scenario::RIVALS`.
    pub const RIVALS: u32 = 2;
    /// A work asks the engine for a long inference and its scope is closed while the engine computes for it; a second, unrelated work then uses the same engine.
    /// `Scenario::CANCEL`.
    pub const CANCEL: u32 = 3;
}

/// What the engine is asked, on both backends.
///
/// From the schema's fixture, so the native program, the Linux reference
/// and the gate ask one question from one source.
pub mod engine_case {
    /// Context the engine builds, in tokens.
    pub const CONTEXT_TOKENS: u64 = 512;
    /// Threads the engine computes a graph with.
    pub const COMPUTE_THREADS: u64 = 1;
    /// The publisher's two prompts, in order.
    pub const PUBLISHER_PROMPTS: [&str; 2] = ["hola hola", "hola"];
    /// Tokens each answer of the `publisher` case may run to.
    pub const PUBLISHER_PREDICT: u32 = 12;
    /// The rival's two prompts, different from the publisher's so an answer given to the wrong work would be visible.
    pub const RIVAL_PROMPTS: [&str; 2] = ["adios", "adios adios"];
    /// Tokens each answer of the `rival` case may run to.
    pub const RIVAL_PREDICT: u32 = 12;
    /// One inference long enough to be cancelled while it runs: about a second of generation on the emulated processor, against a closure that comes a quarter of a second in.
    pub const LONG_PROMPTS: [&str; 1] = ["hola hola hola hola hola hola"];
    /// Tokens each answer of the `long` case may run to.
    pub const LONG_PREDICT: u32 = 400;
}

/// The inline half of a host call; the bytes are in the shared region.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostRequest {
    /// HostOp.
    pub op: u32,
    /// Bytes the runtime wrote at the request offset.
    pub request_len: u32,
    /// The runtime's own call counter, echoed back.
    pub cookie: u64,
    pub arg0: u64,
    pub arg1: u64,
}

const _: () = assert!(size_of::<HostRequest>() == 32);
const _: () = assert!(align_of::<HostRequest>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for HostRequest {}

/// The inline half of a host call's answer.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct HostReply {
    /// Zero when the call was served.
    pub status: u32,
    /// Bytes the work wrote at the answer offset.
    pub answer_len: u32,
    /// Set once the machine has latched and refuses everything after.
    pub stopped: u32,
    pub reserved0: u32,
    pub value: u64,
}

const _: () = assert!(size_of::<HostReply>() == 24);
const _: () = assert!(align_of::<HostReply>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for HostReply {}

/// What one run of the language runtime produced.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RunMetrics {
    pub requests: u32,
    pub validations: u32,
    pub observations: u32,
    pub assertions: u32,
    pub inferences: u32,
    /// Finish.
    pub finish: u32,
    /// Bytes of answers the machine handed the program.
    pub answer_bytes: u64,
    /// Bytes the program returned. The compression's other side.
    pub returned_bytes: u64,
    pub wall_ns: u64,
}

const _: () = assert!(size_of::<RunMetrics>() == 48);
const _: () = assert!(align_of::<RunMetrics>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for RunMetrics {}

/// Ask the launcher to run a tool over the candidate lent with this message.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct LaunchRequest {
    /// LaunchOp.
    pub op: u32,
    /// Which tool. A launcher refuses one it has no image for.
    pub tool_id: u32,
    pub candidate_len: u64,
    /// So a verdict can be tied to the bytes it was about.
    pub candidate_digest: [u8; 32],
    pub seed: u64,
    pub deadline_ns: u64,
}

const _: () = assert!(size_of::<LaunchRequest>() == 64);
const _: () = assert!(align_of::<LaunchRequest>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for LaunchRequest {}

/// What the launcher saw the tool do.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct LaunchReply {
    /// LaunchStatus.
    pub status: u32,
    /// Zero is a pass and only zero is.
    pub exit_code: u32,
    pub checks_run: u32,
    pub checks_failed: u32,
    /// Nanoseconds the tool's own scope was charged.
    pub cpu_ns: u64,
    /// Pages its scope held at its most.
    pub pages: u64,
    /// The tool identity that actually ran.
    pub tool_id: u64,
    pub tool_config_digest: [u8; 32],
    /// Bytes of the candidate the tool actually read, as the tool reported them.
    pub bytes_read: u64,
    /// A digest over those bytes, so a verdict names what it was about.
    pub candidate_sum: u64,
}

const _: () = assert!(size_of::<LaunchReply>() == 88);
const _: () = assert!(align_of::<LaunchReply>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for LaunchReply {}

/// The header of a sealed candidate: what a tool is given, and nothing else.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CandidateHeader {
    /// CANDIDATE_MAGIC_LOW.
    pub magic: u32,
    pub version: u32,
    /// Names bound in this candidate.
    pub count: u32,
    pub reserved0: u32,
    /// The run's seed, so a tool cannot precompute a verdict.
    pub seed: u64,
    pub total_bytes: u64,
    /// The candidate root this was assembled from.
    pub root_digest: [u8; 32],
}

const _: () = assert!(size_of::<CandidateHeader>() == 64);
const _: () = assert!(align_of::<CandidateHeader>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for CandidateHeader {}

/// One name of a sealed candidate.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct CandidateEntry {
    /// Where its bytes start, from the beginning of the object.
    pub offset: u64,
    pub length: u64,
    pub name_len: u32,
    /// Bit 0: the content is a function body, not a script, and a tool has to compile it the way the runtime executes it.
    pub flags: u32,
    pub name: [u8; 32],
}

const _: () = assert!(size_of::<CandidateEntry>() == 56);
const _: () = assert!(align_of::<CandidateEntry>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for CandidateEntry {}

/// What a validation tool says about a candidate, in the region it shares.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct ToolReport {
    pub checks_run: u32,
    pub checks_failed: u32,
    /// Files the tool compiled.
    pub parsed: u32,
    pub parse_failed: u32,
    /// Bytes of the candidate it actually read.
    pub bytes_read: u64,
    /// A digest over those bytes, so a verdict names what it was about.
    pub candidate_sum: u64,
    /// The first check that did not hold, as the tool worded it.
    pub first_failure: [u8; 64],
}

const _: () = assert!(size_of::<ToolReport>() == 96);
const _: () = assert!(align_of::<ToolReport>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for ToolReport {}

/// Ask the engine for one inference.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct EngineRequest {
    /// EngineOp.
    pub op: u32,
    /// Tokens to generate at most.
    pub predict: u32,
    /// Bytes of prompt in the lent buffer.
    pub prompt_len: u32,
    /// Bytes of GBNF grammar right after the prompt in the lent buffer; zero for none. Thalyx's engine takes one per request.
    pub grammar_len: u32,
    pub seed: u64,
}

const _: () = assert!(size_of::<EngineRequest>() == 24);
const _: () = assert!(align_of::<EngineRequest>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for EngineRequest {}

/// What the engine did.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct EngineReply {
    /// EngineStatus.
    pub status: u32,
    pub prompt_tokens: u32,
    pub generated: u32,
    pub answer_len: u32,
    /// How long this inference took.
    pub elapsed_ns: u64,
    /// How long the weights took to load. Every answer carries it, so residency is a number a caller sees.
    pub load_ns: u64,
    /// Inferences served since loading.
    pub served: u64,
    /// The first token chosen, so two engines are comparable on a decision.
    pub first_token: u32,
    /// The margin that decision won by. A comparison of decisions is only meaningful when the decision was not a tie.
    pub first_margin_ppm: u32,
    /// A digest over every token generated.
    pub token_digest: u64,
    /// Bytes of weights held resident.
    pub weight_bytes: u64,
}

const _: () = assert!(size_of::<EngineReply>() == 64);
const _: () = assert!(align_of::<EngineReply>() == 8);

// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:
// the schema refuses a field that would need any.
unsafe impl Pod for EngineReply {}
