[package]
name = "thalyx-kernel"
description = "Thalyx-Kernel: x86_64 microkernel core."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
thalyx-abi.workspace = true
thalyx-boot-protocol.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
