/* Generated by tools/gen_abi.py from abi/schema/v0.json. Do not edit. */
/*
 * C binding of the Thalyx-Kernel V0 interface. It exists so the boundary is
 * expressed in a language with no Rust representation rules: if a structure
 * only laid out correctly under `repr(C)` by accident, the assertions below
 * would disagree with the Rust ones.
 */
#ifndef THALYX_ABI_H
#define THALYX_ABI_H

#include <stdint.h>
#include <stddef.h>

#define THALYX_ABI_VERSION_MAJOR 0u
#define THALYX_ABI_VERSION_MINOR 2u
#define THALYX_MAX_DESCRIPTOR_LEN 4096ull
#define THALYX_MAX_INLINE_PAYLOAD 256ull
#define THALYX_MAX_CAPS_PER_MESSAGE 4ull
#define THALYX_MAX_SCOPE_DEPTH 16ull
#define THALYX_MAX_DERIVE_DEPTH 32ull
#define THALYX_MAX_HANDLES_PER_DOMAIN 32ull
#define THALYX_MAX_ENDPOINT_QUEUE 8ull
#define THALYX_MAX_MEMORY_PAGES_PER_OBJECT 512ull
#define THALYX_CPU_WINDOW_NS 10000000ull
#define THALYX_CPU_QUANTUM_NS 1000000ull
#define THALYX_PAGE_SIZE 4096ull
#define THALYX_CONTROL_LOG_CAPACITY 64ull
#define THALYX_CONTROL_LOG_RESERVED 8ull
#define THALYX_RECEIPT_BATCH 4ull

#define THALYX_ENTRY_VERSION_QUERY 0ull
#define THALYX_ENTRY_INVOKE 1ull
#define THALYX_ENTRY_LIMITS_QUERY 2ull
#define THALYX_ENTRY_EXIT 3ull
#define THALYX_ENTRY_CLOCK_QUERY 4ull

#define THALYX_FLAG_NONBLOCKING (1ull << 0)

#define THALYX_TYPE_NONE 0u
#define THALYX_TYPE_SCOPE 1u
#define THALYX_TYPE_DOMAIN 2u
#define THALYX_TYPE_MEMORY 3u
#define THALYX_TYPE_ENDPOINT 4u
#define THALYX_TYPE_INVOCATION 5u
#define THALYX_TYPE_SIGNAL 6u
#define THALYX_TYPE_TIMER 7u
#define THALYX_TYPE_CONTROL_LOG 8u

#define THALYX_RIGHT_INSPECT (1u << 0)
#define THALYX_RIGHT_DERIVE (1u << 1)
#define THALYX_RIGHT_TRANSFER (1u << 2)
#define THALYX_RIGHT_DESTROY (1u << 3)
#define THALYX_RIGHT_ADMIN (1u << 4)
#define THALYX_RIGHT_SCOPE_CREATE (1u << 8)
#define THALYX_RIGHT_SCOPE_LIMIT (1u << 9)
#define THALYX_RIGHT_SCOPE_FENCE (1u << 10)
#define THALYX_RIGHT_SCOPE_EXEC (1u << 11)
#define THALYX_RIGHT_DOMAIN_BUILD (1u << 8)
#define THALYX_RIGHT_DOMAIN_ACTIVATE (1u << 9)
#define THALYX_RIGHT_DOMAIN_STOP (1u << 10)
#define THALYX_RIGHT_DOMAIN_WAIT (1u << 11)
#define THALYX_RIGHT_MEMORY_READ (1u << 8)
#define THALYX_RIGHT_MEMORY_WRITE (1u << 9)
#define THALYX_RIGHT_MEMORY_EXECUTE (1u << 10)
#define THALYX_RIGHT_MEMORY_MAP (1u << 11)
#define THALYX_RIGHT_MEMORY_SEAL (1u << 12)
#define THALYX_RIGHT_ENDPOINT_SEND (1u << 8)
#define THALYX_RIGHT_ENDPOINT_CALL (1u << 9)
#define THALYX_RIGHT_ENDPOINT_RECEIVE (1u << 10)
#define THALYX_RIGHT_ENDPOINT_BIND (1u << 11)
#define THALYX_RIGHT_INVOCATION_REPLY (1u << 8)
#define THALYX_RIGHT_INVOCATION_EFFECT (1u << 9)
#define THALYX_RIGHT_INVOCATION_RESOLVE (1u << 10)
#define THALYX_RIGHT_INVOCATION_BIND (1u << 11)
#define THALYX_RIGHT_SIGNAL_RAISE (1u << 8)
#define THALYX_RIGHT_SIGNAL_WAIT (1u << 9)
#define THALYX_RIGHT_TIMER_ARM (1u << 8)
#define THALYX_RIGHT_LOG_READ (1u << 8)
#define THALYX_RIGHT_LOG_APPEND (1u << 9)
#define THALYX_RIGHT_LOG_ACK (1u << 10)

#define THALYX_OP_CAP_INSPECT 0x00000001u
#define THALYX_OP_CAP_DERIVE 0x00000002u
#define THALYX_OP_CAP_COPY 0x00000003u
#define THALYX_OP_CAP_CLOSE 0x00000004u
#define THALYX_OP_CAP_FENCE 0x00000005u
#define THALYX_OP_CAP_DRAIN_STATUS 0x00000006u
#define THALYX_OP_SCOPE_CREATE_CHILD 0x00010001u
#define THALYX_OP_SCOPE_QUERY 0x00010002u
#define THALYX_OP_SCOPE_SET_LIMITS 0x00010003u
#define THALYX_OP_SCOPE_FENCE 0x00010004u
#define THALYX_OP_SCOPE_DRAIN_STATUS 0x00010005u
#define THALYX_OP_SCOPE_RETIRE 0x00010006u
#define THALYX_OP_SCOPE_CREATE_DOMAIN 0x00010007u
#define THALYX_OP_SCOPE_CREATE_MEMORY 0x00010008u
#define THALYX_OP_SCOPE_CREATE_ENDPOINT 0x00010009u
#define THALYX_OP_SCOPE_CREATE_SIGNAL 0x0001000Au
#define THALYX_OP_SCOPE_CREATE_TIMER 0x0001000Bu
#define THALYX_OP_DOMAIN_MAP 0x00020001u
#define THALYX_OP_DOMAIN_UNMAP 0x00020002u
#define THALYX_OP_DOMAIN_INSTALL_CAP 0x00020003u
#define THALYX_OP_DOMAIN_ADD_THREAD 0x00020004u
#define THALYX_OP_DOMAIN_SET_FAULT_CHANNEL 0x00020005u
#define THALYX_OP_DOMAIN_ACTIVATE 0x00020006u
#define THALYX_OP_DOMAIN_TERMINATE 0x00020007u
#define THALYX_OP_DOMAIN_QUERY 0x00020008u
#define THALYX_OP_MEMORY_QUERY 0x00030001u
#define THALYX_OP_MEMORY_COPY 0x00030002u
#define THALYX_OP_MEMORY_SEAL 0x00030003u
#define THALYX_OP_MEMORY_WRITE 0x00030004u
#define THALYX_OP_MEMORY_READ 0x00030005u
#define THALYX_OP_ENDPOINT_BIND_FACET 0x00040001u
#define THALYX_OP_ENDPOINT_CALL 0x00040002u
#define THALYX_OP_ENDPOINT_SEND 0x00040003u
#define THALYX_OP_ENDPOINT_RECEIVE 0x00040004u
#define THALYX_OP_ENDPOINT_QUERY 0x00040005u
#define THALYX_OP_INVOCATION_REPLY 0x00050001u
#define THALYX_OP_INVOCATION_BEGIN_EFFECT 0x00050002u
#define THALYX_OP_INVOCATION_RESOLVE 0x00050003u
#define THALYX_OP_INVOCATION_QUERY 0x00050004u
#define THALYX_OP_INVOCATION_BIND_WORKER 0x00050005u
#define THALYX_OP_INVOCATION_UNBIND_WORKER 0x00050006u
#define THALYX_OP_SIGNAL_RAISE 0x00060001u
#define THALYX_OP_SIGNAL_WAIT 0x00060002u
#define THALYX_OP_SIGNAL_QUERY 0x00060003u
#define THALYX_OP_TIMER_ARM 0x00070001u
#define THALYX_OP_TIMER_CANCEL 0x00070002u
#define THALYX_OP_TIMER_QUERY 0x00070003u
#define THALYX_OP_LOG_READ 0x00080001u
#define THALYX_OP_LOG_APPEND 0x00080002u
#define THALYX_OP_LOG_ACK 0x00080003u
#define THALYX_OP_LOG_QUERY 0x00080004u

#define THALYX_STATUS_OK (0)
#define THALYX_STATUS_UNSUPPORTED_ENTRY (-1)
#define THALYX_STATUS_INVALID_ARGUMENT (-2)
#define THALYX_STATUS_INCOMPATIBLE_VERSION (-3)
#define THALYX_STATUS_INVALID_HANDLE (-4)
#define THALYX_STATUS_WRONG_TYPE (-5)
#define THALYX_STATUS_INSUFFICIENT_RIGHTS (-6)
#define THALYX_STATUS_EXPIRED (-7)
#define THALYX_STATUS_SCOPE_CLOSED (-8)
#define THALYX_STATUS_LIMIT_EXHAUSTED (-9)
#define THALYX_STATUS_QUEUE_FULL (-10)
#define THALYX_STATUS_INVALID_ADDRESS (-11)
#define THALYX_STATUS_PEER_DEAD (-12)
#define THALYX_STATUS_CANCELLED (-13)
#define THALYX_STATUS_PENDING (-14)
#define THALYX_STATUS_WOULD_BLOCK (-15)
#define THALYX_STATUS_TIMED_OUT (-16)
#define THALYX_STATUS_ALREADY_RESOLVED (-17)
#define THALYX_STATUS_STATE_CONFLICT (-18)
#define THALYX_STATUS_DRAIN_INCOMPLETE (-19)
#define THALYX_STATUS_NOT_SUPPORTED (-20)

#define THALYX_SCOPE_STATE_OPEN 1u
#define THALYX_SCOPE_STATE_FENCED 2u
#define THALYX_SCOPE_STATE_QUIESCENT 3u
#define THALYX_SCOPE_STATE_RETIRED 4u
#define THALYX_MEMORY_STATE_MUTABLE 1u
#define THALYX_MEMORY_STATE_SEALING 2u
#define THALYX_MEMORY_STATE_SEALED 3u
#define THALYX_DOMAIN_STATE_BUILDING 1u
#define THALYX_DOMAIN_STATE_RUNNABLE 2u
#define THALYX_DOMAIN_STATE_FAULTED 3u
#define THALYX_DOMAIN_STATE_STOPPING 4u
#define THALYX_DOMAIN_STATE_DEAD 5u
#define THALYX_INVOCATION_STATE_ADMITTED 1u
#define THALYX_INVOCATION_STATE_DELIVERED 2u
#define THALYX_INVOCATION_STATE_RESOLVED 3u
#define THALYX_EFFECT_STATE_NONE 0u
#define THALYX_EFFECT_STATE_ADMITTED 1u
#define THALYX_EFFECT_STATE_REFUSED 2u
#define THALYX_EFFECT_STATE_RESOLVED 3u
#define THALYX_CANCEL_STATE_LIVE 0u
#define THALYX_CANCEL_STATE_ORIGIN_FENCED 1u
#define THALYX_CANCEL_STATE_ORIGIN_DEAD 2u
#define THALYX_OUTCOME_COMMITTED 1u
#define THALYX_OUTCOME_ABORTED 2u
#define THALYX_OUTCOME_UNKNOWN 3u
#define THALYX_CAP_OP_COPY 0u
#define THALYX_CAP_OP_MOVE 1u
#define THALYX_MESSAGE_KIND_REQUEST 1u
#define THALYX_MESSAGE_KIND_FAULT 2u
#define THALYX_RECEIPT_KIND_ADMIT 1u
#define THALYX_RECEIPT_KIND_EFFECT 2u
#define THALYX_RECEIPT_KIND_FENCE 3u
#define THALYX_RECEIPT_KIND_RETIRE 4u
#define THALYX_RECEIPT_KIND_SERVICE_NOTE 5u
#define THALYX_RECEIPT_KIND_OBJECT_LIFE 6u

#define THALYX_BOOT_SLOT_SELF_DOMAIN 1u
#define THALYX_BOOT_SLOT_SELF_SCOPE 2u
#define THALYX_BOOT_SLOT_CONTROL_LOG 3u
#define THALYX_BOOT_SLOT_FIRST_MODULE 4u

/* Common descriptor header fixed by vault/architecture/abi.md. */
typedef struct {
    uint16_t major; /* Descriptor major version. A mismatch is refused before effects. */
    uint16_t minor; /* Descriptor minor version. */
    uint32_t opcode; /* Operation selector. Must equal the operation passed in RSI. */
    uint32_t flags; /* Operation flags. Unknown bits are refused, never ignored. */
    uint32_t total_len; /* Whole descriptor length including this header. Must equal R10. */
    uint64_t cookie; /* Client correlation value. Not authorisation and not durable dedupe. */
    uint64_t reserved; /* Reserved, must be zero. */
} thalyx_descriptor_header_t;
_Static_assert(sizeof(thalyx_descriptor_header_t) == 32, "DescriptorHeader size");
_Static_assert(_Alignof(thalyx_descriptor_header_t) == 8, "DescriptorHeader alignment");
_Static_assert(offsetof(thalyx_descriptor_header_t, major) == 0, "DescriptorHeader.major offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, minor) == 2, "DescriptorHeader.minor offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, opcode) == 4, "DescriptorHeader.opcode offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, flags) == 8, "DescriptorHeader.flags offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, total_len) == 12, "DescriptorHeader.total_len offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, cookie) == 16, "DescriptorHeader.cookie offset");
_Static_assert(offsetof(thalyx_descriptor_header_t, reserved) == 24, "DescriptorHeader.reserved offset");

/* Effective interface limits reported by the LIMITS_QUERY entry. */
typedef struct {
    uint16_t major; /* Schema field `major`, little-endian `u16`. */
    uint16_t minor; /* Schema field `minor`, little-endian `u16`. */
    uint32_t max_descriptor_len; /* Schema field `max_descriptor_len`, little-endian `u32`. */
    uint32_t max_inline_payload; /* Schema field `max_inline_payload`, little-endian `u32`. */
    uint32_t max_caps_per_message; /* Schema field `max_caps_per_message`, little-endian `u32`. */
    uint32_t max_scope_depth; /* Schema field `max_scope_depth`, little-endian `u32`. */
    uint32_t max_derive_depth; /* Schema field `max_derive_depth`, little-endian `u32`. */
    uint32_t max_handles_per_domain; /* Schema field `max_handles_per_domain`, little-endian `u32`. */
    uint32_t max_endpoint_queue; /* Schema field `max_endpoint_queue`, little-endian `u32`. */
    uint32_t max_memory_pages_per_object; /* Schema field `max_memory_pages_per_object`, little-endian `u32`. */
    uint32_t control_log_capacity; /* Schema field `control_log_capacity`, little-endian `u32`. */
    uint32_t control_log_reserved; /* Schema field `control_log_reserved`, little-endian `u32`. */
    uint32_t receipt_batch; /* Schema field `receipt_batch`, little-endian `u32`. */
    uint64_t cpu_window_ns; /* Schema field `cpu_window_ns`, little-endian `u64`. */
    uint64_t cpu_quantum_ns; /* Schema field `cpu_quantum_ns`, little-endian `u64`. */
    uint64_t page_size; /* Schema field `page_size`, little-endian `u64`. */
    uint64_t boot_epoch; /* Schema field `boot_epoch`, little-endian `u64`. */
} thalyx_limits_t;
_Static_assert(sizeof(thalyx_limits_t) == 80, "Limits size");
_Static_assert(_Alignof(thalyx_limits_t) == 8, "Limits alignment");
_Static_assert(offsetof(thalyx_limits_t, major) == 0, "Limits.major offset");
_Static_assert(offsetof(thalyx_limits_t, minor) == 2, "Limits.minor offset");
_Static_assert(offsetof(thalyx_limits_t, max_descriptor_len) == 4, "Limits.max_descriptor_len offset");
_Static_assert(offsetof(thalyx_limits_t, max_inline_payload) == 8, "Limits.max_inline_payload offset");
_Static_assert(offsetof(thalyx_limits_t, max_caps_per_message) == 12, "Limits.max_caps_per_message offset");
_Static_assert(offsetof(thalyx_limits_t, max_scope_depth) == 16, "Limits.max_scope_depth offset");
_Static_assert(offsetof(thalyx_limits_t, max_derive_depth) == 20, "Limits.max_derive_depth offset");
_Static_assert(offsetof(thalyx_limits_t, max_handles_per_domain) == 24, "Limits.max_handles_per_domain offset");
_Static_assert(offsetof(thalyx_limits_t, max_endpoint_queue) == 28, "Limits.max_endpoint_queue offset");
_Static_assert(offsetof(thalyx_limits_t, max_memory_pages_per_object) == 32, "Limits.max_memory_pages_per_object offset");
_Static_assert(offsetof(thalyx_limits_t, control_log_capacity) == 36, "Limits.control_log_capacity offset");
_Static_assert(offsetof(thalyx_limits_t, control_log_reserved) == 40, "Limits.control_log_reserved offset");
_Static_assert(offsetof(thalyx_limits_t, receipt_batch) == 44, "Limits.receipt_batch offset");
_Static_assert(offsetof(thalyx_limits_t, cpu_window_ns) == 48, "Limits.cpu_window_ns offset");
_Static_assert(offsetof(thalyx_limits_t, cpu_quantum_ns) == 56, "Limits.cpu_quantum_ns offset");
_Static_assert(offsetof(thalyx_limits_t, page_size) == 64, "Limits.page_size offset");
_Static_assert(offsetof(thalyx_limits_t, boot_epoch) == 72, "Limits.boot_epoch offset");

/* What one capability names and what its lineage still permits. */
typedef struct {
    uint32_t object_type; /* Schema field `object_type`, little-endian `u32`. */
    uint32_t rights; /* Effective rights: never larger than any ancestor's. */
    uint32_t derive_depth; /* Schema field `derive_depth`, little-endian `u32`. */
    uint32_t lineage_state; /* 1 live, 2 fenced, 3 expired. */
    uint64_t grant_id; /* Schema field `grant_id`, little-endian `u64`. */
    uint64_t parent_grant_id; /* Schema field `parent_grant_id`, little-endian `u64`. */
    uint64_t deadline_ns; /* Zero means no deadline. */
    uint64_t life_scope_id; /* Schema field `life_scope_id`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
    uint64_t facet; /* Immutable endpoint facet, zero when the grant carries none. */
} thalyx_cap_info_t;
_Static_assert(sizeof(thalyx_cap_info_t) == 64, "CapInfo size");
_Static_assert(_Alignof(thalyx_cap_info_t) == 8, "CapInfo alignment");
_Static_assert(offsetof(thalyx_cap_info_t, object_type) == 0, "CapInfo.object_type offset");
_Static_assert(offsetof(thalyx_cap_info_t, rights) == 4, "CapInfo.rights offset");
_Static_assert(offsetof(thalyx_cap_info_t, derive_depth) == 8, "CapInfo.derive_depth offset");
_Static_assert(offsetof(thalyx_cap_info_t, lineage_state) == 12, "CapInfo.lineage_state offset");
_Static_assert(offsetof(thalyx_cap_info_t, grant_id) == 16, "CapInfo.grant_id offset");
_Static_assert(offsetof(thalyx_cap_info_t, parent_grant_id) == 24, "CapInfo.parent_grant_id offset");
_Static_assert(offsetof(thalyx_cap_info_t, deadline_ns) == 32, "CapInfo.deadline_ns offset");
_Static_assert(offsetof(thalyx_cap_info_t, life_scope_id) == 40, "CapInfo.life_scope_id offset");
_Static_assert(offsetof(thalyx_cap_info_t, object_id) == 48, "CapInfo.object_id offset");
_Static_assert(offsetof(thalyx_cap_info_t, facet) == 56, "CapInfo.facet offset");

/* Attenuation request. Rights outside the parent's and deadlines beyond it are refused. */
typedef struct {
    uint32_t rights_mask; /* Requested rights. Must be a subset of the parent's. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t deadline_ns; /* Zero keeps the parent's deadline; otherwise must not be later. */
    uint64_t life_scope; /* Optional extra scope handle bounding the child's life. Zero for none. */
} thalyx_derive_request_t;
_Static_assert(sizeof(thalyx_derive_request_t) == 24, "DeriveRequest size");
_Static_assert(_Alignof(thalyx_derive_request_t) == 8, "DeriveRequest alignment");
_Static_assert(offsetof(thalyx_derive_request_t, rights_mask) == 0, "DeriveRequest.rights_mask offset");
_Static_assert(offsetof(thalyx_derive_request_t, reserved0) == 4, "DeriveRequest.reserved0 offset");
_Static_assert(offsetof(thalyx_derive_request_t, deadline_ns) == 8, "DeriveRequest.deadline_ns offset");
_Static_assert(offsetof(thalyx_derive_request_t, life_scope) == 16, "DeriveRequest.life_scope offset");

/* Ceilings of one scope. Every one must fit inside every ancestor's. */
typedef struct {
    uint64_t memory_pages; /* Schema field `memory_pages`, little-endian `u64`. */
    uint64_t metadata_objects; /* Schema field `metadata_objects`, little-endian `u64`. */
    uint64_t cpu_budget_ns; /* Aggregate execution per fixed window. */
    uint64_t queue_bytes; /* Schema field `queue_bytes`, little-endian `u64`. */
    uint64_t closure_reserve_ns; /* Recovery reserve untouchable by ordinary work. */
    uint32_t parallelism; /* Schema field `parallelism`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_scope_limits_t;
_Static_assert(sizeof(thalyx_scope_limits_t) == 48, "ScopeLimits size");
_Static_assert(_Alignof(thalyx_scope_limits_t) == 8, "ScopeLimits alignment");
_Static_assert(offsetof(thalyx_scope_limits_t, memory_pages) == 0, "ScopeLimits.memory_pages offset");
_Static_assert(offsetof(thalyx_scope_limits_t, metadata_objects) == 8, "ScopeLimits.metadata_objects offset");
_Static_assert(offsetof(thalyx_scope_limits_t, cpu_budget_ns) == 16, "ScopeLimits.cpu_budget_ns offset");
_Static_assert(offsetof(thalyx_scope_limits_t, queue_bytes) == 24, "ScopeLimits.queue_bytes offset");
_Static_assert(offsetof(thalyx_scope_limits_t, closure_reserve_ns) == 32, "ScopeLimits.closure_reserve_ns offset");
_Static_assert(offsetof(thalyx_scope_limits_t, parallelism) == 40, "ScopeLimits.parallelism offset");
_Static_assert(offsetof(thalyx_scope_limits_t, reserved0) == 44, "ScopeLimits.reserved0 offset");

/* Create a child scope with its own ceilings and a diagnostic label. */
typedef struct {
    thalyx_scope_limits_t limits; /* Schema field `limits`, little-endian `struct:ScopeLimits`. */
    uint8_t label[16]; /* Diagnostic only. A name grants nothing. */
} thalyx_scope_create_request_t;
_Static_assert(sizeof(thalyx_scope_create_request_t) == 64, "ScopeCreateRequest size");
_Static_assert(_Alignof(thalyx_scope_create_request_t) == 8, "ScopeCreateRequest alignment");
_Static_assert(offsetof(thalyx_scope_create_request_t, limits) == 0, "ScopeCreateRequest.limits offset");
_Static_assert(offsetof(thalyx_scope_create_request_t, label) == 48, "ScopeCreateRequest.label offset");

/* Limits, consumption and debt of one scope. */
typedef struct {
    thalyx_scope_limits_t limits; /* Schema field `limits`, little-endian `struct:ScopeLimits`. */
    uint32_t state; /* Schema field `state`, little-endian `u32`. */
    uint32_t depth; /* Schema field `depth`, little-endian `u32`. */
    uint32_t parallelism_used; /* Schema field `parallelism_used`, little-endian `u32`. */
    uint32_t threads; /* Schema field `threads`, little-endian `u32`. */
    uint64_t scope_id; /* Schema field `scope_id`, little-endian `u64`. */
    uint64_t parent_scope_id; /* Schema field `parent_scope_id`, little-endian `u64`. */
    uint64_t memory_pages_used; /* Schema field `memory_pages_used`, little-endian `u64`. */
    uint64_t metadata_used; /* Schema field `metadata_used`, little-endian `u64`. */
    uint64_t queue_bytes_used; /* Schema field `queue_bytes_used`, little-endian `u64`. */
    uint64_t cpu_window_used_ns; /* Schema field `cpu_window_used_ns`, little-endian `u64`. */
    uint64_t cpu_total_ns; /* Schema field `cpu_total_ns`, little-endian `u64`. */
    uint64_t cpu_debt_ns; /* Schema field `cpu_debt_ns`, little-endian `u64`. */
    uint64_t closure_used_ns; /* Schema field `closure_used_ns`, little-endian `u64`. */
    uint64_t window_index; /* Schema field `window_index`, little-endian `u64`. */
} thalyx_scope_info_t;
_Static_assert(sizeof(thalyx_scope_info_t) == 144, "ScopeInfo size");
_Static_assert(_Alignof(thalyx_scope_info_t) == 8, "ScopeInfo alignment");
_Static_assert(offsetof(thalyx_scope_info_t, limits) == 0, "ScopeInfo.limits offset");
_Static_assert(offsetof(thalyx_scope_info_t, state) == 48, "ScopeInfo.state offset");
_Static_assert(offsetof(thalyx_scope_info_t, depth) == 52, "ScopeInfo.depth offset");
_Static_assert(offsetof(thalyx_scope_info_t, parallelism_used) == 56, "ScopeInfo.parallelism_used offset");
_Static_assert(offsetof(thalyx_scope_info_t, threads) == 60, "ScopeInfo.threads offset");
_Static_assert(offsetof(thalyx_scope_info_t, scope_id) == 64, "ScopeInfo.scope_id offset");
_Static_assert(offsetof(thalyx_scope_info_t, parent_scope_id) == 72, "ScopeInfo.parent_scope_id offset");
_Static_assert(offsetof(thalyx_scope_info_t, memory_pages_used) == 80, "ScopeInfo.memory_pages_used offset");
_Static_assert(offsetof(thalyx_scope_info_t, metadata_used) == 88, "ScopeInfo.metadata_used offset");
_Static_assert(offsetof(thalyx_scope_info_t, queue_bytes_used) == 96, "ScopeInfo.queue_bytes_used offset");
_Static_assert(offsetof(thalyx_scope_info_t, cpu_window_used_ns) == 104, "ScopeInfo.cpu_window_used_ns offset");
_Static_assert(offsetof(thalyx_scope_info_t, cpu_total_ns) == 112, "ScopeInfo.cpu_total_ns offset");
_Static_assert(offsetof(thalyx_scope_info_t, cpu_debt_ns) == 120, "ScopeInfo.cpu_debt_ns offset");
_Static_assert(offsetof(thalyx_scope_info_t, closure_used_ns) == 128, "ScopeInfo.closure_used_ns offset");
_Static_assert(offsetof(thalyx_scope_info_t, window_index) == 136, "ScopeInfo.window_index offset");

/* What a closing perimeter still holds. A timeout is not quiescence. */
typedef struct {
    uint32_t state; /* Schema field `state`, little-endian `u32`. */
    uint32_t threads_running; /* Schema field `threads_running`, little-endian `u32`. */
    uint32_t invocations_pending; /* Schema field `invocations_pending`, little-endian `u32`. */
    uint32_t effects_pending; /* Schema field `effects_pending`, little-endian `u32`. */
    uint32_t maps_pending; /* Schema field `maps_pending`, little-endian `u32`. */
    uint32_t undelivered_cancelled; /* Schema field `undelivered_cancelled`, little-endian `u32`. */
    uint32_t external_unknown; /* Schema field `external_unknown`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t retained_pages; /* Schema field `retained_pages`, little-endian `u64`. */
    uint64_t retained_metadata; /* Schema field `retained_metadata`, little-endian `u64`. */
    uint64_t last_progress_ns; /* Schema field `last_progress_ns`, little-endian `u64`. */
    uint64_t token; /* Stable progress token; equal tokens mean no progress was made. */
} thalyx_drain_report_t;
_Static_assert(sizeof(thalyx_drain_report_t) == 64, "DrainReport size");
_Static_assert(_Alignof(thalyx_drain_report_t) == 8, "DrainReport alignment");
_Static_assert(offsetof(thalyx_drain_report_t, state) == 0, "DrainReport.state offset");
_Static_assert(offsetof(thalyx_drain_report_t, threads_running) == 4, "DrainReport.threads_running offset");
_Static_assert(offsetof(thalyx_drain_report_t, invocations_pending) == 8, "DrainReport.invocations_pending offset");
_Static_assert(offsetof(thalyx_drain_report_t, effects_pending) == 12, "DrainReport.effects_pending offset");
_Static_assert(offsetof(thalyx_drain_report_t, maps_pending) == 16, "DrainReport.maps_pending offset");
_Static_assert(offsetof(thalyx_drain_report_t, undelivered_cancelled) == 20, "DrainReport.undelivered_cancelled offset");
_Static_assert(offsetof(thalyx_drain_report_t, external_unknown) == 24, "DrainReport.external_unknown offset");
_Static_assert(offsetof(thalyx_drain_report_t, reserved0) == 28, "DrainReport.reserved0 offset");
_Static_assert(offsetof(thalyx_drain_report_t, retained_pages) == 32, "DrainReport.retained_pages offset");
_Static_assert(offsetof(thalyx_drain_report_t, retained_metadata) == 40, "DrainReport.retained_metadata offset");
_Static_assert(offsetof(thalyx_drain_report_t, last_progress_ns) == 48, "DrainReport.last_progress_ns offset");
_Static_assert(offsetof(thalyx_drain_report_t, token) == 56, "DrainReport.token offset");

/* Build a domain from an image object the caller may read. */
typedef struct {
    uint64_t image_handle; /* Schema field `image_handle`, little-endian `u64`. */
    uint8_t name[16]; /* Diagnostic only. */
} thalyx_domain_create_request_t;
_Static_assert(sizeof(thalyx_domain_create_request_t) == 24, "DomainCreateRequest size");
_Static_assert(_Alignof(thalyx_domain_create_request_t) == 8, "DomainCreateRequest alignment");
_Static_assert(offsetof(thalyx_domain_create_request_t, image_handle) == 0, "DomainCreateRequest.image_handle offset");
_Static_assert(offsetof(thalyx_domain_create_request_t, name) == 8, "DomainCreateRequest.name offset");

/* Install one mapping. Rights are checked against the capability and the platform. */
typedef struct {
    uint64_t memory_handle; /* Schema field `memory_handle`, little-endian `u64`. */
    uint64_t vaddr; /* Schema field `vaddr`, little-endian `u64`. */
    uint32_t offset_pages; /* Schema field `offset_pages`, little-endian `u32`. */
    uint32_t page_count; /* Schema field `page_count`, little-endian `u32`. */
    uint32_t rights; /* Subset of MEMORY_READ/WRITE/EXECUTE. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_map_request_t;
_Static_assert(sizeof(thalyx_map_request_t) == 32, "MapRequest size");
_Static_assert(_Alignof(thalyx_map_request_t) == 8, "MapRequest alignment");
_Static_assert(offsetof(thalyx_map_request_t, memory_handle) == 0, "MapRequest.memory_handle offset");
_Static_assert(offsetof(thalyx_map_request_t, vaddr) == 8, "MapRequest.vaddr offset");
_Static_assert(offsetof(thalyx_map_request_t, offset_pages) == 16, "MapRequest.offset_pages offset");
_Static_assert(offsetof(thalyx_map_request_t, page_count) == 20, "MapRequest.page_count offset");
_Static_assert(offsetof(thalyx_map_request_t, rights) == 24, "MapRequest.rights offset");
_Static_assert(offsetof(thalyx_map_request_t, reserved0) == 28, "MapRequest.reserved0 offset");

/* Withdraw a mapping range and its translations. */
typedef struct {
    uint64_t vaddr; /* Schema field `vaddr`, little-endian `u64`. */
    uint32_t page_count; /* Schema field `page_count`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_unmap_request_t;
_Static_assert(sizeof(thalyx_unmap_request_t) == 16, "UnmapRequest size");
_Static_assert(_Alignof(thalyx_unmap_request_t) == 8, "UnmapRequest alignment");
_Static_assert(offsetof(thalyx_unmap_request_t, vaddr) == 0, "UnmapRequest.vaddr offset");
_Static_assert(offsetof(thalyx_unmap_request_t, page_count) == 8, "UnmapRequest.page_count offset");
_Static_assert(offsetof(thalyx_unmap_request_t, reserved0) == 12, "UnmapRequest.reserved0 offset");

/* Install a capability into a building domain's table at a chosen slot. */
typedef struct {
    uint64_t source_handle; /* Schema field `source_handle`, little-endian `u64`. */
    uint64_t deadline_ns; /* Zero keeps the source deadline. */
    uint32_t target_slot; /* Schema field `target_slot`, little-endian `u32`. */
    uint32_t rights_mask; /* Attenuation applied while installing; never an amplification. */
} thalyx_install_cap_request_t;
_Static_assert(sizeof(thalyx_install_cap_request_t) == 24, "InstallCapRequest size");
_Static_assert(_Alignof(thalyx_install_cap_request_t) == 8, "InstallCapRequest alignment");
_Static_assert(offsetof(thalyx_install_cap_request_t, source_handle) == 0, "InstallCapRequest.source_handle offset");
_Static_assert(offsetof(thalyx_install_cap_request_t, deadline_ns) == 8, "InstallCapRequest.deadline_ns offset");
_Static_assert(offsetof(thalyx_install_cap_request_t, target_slot) == 16, "InstallCapRequest.target_slot offset");
_Static_assert(offsetof(thalyx_install_cap_request_t, rights_mask) == 20, "InstallCapRequest.rights_mask offset");

/* Create one thread of a building domain. */
typedef struct {
    uint64_t entry; /* Schema field `entry`, little-endian `u64`. */
    uint64_t stack_top; /* Must be inside a writable mapping of the domain. */
    uint64_t argument; /* Passed to the thread in RDI. */
    uint64_t reserved0; /* Reserved, must be zero. */
} thalyx_thread_create_request_t;
_Static_assert(sizeof(thalyx_thread_create_request_t) == 32, "ThreadCreateRequest size");
_Static_assert(_Alignof(thalyx_thread_create_request_t) == 8, "ThreadCreateRequest alignment");
_Static_assert(offsetof(thalyx_thread_create_request_t, entry) == 0, "ThreadCreateRequest.entry offset");
_Static_assert(offsetof(thalyx_thread_create_request_t, stack_top) == 8, "ThreadCreateRequest.stack_top offset");
_Static_assert(offsetof(thalyx_thread_create_request_t, argument) == 16, "ThreadCreateRequest.argument offset");
_Static_assert(offsetof(thalyx_thread_create_request_t, reserved0) == 24, "ThreadCreateRequest.reserved0 offset");

/* Endpoint a fault of this domain is reported on, with a record reserved in advance. */
typedef struct {
    uint64_t endpoint_handle; /* Schema field `endpoint_handle`, little-endian `u64`. */
    uint64_t reserved0; /* Reserved, must be zero. */
} thalyx_fault_channel_request_t;
_Static_assert(sizeof(thalyx_fault_channel_request_t) == 16, "FaultChannelRequest size");
_Static_assert(_Alignof(thalyx_fault_channel_request_t) == 8, "FaultChannelRequest alignment");
_Static_assert(offsetof(thalyx_fault_channel_request_t, endpoint_handle) == 0, "FaultChannelRequest.endpoint_handle offset");
_Static_assert(offsetof(thalyx_fault_channel_request_t, reserved0) == 8, "FaultChannelRequest.reserved0 offset");

/* Lifecycle, faults and exit of one domain. */
typedef struct {
    uint32_t state; /* Schema field `state`, little-endian `u32`. */
    uint32_t threads; /* Schema field `threads`, little-endian `u32`. */
    uint32_t faults; /* Schema field `faults`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t domain_id; /* Schema field `domain_id`, little-endian `u64`. */
    uint64_t owner_scope_id; /* Schema field `owner_scope_id`, little-endian `u64`. */
    uint64_t exit_code; /* Schema field `exit_code`, little-endian `u64`. */
    uint64_t fault_vector; /* Schema field `fault_vector`, little-endian `u64`. */
    uint64_t fault_rip; /* Schema field `fault_rip`, little-endian `u64`. */
    uint64_t charged_pages; /* Schema field `charged_pages`, little-endian `u64`. */
} thalyx_domain_info_t;
_Static_assert(sizeof(thalyx_domain_info_t) == 64, "DomainInfo size");
_Static_assert(_Alignof(thalyx_domain_info_t) == 8, "DomainInfo alignment");
_Static_assert(offsetof(thalyx_domain_info_t, state) == 0, "DomainInfo.state offset");
_Static_assert(offsetof(thalyx_domain_info_t, threads) == 4, "DomainInfo.threads offset");
_Static_assert(offsetof(thalyx_domain_info_t, faults) == 8, "DomainInfo.faults offset");
_Static_assert(offsetof(thalyx_domain_info_t, reserved0) == 12, "DomainInfo.reserved0 offset");
_Static_assert(offsetof(thalyx_domain_info_t, domain_id) == 16, "DomainInfo.domain_id offset");
_Static_assert(offsetof(thalyx_domain_info_t, owner_scope_id) == 24, "DomainInfo.owner_scope_id offset");
_Static_assert(offsetof(thalyx_domain_info_t, exit_code) == 32, "DomainInfo.exit_code offset");
_Static_assert(offsetof(thalyx_domain_info_t, fault_vector) == 40, "DomainInfo.fault_vector offset");
_Static_assert(offsetof(thalyx_domain_info_t, fault_rip) == 48, "DomainInfo.fault_rip offset");
_Static_assert(offsetof(thalyx_domain_info_t, charged_pages) == 56, "DomainInfo.charged_pages offset");

/* Reserve resident pages before the object becomes visible. */
typedef struct {
    uint64_t pages; /* Schema field `pages`, little-endian `u64`. */
    uint32_t max_rights; /* Schema field `max_rights`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint8_t label[16]; /* Schema field `label`, little-endian `u8[16]`. */
} thalyx_memory_create_request_t;
_Static_assert(sizeof(thalyx_memory_create_request_t) == 32, "MemoryCreateRequest size");
_Static_assert(_Alignof(thalyx_memory_create_request_t) == 8, "MemoryCreateRequest alignment");
_Static_assert(offsetof(thalyx_memory_create_request_t, pages) == 0, "MemoryCreateRequest.pages offset");
_Static_assert(offsetof(thalyx_memory_create_request_t, max_rights) == 8, "MemoryCreateRequest.max_rights offset");
_Static_assert(offsetof(thalyx_memory_create_request_t, reserved0) == 12, "MemoryCreateRequest.reserved0 offset");
_Static_assert(offsetof(thalyx_memory_create_request_t, label) == 16, "MemoryCreateRequest.label offset");

/* Size, maximum rights, seal state and alias counts of one memory object. */
typedef struct {
    uint32_t state; /* Schema field `state`, little-endian `u32`. */
    uint32_t max_rights; /* Schema field `max_rights`, little-endian `u32`. */
    uint32_t map_count; /* Schema field `map_count`, little-endian `u32`. */
    uint32_t writable_maps; /* Schema field `writable_maps`, little-endian `u32`. */
    uint64_t pages; /* Schema field `pages`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
    uint64_t sponsor_scope_id; /* Schema field `sponsor_scope_id`, little-endian `u64`. */
    uint8_t label[16]; /* Schema field `label`, little-endian `u8[16]`. */
} thalyx_memory_info_t;
_Static_assert(sizeof(thalyx_memory_info_t) == 56, "MemoryInfo size");
_Static_assert(_Alignof(thalyx_memory_info_t) == 8, "MemoryInfo alignment");
_Static_assert(offsetof(thalyx_memory_info_t, state) == 0, "MemoryInfo.state offset");
_Static_assert(offsetof(thalyx_memory_info_t, max_rights) == 4, "MemoryInfo.max_rights offset");
_Static_assert(offsetof(thalyx_memory_info_t, map_count) == 8, "MemoryInfo.map_count offset");
_Static_assert(offsetof(thalyx_memory_info_t, writable_maps) == 12, "MemoryInfo.writable_maps offset");
_Static_assert(offsetof(thalyx_memory_info_t, pages) == 16, "MemoryInfo.pages offset");
_Static_assert(offsetof(thalyx_memory_info_t, object_id) == 24, "MemoryInfo.object_id offset");
_Static_assert(offsetof(thalyx_memory_info_t, sponsor_scope_id) == 32, "MemoryInfo.sponsor_scope_id offset");
_Static_assert(offsetof(thalyx_memory_info_t, label) == 40, "MemoryInfo.label offset");

/* Copy a bounded range between two memory objects. */
typedef struct {
    uint64_t source_handle; /* Schema field `source_handle`, little-endian `u64`. */
    uint64_t source_offset; /* Schema field `source_offset`, little-endian `u64`. */
    uint64_t dest_offset; /* Schema field `dest_offset`, little-endian `u64`. */
    uint64_t length; /* Schema field `length`, little-endian `u64`. */
} thalyx_memory_copy_request_t;
_Static_assert(sizeof(thalyx_memory_copy_request_t) == 32, "MemoryCopyRequest size");
_Static_assert(_Alignof(thalyx_memory_copy_request_t) == 8, "MemoryCopyRequest alignment");
_Static_assert(offsetof(thalyx_memory_copy_request_t, source_handle) == 0, "MemoryCopyRequest.source_handle offset");
_Static_assert(offsetof(thalyx_memory_copy_request_t, source_offset) == 8, "MemoryCopyRequest.source_offset offset");
_Static_assert(offsetof(thalyx_memory_copy_request_t, dest_offset) == 16, "MemoryCopyRequest.dest_offset offset");
_Static_assert(offsetof(thalyx_memory_copy_request_t, length) == 24, "MemoryCopyRequest.length offset");

/* Mediated read or write of a bounded range. */
typedef struct {
    uint64_t offset; /* Schema field `offset`, little-endian `u64`. */
    uint64_t length; /* Schema field `length`, little-endian `u64`. */
    uint8_t bytes[256]; /* Schema field `bytes`, little-endian `u8[256]`. */
} thalyx_memory_bytes_t;
_Static_assert(sizeof(thalyx_memory_bytes_t) == 272, "MemoryBytes size");
_Static_assert(_Alignof(thalyx_memory_bytes_t) == 8, "MemoryBytes alignment");
_Static_assert(offsetof(thalyx_memory_bytes_t, offset) == 0, "MemoryBytes.offset offset");
_Static_assert(offsetof(thalyx_memory_bytes_t, length) == 8, "MemoryBytes.length offset");
_Static_assert(offsetof(thalyx_memory_bytes_t, bytes) == 16, "MemoryBytes.bytes offset");

/* Create an endpoint with fixed queue capacity. */
typedef struct {
    uint32_t queue_capacity; /* Schema field `queue_capacity`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint8_t label[16]; /* Schema field `label`, little-endian `u8[16]`. */
} thalyx_endpoint_create_request_t;
_Static_assert(sizeof(thalyx_endpoint_create_request_t) == 24, "EndpointCreateRequest size");
_Static_assert(_Alignof(thalyx_endpoint_create_request_t) == 4, "EndpointCreateRequest alignment");
_Static_assert(offsetof(thalyx_endpoint_create_request_t, queue_capacity) == 0, "EndpointCreateRequest.queue_capacity offset");
_Static_assert(offsetof(thalyx_endpoint_create_request_t, reserved0) == 4, "EndpointCreateRequest.reserved0 offset");
_Static_assert(offsetof(thalyx_endpoint_create_request_t, label) == 8, "EndpointCreateRequest.label offset");

/* Administration that mints a send capability bound to one logical object. */
typedef struct {
    uint64_t facet; /* Opaque, immutable, unique within the endpoint epoch. */
    uint64_t deadline_ns; /* Schema field `deadline_ns`, little-endian `u64`. */
    uint32_t rights_mask; /* Schema field `rights_mask`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_bind_facet_request_t;
_Static_assert(sizeof(thalyx_bind_facet_request_t) == 24, "BindFacetRequest size");
_Static_assert(_Alignof(thalyx_bind_facet_request_t) == 8, "BindFacetRequest alignment");
_Static_assert(offsetof(thalyx_bind_facet_request_t, facet) == 0, "BindFacetRequest.facet offset");
_Static_assert(offsetof(thalyx_bind_facet_request_t, deadline_ns) == 8, "BindFacetRequest.deadline_ns offset");
_Static_assert(offsetof(thalyx_bind_facet_request_t, rights_mask) == 16, "BindFacetRequest.rights_mask offset");
_Static_assert(offsetof(thalyx_bind_facet_request_t, reserved0) == 20, "BindFacetRequest.reserved0 offset");

/* Queue occupancy and epoch of one endpoint. */
typedef struct {
    uint32_t queue_capacity; /* Schema field `queue_capacity`, little-endian `u32`. */
    uint32_t queued; /* Schema field `queued`, little-endian `u32`. */
    uint32_t reserved_cells; /* Reserved, must be zero. */
    uint32_t facets; /* Schema field `facets`, little-endian `u32`. */
    uint64_t epoch; /* Schema field `epoch`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
    uint64_t admitted; /* Schema field `admitted`, little-endian `u64`. */
    uint64_t delivered; /* Schema field `delivered`, little-endian `u64`. */
} thalyx_endpoint_info_t;
_Static_assert(sizeof(thalyx_endpoint_info_t) == 48, "EndpointInfo size");
_Static_assert(_Alignof(thalyx_endpoint_info_t) == 8, "EndpointInfo alignment");
_Static_assert(offsetof(thalyx_endpoint_info_t, queue_capacity) == 0, "EndpointInfo.queue_capacity offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, queued) == 4, "EndpointInfo.queued offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, reserved_cells) == 8, "EndpointInfo.reserved_cells offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, facets) == 12, "EndpointInfo.facets offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, epoch) == 16, "EndpointInfo.epoch offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, object_id) == 24, "EndpointInfo.object_id offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, admitted) == 32, "EndpointInfo.admitted offset");
_Static_assert(offsetof(thalyx_endpoint_info_t, delivered) == 40, "EndpointInfo.delivered offset");

/* Built by the kernel. A payload cannot overwrite any field of it. */
typedef struct {
    uint64_t epoch; /* Schema field `epoch`, little-endian `u64`. */
    uint64_t invocation_id; /* Schema field `invocation_id`, little-endian `u64`. */
    uint64_t sender_domain_id; /* Schema field `sender_domain_id`, little-endian `u64`. */
    uint64_t sender_scope_id; /* Schema field `sender_scope_id`, little-endian `u64`. */
    uint64_t parent_invocation_id; /* Schema field `parent_invocation_id`, little-endian `u64`. */
    uint64_t facet; /* Schema field `facet`, little-endian `u64`. */
    uint64_t grant_id; /* Schema field `grant_id`, little-endian `u64`. */
    uint64_t sent_ns; /* Schema field `sent_ns`, little-endian `u64`. */
    uint32_t rights_transferred; /* Schema field `rights_transferred`, little-endian `u32`. */
    uint32_t cancel_state; /* Schema field `cancel_state`, little-endian `u32`. */
    uint32_t kind; /* Schema field `kind`, little-endian `u32`. */
    uint32_t payload_len; /* Schema field `payload_len`, little-endian `u32`. */
} thalyx_message_header_t;
_Static_assert(sizeof(thalyx_message_header_t) == 80, "MessageHeader size");
_Static_assert(_Alignof(thalyx_message_header_t) == 8, "MessageHeader alignment");
_Static_assert(offsetof(thalyx_message_header_t, epoch) == 0, "MessageHeader.epoch offset");
_Static_assert(offsetof(thalyx_message_header_t, invocation_id) == 8, "MessageHeader.invocation_id offset");
_Static_assert(offsetof(thalyx_message_header_t, sender_domain_id) == 16, "MessageHeader.sender_domain_id offset");
_Static_assert(offsetof(thalyx_message_header_t, sender_scope_id) == 24, "MessageHeader.sender_scope_id offset");
_Static_assert(offsetof(thalyx_message_header_t, parent_invocation_id) == 32, "MessageHeader.parent_invocation_id offset");
_Static_assert(offsetof(thalyx_message_header_t, facet) == 40, "MessageHeader.facet offset");
_Static_assert(offsetof(thalyx_message_header_t, grant_id) == 48, "MessageHeader.grant_id offset");
_Static_assert(offsetof(thalyx_message_header_t, sent_ns) == 56, "MessageHeader.sent_ns offset");
_Static_assert(offsetof(thalyx_message_header_t, rights_transferred) == 64, "MessageHeader.rights_transferred offset");
_Static_assert(offsetof(thalyx_message_header_t, cancel_state) == 68, "MessageHeader.cancel_state offset");
_Static_assert(offsetof(thalyx_message_header_t, kind) == 72, "MessageHeader.kind offset");
_Static_assert(offsetof(thalyx_message_header_t, payload_len) == 76, "MessageHeader.payload_len offset");

/* One message: bounded payload plus at most four capabilities, all or nothing. */
typedef struct {
    uint32_t payload_len; /* Schema field `payload_len`, little-endian `u32`. */
    uint32_t cap_count; /* Schema field `cap_count`, little-endian `u32`. */
    uint64_t caps[4]; /* Schema field `caps`, little-endian `u64[4]`. */
    uint32_t cap_ops[4]; /* COPY or MOVE per capability. */
    uint8_t payload[256]; /* Schema field `payload`, little-endian `u8[256]`. */
} thalyx_send_request_t;
_Static_assert(sizeof(thalyx_send_request_t) == 312, "SendRequest size");
_Static_assert(_Alignof(thalyx_send_request_t) == 8, "SendRequest alignment");
_Static_assert(offsetof(thalyx_send_request_t, payload_len) == 0, "SendRequest.payload_len offset");
_Static_assert(offsetof(thalyx_send_request_t, cap_count) == 4, "SendRequest.cap_count offset");
_Static_assert(offsetof(thalyx_send_request_t, caps) == 8, "SendRequest.caps offset");
_Static_assert(offsetof(thalyx_send_request_t, cap_ops) == 40, "SendRequest.cap_ops offset");
_Static_assert(offsetof(thalyx_send_request_t, payload) == 56, "SendRequest.payload offset");

/* Reply of a synchronous call. Absence of a reply never means absence of effect. */
typedef struct {
    uint32_t payload_len; /* Schema field `payload_len`, little-endian `u32`. */
    uint32_t cap_count; /* Schema field `cap_count`, little-endian `u32`. */
    uint64_t caps[4]; /* Schema field `caps`, little-endian `u64[4]`. */
    uint64_t result; /* Schema field `result`, little-endian `u64`. */
    uint64_t invocation_id; /* Schema field `invocation_id`, little-endian `u64`. */
    uint8_t payload[256]; /* Schema field `payload`, little-endian `u8[256]`. */
} thalyx_call_result_t;
_Static_assert(sizeof(thalyx_call_result_t) == 312, "CallResult size");
_Static_assert(_Alignof(thalyx_call_result_t) == 8, "CallResult alignment");
_Static_assert(offsetof(thalyx_call_result_t, payload_len) == 0, "CallResult.payload_len offset");
_Static_assert(offsetof(thalyx_call_result_t, cap_count) == 4, "CallResult.cap_count offset");
_Static_assert(offsetof(thalyx_call_result_t, caps) == 8, "CallResult.caps offset");
_Static_assert(offsetof(thalyx_call_result_t, result) == 40, "CallResult.result offset");
_Static_assert(offsetof(thalyx_call_result_t, invocation_id) == 48, "CallResult.invocation_id offset");
_Static_assert(offsetof(thalyx_call_result_t, payload) == 56, "CallResult.payload offset");

/* An authenticated header, untrusted bytes and installed capabilities. */
typedef struct {
    thalyx_message_header_t header; /* Schema field `header`, little-endian `struct:MessageHeader`. */
    uint32_t cap_count; /* Schema field `cap_count`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t caps[4]; /* Schema field `caps`, little-endian `u64[4]`. */
    uint8_t payload[256]; /* Schema field `payload`, little-endian `u8[256]`. */
} thalyx_receive_result_t;
_Static_assert(sizeof(thalyx_receive_result_t) == 376, "ReceiveResult size");
_Static_assert(_Alignof(thalyx_receive_result_t) == 8, "ReceiveResult alignment");
_Static_assert(offsetof(thalyx_receive_result_t, header) == 0, "ReceiveResult.header offset");
_Static_assert(offsetof(thalyx_receive_result_t, cap_count) == 80, "ReceiveResult.cap_count offset");
_Static_assert(offsetof(thalyx_receive_result_t, reserved0) == 84, "ReceiveResult.reserved0 offset");
_Static_assert(offsetof(thalyx_receive_result_t, caps) == 88, "ReceiveResult.caps offset");
_Static_assert(offsetof(thalyx_receive_result_t, payload) == 120, "ReceiveResult.payload offset");

/* One-shot reply bound to one invocation. */
typedef struct {
    uint32_t payload_len; /* Schema field `payload_len`, little-endian `u32`. */
    uint32_t cap_count; /* Schema field `cap_count`, little-endian `u32`. */
    uint64_t caps[4]; /* Schema field `caps`, little-endian `u64[4]`. */
    uint32_t cap_ops[4]; /* Schema field `cap_ops`, little-endian `u32[4]`. */
    uint64_t result; /* Schema field `result`, little-endian `u64`. */
    uint8_t payload[256]; /* Schema field `payload`, little-endian `u8[256]`. */
} thalyx_reply_request_t;
_Static_assert(sizeof(thalyx_reply_request_t) == 320, "ReplyRequest size");
_Static_assert(_Alignof(thalyx_reply_request_t) == 8, "ReplyRequest alignment");
_Static_assert(offsetof(thalyx_reply_request_t, payload_len) == 0, "ReplyRequest.payload_len offset");
_Static_assert(offsetof(thalyx_reply_request_t, cap_count) == 4, "ReplyRequest.cap_count offset");
_Static_assert(offsetof(thalyx_reply_request_t, caps) == 8, "ReplyRequest.caps offset");
_Static_assert(offsetof(thalyx_reply_request_t, cap_ops) == 40, "ReplyRequest.cap_ops offset");
_Static_assert(offsetof(thalyx_reply_request_t, result) == 56, "ReplyRequest.result offset");
_Static_assert(offsetof(thalyx_reply_request_t, payload) == 64, "ReplyRequest.payload offset");

/* Effect admission: the same lineage checked again under the same synchronisation. */
typedef struct {
    uint64_t closure_reserve_ns; /* Recovery budget reserved before the effect is permitted. */
    uint32_t effect_kind; /* Schema field `effect_kind`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_effect_request_t;
_Static_assert(sizeof(thalyx_effect_request_t) == 16, "EffectRequest size");
_Static_assert(_Alignof(thalyx_effect_request_t) == 8, "EffectRequest alignment");
_Static_assert(offsetof(thalyx_effect_request_t, closure_reserve_ns) == 0, "EffectRequest.closure_reserve_ns offset");
_Static_assert(offsetof(thalyx_effect_request_t, effect_kind) == 8, "EffectRequest.effect_kind offset");
_Static_assert(offsetof(thalyx_effect_request_t, reserved0) == 12, "EffectRequest.reserved0 offset");

/* Discharge of a retained obligation with an explicit outcome. */
typedef struct {
    uint32_t outcome; /* Schema field `outcome`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t detail; /* Schema field `detail`, little-endian `u64`. */
} thalyx_resolve_request_t;
_Static_assert(sizeof(thalyx_resolve_request_t) == 16, "ResolveRequest size");
_Static_assert(_Alignof(thalyx_resolve_request_t) == 8, "ResolveRequest alignment");
_Static_assert(offsetof(thalyx_resolve_request_t, outcome) == 0, "ResolveRequest.outcome offset");
_Static_assert(offsetof(thalyx_resolve_request_t, reserved0) == 4, "ResolveRequest.reserved0 offset");
_Static_assert(offsetof(thalyx_resolve_request_t, detail) == 8, "ResolveRequest.detail offset");

/* Origin, cancellation and effect state of admitted work. */
typedef struct {
    uint32_t state; /* Schema field `state`, little-endian `u32`. */
    uint32_t cancel_state; /* Schema field `cancel_state`, little-endian `u32`. */
    uint32_t effect_state; /* Schema field `effect_state`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t invocation_id; /* Schema field `invocation_id`, little-endian `u64`. */
    uint64_t origin_domain_id; /* Schema field `origin_domain_id`, little-endian `u64`. */
    uint64_t origin_scope_id; /* Schema field `origin_scope_id`, little-endian `u64`. */
    uint64_t facet; /* Schema field `facet`, little-endian `u64`. */
    uint64_t grant_id; /* Schema field `grant_id`, little-endian `u64`. */
    uint64_t admitted_ns; /* Schema field `admitted_ns`, little-endian `u64`. */
} thalyx_invocation_info_t;
_Static_assert(sizeof(thalyx_invocation_info_t) == 64, "InvocationInfo size");
_Static_assert(_Alignof(thalyx_invocation_info_t) == 8, "InvocationInfo alignment");
_Static_assert(offsetof(thalyx_invocation_info_t, state) == 0, "InvocationInfo.state offset");
_Static_assert(offsetof(thalyx_invocation_info_t, cancel_state) == 4, "InvocationInfo.cancel_state offset");
_Static_assert(offsetof(thalyx_invocation_info_t, effect_state) == 8, "InvocationInfo.effect_state offset");
_Static_assert(offsetof(thalyx_invocation_info_t, reserved0) == 12, "InvocationInfo.reserved0 offset");
_Static_assert(offsetof(thalyx_invocation_info_t, invocation_id) == 16, "InvocationInfo.invocation_id offset");
_Static_assert(offsetof(thalyx_invocation_info_t, origin_domain_id) == 24, "InvocationInfo.origin_domain_id offset");
_Static_assert(offsetof(thalyx_invocation_info_t, origin_scope_id) == 32, "InvocationInfo.origin_scope_id offset");
_Static_assert(offsetof(thalyx_invocation_info_t, facet) == 40, "InvocationInfo.facet offset");
_Static_assert(offsetof(thalyx_invocation_info_t, grant_id) == 48, "InvocationInfo.grant_id offset");
_Static_assert(offsetof(thalyx_invocation_info_t, admitted_ns) == 56, "InvocationInfo.admitted_ns offset");

/* Bit set raised or waited on. */
typedef struct {
    uint64_t bits; /* Schema field `bits`, little-endian `u64`. */
} thalyx_signal_bits_t;
_Static_assert(sizeof(thalyx_signal_bits_t) == 8, "SignalBits size");
_Static_assert(_Alignof(thalyx_signal_bits_t) == 8, "SignalBits alignment");
_Static_assert(offsetof(thalyx_signal_bits_t, bits) == 0, "SignalBits.bits offset");

/* Coalesced bits with a sequence, so a consumer can re-arm without losing a race. */
typedef struct {
    uint64_t bits; /* Schema field `bits`, little-endian `u64`. */
    uint64_t sequence; /* Schema field `sequence`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
    uint32_t waiters; /* Schema field `waiters`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_signal_info_t;
_Static_assert(sizeof(thalyx_signal_info_t) == 32, "SignalInfo size");
_Static_assert(_Alignof(thalyx_signal_info_t) == 8, "SignalInfo alignment");
_Static_assert(offsetof(thalyx_signal_info_t, bits) == 0, "SignalInfo.bits offset");
_Static_assert(offsetof(thalyx_signal_info_t, sequence) == 8, "SignalInfo.sequence offset");
_Static_assert(offsetof(thalyx_signal_info_t, object_id) == 16, "SignalInfo.object_id offset");
_Static_assert(offsetof(thalyx_signal_info_t, waiters) == 24, "SignalInfo.waiters offset");
_Static_assert(offsetof(thalyx_signal_info_t, reserved0) == 28, "SignalInfo.reserved0 offset");

/* Timer bound to the signal and bits it raises on expiry. */
typedef struct {
    uint64_t signal_handle; /* Schema field `signal_handle`, little-endian `u64`. */
    uint64_t bits; /* Schema field `bits`, little-endian `u64`. */
} thalyx_timer_create_request_t;
_Static_assert(sizeof(thalyx_timer_create_request_t) == 16, "TimerCreateRequest size");
_Static_assert(_Alignof(thalyx_timer_create_request_t) == 8, "TimerCreateRequest alignment");
_Static_assert(offsetof(thalyx_timer_create_request_t, signal_handle) == 0, "TimerCreateRequest.signal_handle offset");
_Static_assert(offsetof(thalyx_timer_create_request_t, bits) == 8, "TimerCreateRequest.bits offset");

/* Monotonic expiry. */
typedef struct {
    uint64_t deadline_ns; /* Schema field `deadline_ns`, little-endian `u64`. */
} thalyx_timer_arm_request_t;
_Static_assert(sizeof(thalyx_timer_arm_request_t) == 8, "TimerArmRequest size");
_Static_assert(_Alignof(thalyx_timer_arm_request_t) == 8, "TimerArmRequest alignment");
_Static_assert(offsetof(thalyx_timer_arm_request_t, deadline_ns) == 0, "TimerArmRequest.deadline_ns offset");

/* Armed deadline and fire count. */
typedef struct {
    uint32_t armed; /* Schema field `armed`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t deadline_ns; /* Schema field `deadline_ns`, little-endian `u64`. */
    uint64_t fired; /* Schema field `fired`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
} thalyx_timer_info_t;
_Static_assert(sizeof(thalyx_timer_info_t) == 32, "TimerInfo size");
_Static_assert(_Alignof(thalyx_timer_info_t) == 8, "TimerInfo alignment");
_Static_assert(offsetof(thalyx_timer_info_t, armed) == 0, "TimerInfo.armed offset");
_Static_assert(offsetof(thalyx_timer_info_t, reserved0) == 4, "TimerInfo.reserved0 offset");
_Static_assert(offsetof(thalyx_timer_info_t, deadline_ns) == 8, "TimerInfo.deadline_ns offset");
_Static_assert(offsetof(thalyx_timer_info_t, fired) == 16, "TimerInfo.fired offset");
_Static_assert(offsetof(thalyx_timer_info_t, object_id) == 24, "TimerInfo.object_id offset");

/* One control receipt. Origin and time are the kernel's; a and b are the caller's untrusted values. */
typedef struct {
    uint32_t schema; /* Schema field `schema`, little-endian `u32`. */
    uint32_t kind; /* Schema field `kind`, little-endian `u32`. */
    uint64_t sequence; /* Schema field `sequence`, little-endian `u64`. */
    uint64_t epoch; /* Schema field `epoch`, little-endian `u64`. */
    uint64_t ns; /* Schema field `ns`, little-endian `u64`. */
    uint64_t origin_domain_id; /* Schema field `origin_domain_id`, little-endian `u64`. */
    uint64_t origin_scope_id; /* Schema field `origin_scope_id`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
    uint64_t grant_id; /* Schema field `grant_id`, little-endian `u64`. */
    uint64_t parent_invocation_id; /* Schema field `parent_invocation_id`, little-endian `u64`. */
    int64_t result; /* Schema field `result`, little-endian `i64`. */
    uint64_t a; /* Schema field `a`, little-endian `u64`. */
    uint64_t b; /* Schema field `b`, little-endian `u64`. */
} thalyx_receipt_record_t;
_Static_assert(sizeof(thalyx_receipt_record_t) == 96, "ReceiptRecord size");
_Static_assert(_Alignof(thalyx_receipt_record_t) == 8, "ReceiptRecord alignment");
_Static_assert(offsetof(thalyx_receipt_record_t, schema) == 0, "ReceiptRecord.schema offset");
_Static_assert(offsetof(thalyx_receipt_record_t, kind) == 4, "ReceiptRecord.kind offset");
_Static_assert(offsetof(thalyx_receipt_record_t, sequence) == 8, "ReceiptRecord.sequence offset");
_Static_assert(offsetof(thalyx_receipt_record_t, epoch) == 16, "ReceiptRecord.epoch offset");
_Static_assert(offsetof(thalyx_receipt_record_t, ns) == 24, "ReceiptRecord.ns offset");
_Static_assert(offsetof(thalyx_receipt_record_t, origin_domain_id) == 32, "ReceiptRecord.origin_domain_id offset");
_Static_assert(offsetof(thalyx_receipt_record_t, origin_scope_id) == 40, "ReceiptRecord.origin_scope_id offset");
_Static_assert(offsetof(thalyx_receipt_record_t, object_id) == 48, "ReceiptRecord.object_id offset");
_Static_assert(offsetof(thalyx_receipt_record_t, grant_id) == 56, "ReceiptRecord.grant_id offset");
_Static_assert(offsetof(thalyx_receipt_record_t, parent_invocation_id) == 64, "ReceiptRecord.parent_invocation_id offset");
_Static_assert(offsetof(thalyx_receipt_record_t, result) == 72, "ReceiptRecord.result offset");
_Static_assert(offsetof(thalyx_receipt_record_t, a) == 80, "ReceiptRecord.a offset");
_Static_assert(offsetof(thalyx_receipt_record_t, b) == 88, "ReceiptRecord.b offset");

/* A bounded batch of receipts and an explicit loss count. */
typedef struct {
    uint32_t count; /* Schema field `count`, little-endian `u32`. */
    uint32_t lost; /* Receipts dropped since the last read. Coverage is never assumed complete. */
    uint64_t next_sequence; /* Schema field `next_sequence`, little-endian `u64`. */
    thalyx_receipt_record_t records[4]; /* Schema field `records`, little-endian `struct:ReceiptRecord[4]`. */
} thalyx_log_read_result_t;
_Static_assert(sizeof(thalyx_log_read_result_t) == 400, "LogReadResult size");
_Static_assert(_Alignof(thalyx_log_read_result_t) == 8, "LogReadResult alignment");
_Static_assert(offsetof(thalyx_log_read_result_t, count) == 0, "LogReadResult.count offset");
_Static_assert(offsetof(thalyx_log_read_result_t, lost) == 4, "LogReadResult.lost offset");
_Static_assert(offsetof(thalyx_log_read_result_t, next_sequence) == 8, "LogReadResult.next_sequence offset");
_Static_assert(offsetof(thalyx_log_read_result_t, records) == 16, "LogReadResult.records offset");

/* Service note. The kernel stamps origin; the payload cannot claim another. */
typedef struct {
    uint32_t kind; /* Schema field `kind`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
    uint64_t a; /* Schema field `a`, little-endian `u64`. */
    uint64_t b; /* Schema field `b`, little-endian `u64`. */
    uint64_t claimed_origin_domain_id; /* Ignored by the kernel. Present so a forged origin can be observed being overwritten. */
} thalyx_log_append_request_t;
_Static_assert(sizeof(thalyx_log_append_request_t) == 32, "LogAppendRequest size");
_Static_assert(_Alignof(thalyx_log_append_request_t) == 8, "LogAppendRequest alignment");
_Static_assert(offsetof(thalyx_log_append_request_t, kind) == 0, "LogAppendRequest.kind offset");
_Static_assert(offsetof(thalyx_log_append_request_t, reserved0) == 4, "LogAppendRequest.reserved0 offset");
_Static_assert(offsetof(thalyx_log_append_request_t, a) == 8, "LogAppendRequest.a offset");
_Static_assert(offsetof(thalyx_log_append_request_t, b) == 16, "LogAppendRequest.b offset");
_Static_assert(offsetof(thalyx_log_append_request_t, claimed_origin_domain_id) == 24, "LogAppendRequest.claimed_origin_domain_id offset");

/* Acknowledge consumption up to a sequence. */
typedef struct {
    uint64_t through_sequence; /* Schema field `through_sequence`, little-endian `u64`. */
} thalyx_log_ack_request_t;
_Static_assert(sizeof(thalyx_log_ack_request_t) == 8, "LogAckRequest size");
_Static_assert(_Alignof(thalyx_log_ack_request_t) == 8, "LogAckRequest alignment");
_Static_assert(offsetof(thalyx_log_ack_request_t, through_sequence) == 0, "LogAckRequest.through_sequence offset");

/* Capacity, reservation and loss of one control log. */
typedef struct {
    uint32_t capacity; /* Schema field `capacity`, little-endian `u32`. */
    uint32_t reserved_cells; /* Reserved, must be zero. */
    uint32_t used; /* Schema field `used`, little-endian `u32`. */
    uint32_t lost; /* Schema field `lost`, little-endian `u32`. */
    uint64_t next_sequence; /* Schema field `next_sequence`, little-endian `u64`. */
    uint64_t oldest_sequence; /* Schema field `oldest_sequence`, little-endian `u64`. */
    uint64_t object_id; /* Schema field `object_id`, little-endian `u64`. */
} thalyx_log_info_t;
_Static_assert(sizeof(thalyx_log_info_t) == 40, "LogInfo size");
_Static_assert(_Alignof(thalyx_log_info_t) == 8, "LogInfo alignment");
_Static_assert(offsetof(thalyx_log_info_t, capacity) == 0, "LogInfo.capacity offset");
_Static_assert(offsetof(thalyx_log_info_t, reserved_cells) == 4, "LogInfo.reserved_cells offset");
_Static_assert(offsetof(thalyx_log_info_t, used) == 8, "LogInfo.used offset");
_Static_assert(offsetof(thalyx_log_info_t, lost) == 12, "LogInfo.lost offset");
_Static_assert(offsetof(thalyx_log_info_t, next_sequence) == 16, "LogInfo.next_sequence offset");
_Static_assert(offsetof(thalyx_log_info_t, oldest_sequence) == 24, "LogInfo.oldest_sequence offset");
_Static_assert(offsetof(thalyx_log_info_t, object_id) == 32, "LogInfo.object_id offset");

/* Bounded fault payload delivered to a supervisor. Carries no kernel address. */
typedef struct {
    uint64_t domain_id; /* Schema field `domain_id`, little-endian `u64`. */
    uint64_t thread_id; /* Schema field `thread_id`, little-endian `u64`. */
    uint64_t generation; /* Schema field `generation`, little-endian `u64`. */
    uint64_t vector; /* Schema field `vector`, little-endian `u64`. */
    uint64_t error_code; /* Schema field `error_code`, little-endian `u64`. */
    uint64_t rip; /* Schema field `rip`, little-endian `u64`. */
    uint64_t rsp; /* Schema field `rsp`, little-endian `u64`. */
    uint64_t address; /* Schema field `address`, little-endian `u64`. */
    uint32_t class; /* Schema field `class`, little-endian `u32`. */
    uint32_t reserved0; /* Reserved, must be zero. */
} thalyx_fault_report_t;
_Static_assert(sizeof(thalyx_fault_report_t) == 72, "FaultReport size");
_Static_assert(_Alignof(thalyx_fault_report_t) == 8, "FaultReport alignment");
_Static_assert(offsetof(thalyx_fault_report_t, domain_id) == 0, "FaultReport.domain_id offset");
_Static_assert(offsetof(thalyx_fault_report_t, thread_id) == 8, "FaultReport.thread_id offset");
_Static_assert(offsetof(thalyx_fault_report_t, generation) == 16, "FaultReport.generation offset");
_Static_assert(offsetof(thalyx_fault_report_t, vector) == 24, "FaultReport.vector offset");
_Static_assert(offsetof(thalyx_fault_report_t, error_code) == 32, "FaultReport.error_code offset");
_Static_assert(offsetof(thalyx_fault_report_t, rip) == 40, "FaultReport.rip offset");
_Static_assert(offsetof(thalyx_fault_report_t, rsp) == 48, "FaultReport.rsp offset");
_Static_assert(offsetof(thalyx_fault_report_t, address) == 56, "FaultReport.address offset");
_Static_assert(offsetof(thalyx_fault_report_t, class) == 64, "FaultReport.class offset");
_Static_assert(offsetof(thalyx_fault_report_t, reserved0) == 68, "FaultReport.reserved0 offset");

#endif /* THALYX_ABI_H */
