[package]
name = "thalyx-user-k3worker"
description = "K3 user domain: k3worker."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "k3worker"
path = "src/main.rs"

[dependencies]
thalyx-abi.workspace = true
thalyx-user-rt.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
