/* Generated by tools/gen_k5_proto.py from abi/schema/k5-proto-v1.json.
 * Do not edit.
 *
 * The K5 protocols, as the C side of the package encodes them. The Rust
 * side has the same layout in user/k5pkg/src/generated.rs, derived from
 * the same schema. The assertions below are what makes that a checked
 * fact rather than an intention: if this compiler lays a structure out
 * differently from what the schema says, the build stops here.
 */
#ifndef THALYX_K5_H
#define THALYX_K5_H

#include <stdint.h>
#include <stddef.h>

/* C++ spells both of these differently; the inference engine is C++ and
 * reads this header. The assertions are the same checks in either. */
#if defined(__cplusplus) && !defined(_Static_assert)
#define _Static_assert static_assert
#endif
#if defined(__cplusplus) && !defined(_Alignof)
#define _Alignof alignof
#endif

#define K5_VERSION_MAJOR 1u
#define K5_VERSION_MINOR 0u

#define K5_CHANNEL_REQUEST_OFFSET 0u
#define K5_CHANNEL_REQUEST_MAX 8192u
#define K5_CHANNEL_ANSWER_OFFSET 8192u
#define K5_CHANNEL_ANSWER_MAX 16384u
#define K5_CHANNEL_PROGRAM_OFFSET 24576u
#define K5_CHANNEL_PROGRAM_MAX 8192u
#define K5_PROMPT_MAX 4096u
#define K5_ANSWER_MAX 4096u
#define K5_CANDIDATE_MAX 16384u
#define K5_CANDIDATE_MAGIC_LOW 893668931u
#define K5_CANDIDATE_ENTRIES 8u
#define K5_CANDIDATE_FLAG_FUNCTION_BODY 1u

/* The work read the published version. Value: the generation. */
#define K5_NOTE_VERSION_SEEN 0x5200ull
/* The work asked for context about a name. Value: uses found. */
#define K5_NOTE_CONTEXT_ANSWERED 0x5201ull
/* A private workspace was opened over a version. Value: the workspace id. */
#define K5_NOTE_WORKSPACE_OPEN 0x5202ull
/* A name was bound in the workspace. Value: bytes of the object. */
#define K5_NOTE_WORKSPACE_WROTE 0x5203ull
/* The workspace was frozen into a candidate. Value: entries. */
#define K5_NOTE_CANDIDATE_FROZEN 0x5204ull
/* A candidate was sealed into a memory object. Value: bytes. */
#define K5_NOTE_CANDIDATE_SEALED 0x5205ull
/* A tool ran over the candidate. Value: its exit code. */
#define K5_NOTE_TOOL_VERDICT 0x5206ull
/* The tool's own accounting, as the launcher measured it. Value: ns. */
#define K5_NOTE_TOOL_COST 0x5207ull
/* A validation record was staged. Value: its result. */
#define K5_NOTE_VALIDATION_STAGED 0x5208ull
/* A publication succeeded. Value: the new generation. */
#define K5_NOTE_PUBLISHED 0x5209ull
/* A publication was refused. Value: the store status. */
#define K5_NOTE_PUBLISH_REFUSED 0x520Aull
/* The work abandoned on purpose. Value: the workspace it discarded. */
#define K5_NOTE_ABANDONED 0x520Bull
/* Evidence was written durably. Value: bytes. */
#define K5_NOTE_EVIDENCE_WRITTEN 0x520Cull
/* Evidence was read back from a published version. Value: bytes. */
#define K5_NOTE_EVIDENCE_READ 0x520Dull
/* The work finished its script. Value: the role. */
#define K5_NOTE_WORK_DONE 0x520Eull
/* The state service refused something. Value: the store status. */
#define K5_NOTE_STORE_REFUSED 0x520Full
/* The published version after the work ended. Value: the generation. */
#define K5_NOTE_FINAL_GENERATION 0x5210ull
/* The work was asked to stop and did. Value: where it was. */
#define K5_NOTE_CANCELLED 0x5211ull
/* The work's own scope accounting. Value: nanoseconds it was charged. */
#define K5_NOTE_WORK_CPU 0x5212ull
/* A step the work did not expect. Value: what it saw. */
#define K5_NOTE_WORK_UNEXPECTED 0x5213ull
/* The digest of the root this work published or tried to. Value: prefix. */
#define K5_NOTE_ROOT_PREFIX 0x5214ull
/* The runtime compiled the program. Value: bytes of source. */
#define K5_NOTE_PROGRAM_COMPILED 0x5300ull
/* The runtime refused to compile the program. Value: where. */
#define K5_NOTE_PROGRAM_REFUSED 0x5301ull
/* The program made a hostcall. Value: the verb. */
#define K5_NOTE_HOSTCALL 0x5302ull
/* The program finished. Value: the finish kind. */
#define K5_NOTE_PROGRAM_FINISH 0x5303ull
/* A ceiling the runtime enforced. Value: which one. */
#define K5_NOTE_PROGRAM_CEILING 0x5304ull
/* An assertion latched. Value: the call it latched on. */
#define K5_NOTE_PROGRAM_LATCHED 0x5305ull
/* The runtime's own memory ceiling, as the engine reports it. Value: bytes. */
#define K5_NOTE_PROGRAM_MEMORY 0x5306ull
/* A hostcall was refused after the latch. Value: the verb. */
#define K5_NOTE_REFUSED_AFTER_LATCH 0x5307ull
/* The tool started over a candidate. Value: bytes it was given. */
#define K5_NOTE_TOOL_START 0x5400ull
/* The tool parsed a file. Value: bytes. */
#define K5_NOTE_TOOL_PARSED 0x5401ull
/* The tool refused a file. Value: where the syntax error was. */
#define K5_NOTE_TOOL_PARSE_FAILED 0x5402ull
/* The tool ran a check. Value: which. */
#define K5_NOTE_TOOL_CHECK 0x5403ull
/* A check did not hold. Value: which. */
#define K5_NOTE_TOOL_CHECK_FAILED 0x5404ull
/* The tool finished. Value: its exit code. */
#define K5_NOTE_TOOL_DONE 0x5405ull
/* The engine loaded its weights. Value: nanoseconds it took. */
#define K5_NOTE_ENGINE_LOADED 0x5500ull
/* Bytes of weights the engine holds. Value: bytes. */
#define K5_NOTE_ENGINE_WEIGHTS 0x5501ull
/* An inference was served. Value: which one since loading. */
#define K5_NOTE_ENGINE_SERVED 0x5502ull
/* The first token of an answer. Value: the token identifier. */
#define K5_NOTE_ENGINE_TOKEN 0x5503ull
/* The margin the first decision won by, in parts per million. */
#define K5_NOTE_ENGINE_MARGIN 0x5504ull
/* A digest over every token of one answer. */
#define K5_NOTE_ENGINE_DIGEST 0x5505ull
/* The engine bound a worker to the invocation. Value: the invocation. */
#define K5_NOTE_ENGINE_BOUND 0x5506ull
/* Nanoseconds one inference took, by the engine's own clock. */
#define K5_NOTE_ENGINE_ELAPSED 0x5507ull
/* The engine refused a request. Value: the status. */
#define K5_NOTE_ENGINE_REFUSED 0x5508ull
/* The prompt the engine actually read, as a digest of its bytes. */
#define K5_NOTE_ENGINE_PROMPT 0x5509ull
/* llama.cpp refused the weights. Value: a digest of the reason it gave. */
#define K5_NOTE_ENGINE_LOAD_FAILED 0x550Aull
/* An inference stopped because the caller's scope was closed. Value: tokens made before it stopped. */
#define K5_NOTE_ENGINE_CANCELLED 0x550Bull
/* A request was read and could not be served. Value: a digest of the reason. */
#define K5_NOTE_ENGINE_FAILED 0x550Cull
/* The context the engine built, in tokens. */
#define K5_NOTE_ENGINE_CONTEXT 0x550Dull
/* A C++ exception was thrown inside a request and caught by the engine. Value: a digest of what() said. */
#define K5_NOTE_ENGINE_EXCEPTION 0x550Eull
/* The highest raw logit of the first decision, computed before sampling, so the sampler's choice can be checked against it. */
#define K5_NOTE_ENGINE_ARGMAX 0x550Full
/* Lines llama.cpp and ggml logged while loading. They go nowhere; the count says how many. */
#define K5_NOTE_ENGINE_LOG_LINES 0x5510ull
/* Bytes of /bulk the engine was given, before it loaded anything. */
#define K5_NOTE_ENGINE_MODEL_BYTES 0x5511ull
/* FNV-1a over those bytes, computed by the engine, so the weights it loaded can be named from the host's copy. */
#define K5_NOTE_ENGINE_MODEL_DIGEST 0x5512ull
/* A tool domain was built. Value: the tool identity. */
#define K5_NOTE_LAUNCH_BUILT 0x5600ull
/* A tool domain was retired. Value: pages its scope had held. */
#define K5_NOTE_LAUNCH_RETIRED 0x5601ull
/* A launch was refused. Value: the launcher status. */
#define K5_NOTE_LAUNCH_REFUSED 0x5602ull
/* The candidate a launch was given was not sealed. Value: its state. */
#define K5_NOTE_LAUNCH_NOT_SEALED 0x5603ull
/* Bytes of the candidate the tool read, with the checks it ran and failed. */
#define K5_NOTE_TOOL_READ 0x5215ull
/* The digest the tool computed over the bytes it actually read. */
#define K5_NOTE_TOOL_SUM 0x5216ull

/* One Thalyx request: a verb and its arguments. */
#define K5_HOST_OP_REQUEST 1u
/* One validation, through the tool the whole verb uses. */
#define K5_HOST_OP_VALIDATE 2u
/* What the workspace really shows changed. */
#define K5_HOST_OP_CHANGED 3u
/* One inference from the resident engine. */
#define K5_HOST_OP_MODEL 4u
/* A line the program printed. */
#define K5_HOST_OP_LOG 5u
/* An assertion that did not hold. The latch is on the other side of this call. */
#define K5_HOST_OP_ASSERT_FAILED 6u
/* The program has finished, and this is how. */
#define K5_HOST_OP_FINISH 7u
/* The program stopped and asked for a decision it would not make. */
#define K5_HOST_OP_NEEDS_MODEL 8u

/* It ran to the end and returned a value. */
#define K5_FINISH_RETURNED 1u
/* It asked for a decision a machine should not make. Not a success. */
#define K5_FINISH_NEEDS_MODEL 2u
/* An assertion said no. Everything after it did not run. */
#define K5_FINISH_ASSERTION 3u
/* It threw something it did not catch. */
#define K5_FINISH_THREW 4u
/* A ceiling was reached. */
#define K5_FINISH_EXHAUSTED 5u
/* It could not be read, or the engine could not be built. */
#define K5_FINISH_REFUSED 6u

#define K5_VERDICT_PASSED 1u
#define K5_VERDICT_FAILED 2u
/* The check could not run. Never a pass. */
#define K5_VERDICT_NOT_PROVEN 3u

/* Run a tool over the sealed candidate lent with this message and report what it did. */
#define K5_LAUNCH_OP_RUN_TOOL 1u
/* What this launcher is and which tools it has images for. */
#define K5_LAUNCH_OP_QUERY 2u
/* Build and activate the language runtime over the shared channel, and answer at once: the caller has to be free to serve the calls it will make. */
#define K5_LAUNCH_OP_START_RUNTIME 3u
/* Stop it and retire its scope, whether or not it finished. */
#define K5_LAUNCH_OP_STOP_RUNTIME 4u

#define K5_LAUNCH_STATUS_OK 0u
#define K5_LAUNCH_STATUS_NO_SUCH_TOOL 1u
/* The candidate was not a sealed object, or was not lent at all. */
#define K5_LAUNCH_STATUS_NOT_SEALED 2u
#define K5_LAUNCH_STATUS_UNAVAILABLE 3u
#define K5_LAUNCH_STATUS_TIMED_OUT 4u
#define K5_LAUNCH_STATUS_FAULTED 5u

#define K5_ENGINE_OP_INFER 1u
#define K5_ENGINE_OP_QUERY 2u

#define K5_ENGINE_STATUS_OK 0u
#define K5_ENGINE_STATUS_INVALID 1u
/* The prompt did not fit the context, and was not silently cut. */
#define K5_ENGINE_STATUS_TOO_LONG 2u
#define K5_ENGINE_STATUS_NOT_READY 3u
#define K5_ENGINE_STATUS_NO_BUFFER 4u
/* The work that asked was closed while this was running. */
#define K5_ENGINE_STATUS_CANCELLED 5u
/* The request was read and could not be served; the answer bytes are the reason, as Thalyx's engine reports one. */
#define K5_ENGINE_STATUS_FAILED 6u

/* The inline half of a host call; the bytes are in the shared region. */
typedef struct {
    uint32_t op; /* HostOp. */
    uint32_t request_len; /* Bytes the runtime wrote at the request offset. */
    uint64_t cookie; /* The runtime's own call counter, echoed back. */
    uint64_t arg0;
    uint64_t arg1;
} k5_host_request;
_Static_assert(sizeof(k5_host_request) == 32, "HostRequest size");
_Static_assert(_Alignof(k5_host_request) == 8, "HostRequest alignment");
_Static_assert(offsetof(k5_host_request, op) == 0, "HostRequest.op offset");
_Static_assert(offsetof(k5_host_request, request_len) == 4, "HostRequest.request_len offset");
_Static_assert(offsetof(k5_host_request, cookie) == 8, "HostRequest.cookie offset");
_Static_assert(offsetof(k5_host_request, arg0) == 16, "HostRequest.arg0 offset");
_Static_assert(offsetof(k5_host_request, arg1) == 24, "HostRequest.arg1 offset");

/* The inline half of a host call's answer. */
typedef struct {
    uint32_t status; /* Zero when the call was served. */
    uint32_t answer_len; /* Bytes the work wrote at the answer offset. */
    uint32_t stopped; /* Set once the machine has latched and refuses everything after. */
    uint32_t reserved0;
    uint64_t value;
} k5_host_reply;
_Static_assert(sizeof(k5_host_reply) == 24, "HostReply size");
_Static_assert(_Alignof(k5_host_reply) == 8, "HostReply alignment");
_Static_assert(offsetof(k5_host_reply, status) == 0, "HostReply.status offset");
_Static_assert(offsetof(k5_host_reply, answer_len) == 4, "HostReply.answer_len offset");
_Static_assert(offsetof(k5_host_reply, stopped) == 8, "HostReply.stopped offset");
_Static_assert(offsetof(k5_host_reply, reserved0) == 12, "HostReply.reserved0 offset");
_Static_assert(offsetof(k5_host_reply, value) == 16, "HostReply.value offset");

/* What one run of the language runtime produced. */
typedef struct {
    uint32_t requests;
    uint32_t validations;
    uint32_t observations;
    uint32_t assertions;
    uint32_t inferences;
    uint32_t finish; /* Finish. */
    uint64_t answer_bytes; /* Bytes of answers the machine handed the program. */
    uint64_t returned_bytes; /* Bytes the program returned. The compression's other side. */
    uint64_t wall_ns;
} k5_run_metrics;
_Static_assert(sizeof(k5_run_metrics) == 48, "RunMetrics size");
_Static_assert(_Alignof(k5_run_metrics) == 8, "RunMetrics alignment");
_Static_assert(offsetof(k5_run_metrics, requests) == 0, "RunMetrics.requests offset");
_Static_assert(offsetof(k5_run_metrics, validations) == 4, "RunMetrics.validations offset");
_Static_assert(offsetof(k5_run_metrics, observations) == 8, "RunMetrics.observations offset");
_Static_assert(offsetof(k5_run_metrics, assertions) == 12, "RunMetrics.assertions offset");
_Static_assert(offsetof(k5_run_metrics, inferences) == 16, "RunMetrics.inferences offset");
_Static_assert(offsetof(k5_run_metrics, finish) == 20, "RunMetrics.finish offset");
_Static_assert(offsetof(k5_run_metrics, answer_bytes) == 24, "RunMetrics.answer_bytes offset");
_Static_assert(offsetof(k5_run_metrics, returned_bytes) == 32, "RunMetrics.returned_bytes offset");
_Static_assert(offsetof(k5_run_metrics, wall_ns) == 40, "RunMetrics.wall_ns offset");

/* Ask the launcher to run a tool over the candidate lent with this message. */
typedef struct {
    uint32_t op; /* LaunchOp. */
    uint32_t tool_id; /* Which tool. A launcher refuses one it has no image for. */
    uint64_t candidate_len;
    uint8_t candidate_digest[32]; /* So a verdict can be tied to the bytes it was about. */
    uint64_t seed;
    uint64_t deadline_ns;
} k5_launch_request;
_Static_assert(sizeof(k5_launch_request) == 64, "LaunchRequest size");
_Static_assert(_Alignof(k5_launch_request) == 8, "LaunchRequest alignment");
_Static_assert(offsetof(k5_launch_request, op) == 0, "LaunchRequest.op offset");
_Static_assert(offsetof(k5_launch_request, tool_id) == 4, "LaunchRequest.tool_id offset");
_Static_assert(offsetof(k5_launch_request, candidate_len) == 8, "LaunchRequest.candidate_len offset");
_Static_assert(offsetof(k5_launch_request, candidate_digest) == 16, "LaunchRequest.candidate_digest offset");
_Static_assert(offsetof(k5_launch_request, seed) == 48, "LaunchRequest.seed offset");
_Static_assert(offsetof(k5_launch_request, deadline_ns) == 56, "LaunchRequest.deadline_ns offset");

/* What the launcher saw the tool do. */
typedef struct {
    uint32_t status; /* LaunchStatus. */
    uint32_t exit_code; /* Zero is a pass and only zero is. */
    uint32_t checks_run;
    uint32_t checks_failed;
    uint64_t cpu_ns; /* Nanoseconds the tool's own scope was charged. */
    uint64_t pages; /* Pages its scope held at its most. */
    uint64_t tool_id; /* The tool identity that actually ran. */
    uint8_t tool_config_digest[32];
    uint64_t bytes_read; /* Bytes of the candidate the tool actually read, as the tool reported them. */
    uint64_t candidate_sum; /* A digest over those bytes, so a verdict names what it was about. */
} k5_launch_reply;
_Static_assert(sizeof(k5_launch_reply) == 88, "LaunchReply size");
_Static_assert(_Alignof(k5_launch_reply) == 8, "LaunchReply alignment");
_Static_assert(offsetof(k5_launch_reply, status) == 0, "LaunchReply.status offset");
_Static_assert(offsetof(k5_launch_reply, exit_code) == 4, "LaunchReply.exit_code offset");
_Static_assert(offsetof(k5_launch_reply, checks_run) == 8, "LaunchReply.checks_run offset");
_Static_assert(offsetof(k5_launch_reply, checks_failed) == 12, "LaunchReply.checks_failed offset");
_Static_assert(offsetof(k5_launch_reply, cpu_ns) == 16, "LaunchReply.cpu_ns offset");
_Static_assert(offsetof(k5_launch_reply, pages) == 24, "LaunchReply.pages offset");
_Static_assert(offsetof(k5_launch_reply, tool_id) == 32, "LaunchReply.tool_id offset");
_Static_assert(offsetof(k5_launch_reply, tool_config_digest) == 40, "LaunchReply.tool_config_digest offset");
_Static_assert(offsetof(k5_launch_reply, bytes_read) == 72, "LaunchReply.bytes_read offset");
_Static_assert(offsetof(k5_launch_reply, candidate_sum) == 80, "LaunchReply.candidate_sum offset");

/* The header of a sealed candidate: what a tool is given, and nothing else. */
typedef struct {
    uint32_t magic; /* CANDIDATE_MAGIC_LOW. */
    uint32_t version;
    uint32_t count; /* Names bound in this candidate. */
    uint32_t reserved0;
    uint64_t seed; /* The run's seed, so a tool cannot precompute a verdict. */
    uint64_t total_bytes;
    uint8_t root_digest[32]; /* The candidate root this was assembled from. */
} k5_candidate_header;
_Static_assert(sizeof(k5_candidate_header) == 64, "CandidateHeader size");
_Static_assert(_Alignof(k5_candidate_header) == 8, "CandidateHeader alignment");
_Static_assert(offsetof(k5_candidate_header, magic) == 0, "CandidateHeader.magic offset");
_Static_assert(offsetof(k5_candidate_header, version) == 4, "CandidateHeader.version offset");
_Static_assert(offsetof(k5_candidate_header, count) == 8, "CandidateHeader.count offset");
_Static_assert(offsetof(k5_candidate_header, reserved0) == 12, "CandidateHeader.reserved0 offset");
_Static_assert(offsetof(k5_candidate_header, seed) == 16, "CandidateHeader.seed offset");
_Static_assert(offsetof(k5_candidate_header, total_bytes) == 24, "CandidateHeader.total_bytes offset");
_Static_assert(offsetof(k5_candidate_header, root_digest) == 32, "CandidateHeader.root_digest offset");

/* One name of a sealed candidate. */
typedef struct {
    uint64_t offset; /* Where its bytes start, from the beginning of the object. */
    uint64_t length;
    uint32_t name_len;
    uint32_t flags; /* Bit 0: the content is a function body, not a script, and a tool has to compile it the way the runtime executes it. */
    uint8_t name[32];
} k5_candidate_entry;
_Static_assert(sizeof(k5_candidate_entry) == 56, "CandidateEntry size");
_Static_assert(_Alignof(k5_candidate_entry) == 8, "CandidateEntry alignment");
_Static_assert(offsetof(k5_candidate_entry, offset) == 0, "CandidateEntry.offset offset");
_Static_assert(offsetof(k5_candidate_entry, length) == 8, "CandidateEntry.length offset");
_Static_assert(offsetof(k5_candidate_entry, name_len) == 16, "CandidateEntry.name_len offset");
_Static_assert(offsetof(k5_candidate_entry, flags) == 20, "CandidateEntry.flags offset");
_Static_assert(offsetof(k5_candidate_entry, name) == 24, "CandidateEntry.name offset");

/* What a validation tool says about a candidate, in the region it shares. */
typedef struct {
    uint32_t checks_run;
    uint32_t checks_failed;
    uint32_t parsed; /* Files the tool compiled. */
    uint32_t parse_failed;
    uint64_t bytes_read; /* Bytes of the candidate it actually read. */
    uint64_t candidate_sum; /* A digest over those bytes, so a verdict names what it was about. */
    uint8_t first_failure[64]; /* The first check that did not hold, as the tool worded it. */
} k5_tool_report;
_Static_assert(sizeof(k5_tool_report) == 96, "ToolReport size");
_Static_assert(_Alignof(k5_tool_report) == 8, "ToolReport alignment");
_Static_assert(offsetof(k5_tool_report, checks_run) == 0, "ToolReport.checks_run offset");
_Static_assert(offsetof(k5_tool_report, checks_failed) == 4, "ToolReport.checks_failed offset");
_Static_assert(offsetof(k5_tool_report, parsed) == 8, "ToolReport.parsed offset");
_Static_assert(offsetof(k5_tool_report, parse_failed) == 12, "ToolReport.parse_failed offset");
_Static_assert(offsetof(k5_tool_report, bytes_read) == 16, "ToolReport.bytes_read offset");
_Static_assert(offsetof(k5_tool_report, candidate_sum) == 24, "ToolReport.candidate_sum offset");
_Static_assert(offsetof(k5_tool_report, first_failure) == 32, "ToolReport.first_failure offset");

/* Ask the engine for one inference. */
typedef struct {
    uint32_t op; /* EngineOp. */
    uint32_t predict; /* Tokens to generate at most. */
    uint32_t prompt_len; /* Bytes of prompt in the lent buffer. */
    uint32_t grammar_len; /* Bytes of GBNF grammar right after the prompt in the lent buffer; zero for none. Thalyx's engine takes one per request. */
    uint64_t seed;
} k5_engine_request;
_Static_assert(sizeof(k5_engine_request) == 24, "EngineRequest size");
_Static_assert(_Alignof(k5_engine_request) == 8, "EngineRequest alignment");
_Static_assert(offsetof(k5_engine_request, op) == 0, "EngineRequest.op offset");
_Static_assert(offsetof(k5_engine_request, predict) == 4, "EngineRequest.predict offset");
_Static_assert(offsetof(k5_engine_request, prompt_len) == 8, "EngineRequest.prompt_len offset");
_Static_assert(offsetof(k5_engine_request, grammar_len) == 12, "EngineRequest.grammar_len offset");
_Static_assert(offsetof(k5_engine_request, seed) == 16, "EngineRequest.seed offset");

/* What the engine did. */
typedef struct {
    uint32_t status; /* EngineStatus. */
    uint32_t prompt_tokens;
    uint32_t generated;
    uint32_t answer_len;
    uint64_t elapsed_ns; /* How long this inference took. */
    uint64_t load_ns; /* How long the weights took to load. Every answer carries it, so residency is a number a caller sees. */
    uint64_t served; /* Inferences served since loading. */
    uint32_t first_token; /* The first token chosen, so two engines are comparable on a decision. */
    uint32_t first_margin_ppm; /* The margin that decision won by. A comparison of decisions is only meaningful when the decision was not a tie. */
    uint64_t token_digest; /* A digest over every token generated. */
    uint64_t weight_bytes; /* Bytes of weights held resident. */
} k5_engine_reply;
_Static_assert(sizeof(k5_engine_reply) == 64, "EngineReply size");
_Static_assert(_Alignof(k5_engine_reply) == 8, "EngineReply alignment");
_Static_assert(offsetof(k5_engine_reply, status) == 0, "EngineReply.status offset");
_Static_assert(offsetof(k5_engine_reply, prompt_tokens) == 4, "EngineReply.prompt_tokens offset");
_Static_assert(offsetof(k5_engine_reply, generated) == 8, "EngineReply.generated offset");
_Static_assert(offsetof(k5_engine_reply, answer_len) == 12, "EngineReply.answer_len offset");
_Static_assert(offsetof(k5_engine_reply, elapsed_ns) == 16, "EngineReply.elapsed_ns offset");
_Static_assert(offsetof(k5_engine_reply, load_ns) == 24, "EngineReply.load_ns offset");
_Static_assert(offsetof(k5_engine_reply, served) == 32, "EngineReply.served offset");
_Static_assert(offsetof(k5_engine_reply, first_token) == 40, "EngineReply.first_token offset");
_Static_assert(offsetof(k5_engine_reply, first_margin_ppm) == 44, "EngineReply.first_margin_ppm offset");
_Static_assert(offsetof(k5_engine_reply, token_digest) == 48, "EngineReply.token_digest offset");
_Static_assert(offsetof(k5_engine_reply, weight_bytes) == 56, "EngineReply.weight_bytes offset");

#endif /* THALYX_K5_H */
