/* Generated by tools/gen_k6_bench.py from abi/schema/k6-bench-v1.json.
 * Do not edit.
 *
 * The K6 paired benchmarks, as both C builds see them: the benchmark
 * compiled for the native target and the same benchmark compiled for
 * Linux include this one header, so the two sides of a comparison cannot
 * disagree about what a benchmark is called or how a plan is laid out.
 * The native supervisor has the same layout in user/k6super/src/
 * generated.rs, from the same schema.
 */
#ifndef THALYX_K6_H
#define THALYX_K6_H

#include <stdint.h>
#include <stddef.h>

#define K6_VERSION_MAJOR 1u
#define K6_VERSION_MINOR 0u

#define K6_PLAN_MAGIC 3544385891052868683ull
#define K6_PLAN_VERSION 1ull
#define K6_PLAN_ENTRIES 32ull
#define K6_SAMPLES_MAX 16384ull
#define K6_CAL_WINDOW_NS 200000000ull
#define K6_SLICE_NS 10000000ull
#define K6_LOST_SAMPLE 4294967295ull
#define K6_ENGINE_PROMPTS 5ull
#define K6_ROLE_CLIENT 16ull
#define K6_ROLE_SERVER 17ull
#define K6_ROLE_SPIN 18ull
#define K6_ROLE_ASKER 19ull
#define K6_ROLE_IDLE 20ull
#define K6_SLOT_PAIR0 2ull
#define K6_SLOT_PAIR1 9ull
#define K6_SLOT_PAIR2 10ull
#define K6_SLOT_PAIR3 11ull
#define K6_SLOT_ENGINE 12ull
#define K6_SLOT_HANDOFF 13ull
#define K6_HANDOFF_REQUEST_BIT 1ull
#define K6_HANDOFF_DONE_BIT 2ull
#define K6_ASKER_ASKING_BIT 4ull
#define K6_IDLE_READY_BIT 8ull
#define K6_SHARED_PLAN_OFFSET 0ull
#define K6_SHARED_HANDOFF_OFFSET 2048ull
#define K6_SHARED_BYTES 4096ull
#define K6_WAKE_BIT 1099511627776ull
#define K6_MAP_VADDR 1879048192ull
#define K6_SEAL_VADDR 1946157056ull
#define K6_PROMPT_VADDR 2013265920ull

/* The plan this run follows. Value: its seed. */
#define K6_NOTE_PLAN 0x6000ull
/* Time-stamp-counter frequency calibrated against this backend's monotonic clock over CAL_WINDOW_NS. */
#define K6_NOTE_TSC_HZ 0x6001ull
/* A benchmark starts. Value: id | param << 16 | samples << 32. */
#define K6_NOTE_BEGIN 0x6002ull
/* Two samples, the earlier in the low 32 bits. LOST_SAMPLE marks a sample that was not taken. */
#define K6_NOTE_SAMPLE 0x6003ull
/* A benchmark ended. Value: id | errors << 32. */
#define K6_NOTE_END 0x6004ull
/* An operation under measurement failed. Value: id | (status & 0xffffffff) << 32. */
#define K6_NOTE_ERROR 0x6005ull
/* An engine answer was not the reference completion. Value: prompt index. */
#define K6_NOTE_MISMATCH 0x6006ull
/* A correctness check the benchmark makes on its own work passed. Value: id | count << 32. */
#define K6_NOTE_CHECK 0x6007ull
/* A benchmark-specific quantity. Value: id | quantity index << 16 | value << 32. */
#define K6_NOTE_AUX 0x6008ull
/* The plan ran to its end. Value: benchmarks run. */
#define K6_NOTE_DONE 0x60FFull
/* FNV-1a of the first answer an engine gave to one prompt. Value: the digest; the prompt is the AUX note before it. */
#define K6_NOTE_DIGEST 0x6009ull

/* Benchmark identities. What each side does for one is in the schema. */
#define K6_BENCH_ENTRY_VERSION 1u
#define K6_BENCH_ENTRY_CLOCK 2u
#define K6_BENCH_IPC_CALL 3u
#define K6_BENCH_IPC_CAPS 4u
#define K6_BENCH_MEM_MAP 5u
#define K6_BENCH_MEM_SEAL 6u
#define K6_BENCH_CAP_DERIVE 7u
#define K6_BENCH_SCHED_WAKE 8u
#define K6_BENCH_QUOTA_SHARE 9u
#define K6_BENCH_SCALE_IPC 10u
#define K6_BENCH_SCALE_COMPUTE 11u
#define K6_BENCH_CLOSURE_UNIT 12u
#define K6_BENCH_ENGINE_LOAD 13u
#define K6_BENCH_ENGINE_INFER 14u
#define K6_BENCH_ENGINE_CANCEL 15u
#define K6_BENCH_IPC_LINEAGE 16u
#define K6_BENCH_AUDIT_DRAIN 17u

/* The engine's questions, from the K5 fixture in abi/schema/k5-proto-v1.json,
 * case by case and prompt by prompt. engine.infer's parameter indexes them. */
#define K6_ENGINE_CONTEXT_TOKENS 512u
#define K6_ENGINE_COMPUTE_THREADS 1u
__attribute__((unused))
static const char *const k6_engine_prompt[5] = {"hola hola", "hola", "adios", "adios adios", "hola hola hola hola hola hola"};
__attribute__((unused))
static const uint32_t k6_engine_predict[5] = {12u, 12u, 12u, 12u, 400u};
/* A grammar under which no answer ends, for the request that is cancelled. */
#define K6_CANCEL_GRAMMAR "root ::= \"hola \" root"

/* What one boot runs, in order. The same bytes reach both backends: a module of the native package, a file of the Linux one. */
typedef struct {
    uint64_t magic; /* PLAN_MAGIC. */
    uint32_t version; /* PLAN_VERSION. */
    uint32_t count; /* Entries in use. */
    uint64_t seed; /* Seed the host drew for this boot; it decided the order of the entries. */
    uint32_t round; /* Which round of the paired design this boot is. */
    uint32_t flags; /* Reserved, zero. */
    uint64_t model_bytes; /* Bytes of the engine model the package carries; a sealed module is whole pages, so the length is said here and checked against the object. Zero when no entry asks the engine. Linux reads the file and ignores it. */
    uint32_t bench[32]; /* Benchmark ids, in the order they run. */
    uint32_t param[32]; /* The parameter of each entry. */
    uint32_t samples[32]; /* Samples each entry takes. */
    uint32_t warmup[32]; /* Unrecorded iterations before them. */
} k6_plan;
_Static_assert(sizeof(k6_plan) == 552, "Plan size");
_Static_assert(_Alignof(k6_plan) == 8, "Plan alignment");
_Static_assert(offsetof(k6_plan, magic) == 0, "Plan.magic offset");
_Static_assert(offsetof(k6_plan, version) == 8, "Plan.version offset");
_Static_assert(offsetof(k6_plan, count) == 12, "Plan.count offset");
_Static_assert(offsetof(k6_plan, seed) == 16, "Plan.seed offset");
_Static_assert(offsetof(k6_plan, round) == 24, "Plan.round offset");
_Static_assert(offsetof(k6_plan, flags) == 28, "Plan.flags offset");
_Static_assert(offsetof(k6_plan, model_bytes) == 32, "Plan.model_bytes offset");
_Static_assert(offsetof(k6_plan, bench) == 40, "Plan.bench offset");
_Static_assert(offsetof(k6_plan, param) == 168, "Plan.param offset");
_Static_assert(offsetof(k6_plan, samples) == 296, "Plan.samples offset");
_Static_assert(offsetof(k6_plan, warmup) == 424, "Plan.warmup offset");

/* An entry the native program hands to its supervisor, which runs it and answers with HANDOFF_DONE_BIT. At SHARED_HANDOFF_OFFSET. */
typedef struct {
    uint32_t bench; /* Benchmark id. */
    uint32_t param; /* Its parameter. */
    uint32_t samples; /* Samples to take. */
    uint32_t status; /* Written by the supervisor: zero, or the negated status it stopped with. */
} k6_handoff;
_Static_assert(sizeof(k6_handoff) == 16, "Handoff size");
_Static_assert(_Alignof(k6_handoff) == 4, "Handoff alignment");
_Static_assert(offsetof(k6_handoff, bench) == 0, "Handoff.bench offset");
_Static_assert(offsetof(k6_handoff, param) == 4, "Handoff.param offset");
_Static_assert(offsetof(k6_handoff, samples) == 8, "Handoff.samples offset");
_Static_assert(offsetof(k6_handoff, status) == 12, "Handoff.status offset");

#endif /* THALYX_K6_H */
