[package]
name = "thalyx-user-k4disk"
description = "K4 user domain: k4disk, a block driver that can be made to fail."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "k4disk"
path = "src/main.rs"

[dependencies]
thalyx-abi.workspace = true
thalyx-user-rt.workspace = true
thalyx-user-k4fmt.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
