//! Layout fixtures, generated from `abi/schema/v0.json`.
//!
//! The byte vectors below were produced by the generator, not by this crate's
//! own encoder. Decoding them with the generated structures therefore checks
//! the Rust layout against an independent implementation of the same schema,
//! which is what a fixture is for. [`verify`] runs inside the kernel at boot
//! so the check happens on the real path, not only in a host test.

// Generated by tools/gen_abi.py. Do not edit.

use crate::generated::*;

/// One fixture: the encoded bytes and the value they must decode to.
pub struct Fixture {
    /// Structure name, as written in the schema.
    pub name: &'static str,
    /// Bytes the generator produced.
    pub bytes: &'static [u8],
    /// Size the schema fixes for the structure.
    pub size: usize,
}

const DESCRIPTOR_HEADER_BYTES: [u8; 32] = [
    0x11, 0x0E, 0x1A, 0x15, 0x23, 0x1C, 0x18, 0x14, 0x2C, 0x23, 0x1E, 0x19, 0x35, 0x2A, 0x24, 0x1E,
    0x3E, 0x31, 0x2A, 0x23, 0x1C, 0x15, 0x0E, 0x07, 0x47, 0x38, 0x30, 0x28, 0x20, 0x18, 0x10, 0x08,
];
const LIMITS_BYTES: [u8; 88] = [
    0xAA, 0x85, 0xB3, 0x8C, 0xBC, 0x93, 0x7E, 0x69, 0xC5, 0x9A, 0x84, 0x6E, 0xCE, 0xA1, 0x8A, 0x73,
    0xD7, 0xA8, 0x90, 0x78, 0xE0, 0xAF, 0x96, 0x7D, 0xE9, 0xB6, 0x9C, 0x82, 0xF2, 0xBD, 0xA2, 0x87,
    0xFB, 0xC4, 0xA8, 0x8C, 0x04, 0xCC, 0xAE, 0x91, 0x0D, 0xD3, 0xB4, 0x96, 0x16, 0xDA, 0xBA, 0x9B,
    0x1F, 0xE1, 0xC0, 0xA0, 0x80, 0x60, 0x40, 0x20, 0x28, 0xE8, 0xC6, 0xA5, 0x84, 0x63, 0x42, 0x21,
    0x31, 0xEF, 0xCC, 0xAA, 0x88, 0x66, 0x44, 0x22, 0x3A, 0xF6, 0xD2, 0xAF, 0x8C, 0x69, 0x46, 0x23,
    0x43, 0xFD, 0xD8, 0xB4, 0x4C, 0x04, 0xDF, 0xB9,
];
const CAP_INFO_BYTES: [u8; 64] = [
    0x43, 0xFD, 0xD8, 0xB4, 0x4C, 0x04, 0xDF, 0xB9, 0x55, 0x0B, 0xE5, 0xBE, 0x5E, 0x12, 0xEB, 0xC3,
    0x67, 0x19, 0xF1, 0xC8, 0xA0, 0x78, 0x50, 0x28, 0x70, 0x20, 0xF7, 0xCD, 0xA4, 0x7B, 0x52, 0x29,
    0x79, 0x27, 0xFD, 0xD2, 0xA8, 0x7E, 0x54, 0x2A, 0x82, 0x2E, 0x03, 0xD8, 0xAC, 0x81, 0x56, 0x2B,
    0x8B, 0x35, 0x09, 0xDD, 0xB0, 0x84, 0x58, 0x2C, 0x94, 0x3C, 0x0F, 0xE2, 0xB4, 0x87, 0x5A, 0x2D,
];
const DERIVE_REQUEST_BYTES: [u8; 24] = [
    0xDC, 0x74, 0x3F, 0x0A, 0xE5, 0x7B, 0x45, 0x0F, 0xEE, 0x82, 0x4B, 0x14, 0xDD, 0xA5, 0x6E, 0x37,
    0xF7, 0x89, 0x51, 0x19, 0xE1, 0xA8, 0x70, 0x38,
];
const SCOPE_INFO_BYTES: [u8; 144] = [
    0x7E, 0xF3, 0xAB, 0x64, 0x1D, 0xD6, 0x8E, 0x47, 0x87, 0xFA, 0xB1, 0x69, 0x21, 0xD9, 0x90, 0x48,
    0x90, 0x01, 0xB8, 0x6E, 0x25, 0xDC, 0x92, 0x49, 0x99, 0x08, 0xBE, 0x73, 0x29, 0xDF, 0x94, 0x4A,
    0xA2, 0x0F, 0xC4, 0x78, 0x2D, 0xE2, 0x96, 0x4B, 0xAB, 0x16, 0xCA, 0x7D, 0xB4, 0x1D, 0xD0, 0x82,
    0xA2, 0x0F, 0xC4, 0x78, 0xAB, 0x16, 0xCA, 0x7D, 0xB4, 0x1D, 0xD0, 0x82, 0xBD, 0x24, 0xD6, 0x87,
    0xC6, 0x2B, 0xDC, 0x8C, 0x3D, 0xEE, 0x9E, 0x4F, 0xCF, 0x32, 0xE2, 0x91, 0x41, 0xF1, 0xA0, 0x50,
    0xD8, 0x39, 0xE8, 0x96, 0x45, 0xF4, 0xA2, 0x51, 0xE1, 0x40, 0xEE, 0x9B, 0x49, 0xF7, 0xA4, 0x52,
    0xEA, 0x47, 0xF4, 0xA0, 0x4D, 0xFA, 0xA6, 0x53, 0xF3, 0x4E, 0xFA, 0xA5, 0x51, 0xFD, 0xA8, 0x54,
    0xFC, 0x55, 0x00, 0xAB, 0x55, 0x00, 0xAB, 0x55, 0x05, 0x5D, 0x06, 0xB0, 0x59, 0x03, 0xAD, 0x56,
    0x0E, 0x64, 0x0C, 0xB5, 0x5D, 0x06, 0xAF, 0x57, 0x17, 0x6B, 0x12, 0xBA, 0x61, 0x09, 0xB1, 0x58,
];
const DRAIN_REPORT_BYTES: [u8; 64] = [
    0x0E, 0x64, 0x0C, 0xB5, 0x17, 0x6B, 0x12, 0xBA, 0x20, 0x72, 0x18, 0xBF, 0x29, 0x79, 0x1E, 0xC4,
    0x32, 0x80, 0x24, 0xC9, 0x3B, 0x87, 0x2A, 0xCE, 0x44, 0x8E, 0x30, 0xD3, 0x4D, 0x95, 0x36, 0xD8,
    0x56, 0x9C, 0x3C, 0xDD, 0x7D, 0x1E, 0xBF, 0x5F, 0x5F, 0xA3, 0x42, 0xE2, 0x81, 0x21, 0xC1, 0x60,
    0x68, 0xAA, 0x48, 0xE7, 0x85, 0x24, 0xC3, 0x61, 0x71, 0xB1, 0x4E, 0xEC, 0x89, 0x27, 0xC5, 0x62,
];
const MAP_REQUEST_BYTES: [u8; 32] = [
    0xA7, 0xDB, 0x72, 0x0A, 0xA2, 0x39, 0xD1, 0x68, 0xB0, 0xE2, 0x78, 0x0F, 0xA6, 0x3C, 0xD3, 0x69,
    0xB9, 0xE9, 0x7E, 0x14, 0xC2, 0xF0, 0x84, 0x19, 0xCB, 0xF7, 0x8A, 0x1E, 0xD4, 0xFE, 0x90, 0x23,
];
const MEMORY_INFO_BYTES: [u8; 56] = [
    0x40, 0x53, 0xD9, 0x5F, 0x49, 0x5A, 0xDF, 0x64, 0x52, 0x61, 0xE5, 0x69, 0x5B, 0x68, 0xEB, 0x6E,
    0x64, 0x6F, 0xF1, 0x73, 0xF6, 0x78, 0xFB, 0x7D, 0x6D, 0x76, 0xF7, 0x78, 0xFA, 0x7B, 0xFD, 0x7E,
    0x76, 0x7D, 0xFD, 0x7D, 0xFE, 0x7E, 0xFF, 0x7F, 0x7F, 0x88, 0x91, 0x9A, 0xA3, 0xAC, 0xB5, 0xBE,
    0xC7, 0xD0, 0xD9, 0xE2, 0xEB, 0xF4, 0xFD, 0x06,
];
const SEND_REQUEST_BYTES: [u8; 312] = [
    0xD9, 0xCA, 0x3F, 0xB5, 0xE2, 0xD1, 0x45, 0xBA, 0xEB, 0xD8, 0x4B, 0xBF, 0x32, 0xA6, 0x19, 0x8D,
    0xF4, 0xDF, 0x51, 0xC4, 0x36, 0xA9, 0x1B, 0x8E, 0xFD, 0xE6, 0x57, 0xC9, 0x3A, 0xAC, 0x1D, 0x8F,
    0x06, 0xEE, 0x5D, 0xCE, 0x3E, 0xAF, 0x1F, 0x90, 0x0F, 0xF5, 0x63, 0xD3, 0x18, 0xFC, 0x69, 0xD8,
    0x21, 0x03, 0x70, 0xDD, 0x2A, 0x0A, 0x76, 0xE2, 0x33, 0x3C, 0x45, 0x4E, 0x57, 0x60, 0x69, 0x72,
    0x7B, 0x84, 0x8D, 0x96, 0x9F, 0xA8, 0xB1, 0xBA, 0xC3, 0xCC, 0xD5, 0xDE, 0xE7, 0xF0, 0xF9, 0x02,
    0x0B, 0x14, 0x1D, 0x26, 0x2F, 0x38, 0x41, 0x4A, 0x53, 0x5C, 0x65, 0x6E, 0x77, 0x80, 0x89, 0x92,
    0x9B, 0xA4, 0xAD, 0xB6, 0xBF, 0xC8, 0xD1, 0xDA, 0xE3, 0xEC, 0xF5, 0xFE, 0x07, 0x10, 0x19, 0x22,
    0x2B, 0x34, 0x3D, 0x46, 0x4F, 0x58, 0x61, 0x6A, 0x73, 0x7C, 0x85, 0x8E, 0x97, 0xA0, 0xA9, 0xB2,
    0xBB, 0xC4, 0xCD, 0xD6, 0xDF, 0xE8, 0xF1, 0xFA, 0x03, 0x0C, 0x15, 0x1E, 0x27, 0x30, 0x39, 0x42,
    0x4B, 0x54, 0x5D, 0x66, 0x6F, 0x78, 0x81, 0x8A, 0x93, 0x9C, 0xA5, 0xAE, 0xB7, 0xC0, 0xC9, 0xD2,
    0xDB, 0xE4, 0xED, 0xF6, 0xFF, 0x08, 0x11, 0x1A, 0x23, 0x2C, 0x35, 0x3E, 0x47, 0x50, 0x59, 0x62,
    0x6B, 0x74, 0x7D, 0x86, 0x8F, 0x98, 0xA1, 0xAA, 0xB3, 0xBC, 0xC5, 0xCE, 0xD7, 0xE0, 0xE9, 0xF2,
    0xFB, 0x04, 0x0D, 0x16, 0x1F, 0x28, 0x31, 0x3A, 0x43, 0x4C, 0x55, 0x5E, 0x67, 0x70, 0x79, 0x82,
    0x8B, 0x94, 0x9D, 0xA6, 0xAF, 0xB8, 0xC1, 0xCA, 0xD3, 0xDC, 0xE5, 0xEE, 0xF7, 0x00, 0x09, 0x12,
    0x1B, 0x24, 0x2D, 0x36, 0x3F, 0x48, 0x51, 0x5A, 0x63, 0x6C, 0x75, 0x7E, 0x87, 0x90, 0x99, 0xA2,
    0xAB, 0xB4, 0xBD, 0xC6, 0xCF, 0xD8, 0xE1, 0xEA, 0xF3, 0xFC, 0x05, 0x0E, 0x17, 0x20, 0x29, 0x32,
    0x3B, 0x44, 0x4D, 0x56, 0x5F, 0x68, 0x71, 0x7A, 0x83, 0x8C, 0x95, 0x9E, 0xA7, 0xB0, 0xB9, 0xC2,
    0xCB, 0xD4, 0xDD, 0xE6, 0xEF, 0xF8, 0x01, 0x0A, 0x13, 0x1C, 0x25, 0x2E, 0x37, 0x40, 0x49, 0x52,
    0x5B, 0x64, 0x6D, 0x76, 0x7F, 0x88, 0x91, 0x9A, 0xA3, 0xAC, 0xB5, 0xBE, 0xC7, 0xD0, 0xD9, 0xE2,
    0xEB, 0xF4, 0xFD, 0x06, 0x0F, 0x18, 0x21, 0x2A,
];
const MESSAGE_HEADER_BYTES: [u8; 80] = [
    0x72, 0x42, 0xA6, 0x0A, 0x6F, 0xD3, 0x37, 0x9C, 0x7B, 0x49, 0xAC, 0x0F, 0x73, 0xD6, 0x39, 0x9D,
    0x84, 0x50, 0xB2, 0x14, 0x77, 0xD9, 0x3B, 0x9E, 0x8D, 0x57, 0xB8, 0x19, 0x7B, 0xDC, 0x3D, 0x9F,
    0x96, 0x5E, 0xBE, 0x1E, 0x7F, 0xDF, 0x3F, 0xA0, 0x9F, 0x65, 0xC4, 0x23, 0x83, 0xE2, 0x41, 0xA1,
    0xA8, 0x6C, 0xCA, 0x28, 0x87, 0xE5, 0x43, 0xA2, 0xB1, 0x73, 0xD0, 0x2D, 0x8B, 0xE8, 0x45, 0xA3,
    0xBA, 0x7A, 0xD6, 0x32, 0xC3, 0x81, 0xDC, 0x37, 0xCC, 0x88, 0xE2, 0x3C, 0xD5, 0x8F, 0xE8, 0x41,
];
const RECEIVE_RESULT_BYTES: [u8; 376] = [
    0x14, 0xC1, 0x12, 0x65, 0xB7, 0x09, 0x5C, 0xAE, 0x1D, 0xC8, 0x18, 0x6A, 0xBB, 0x0C, 0x5E, 0xAF,
    0x26, 0xCF, 0x1E, 0x6F, 0xBF, 0x0F, 0x60, 0xB0, 0x2F, 0xD6, 0x24, 0x74, 0xC3, 0x12, 0x62, 0xB1,
    0x38, 0xDD, 0x2A, 0x79, 0xC7, 0x15, 0x64, 0xB2, 0x41, 0xE4, 0x30, 0x7E, 0xCB, 0x18, 0x66, 0xB3,
    0x4A, 0xEB, 0x36, 0x83, 0xCF, 0x1B, 0x68, 0xB4, 0x53, 0xF2, 0x3C, 0x88, 0xD3, 0x1E, 0x6A, 0xB5,
    0x5C, 0xF9, 0x42, 0x8D, 0x65, 0x00, 0x49, 0x92, 0x6E, 0x07, 0x4F, 0x97, 0x77, 0x0E, 0x55, 0x9C,
    0x38, 0xDD, 0x2A, 0x79, 0x41, 0xE4, 0x30, 0x7E, 0x4A, 0xEB, 0x36, 0x83, 0xCF, 0x1B, 0x68, 0xB4,
    0x53, 0xF2, 0x3C, 0x88, 0xD3, 0x1E, 0x6A, 0xB5, 0x5C, 0xF9, 0x42, 0x8D, 0xD7, 0x21, 0x6C, 0xB6,
    0x65, 0x00, 0x49, 0x92, 0xDB, 0x24, 0x6E, 0xB7, 0x6E, 0x77, 0x80, 0x89, 0x92, 0x9B, 0xA4, 0xAD,
    0xB6, 0xBF, 0xC8, 0xD1, 0xDA, 0xE3, 0xEC, 0xF5, 0xFE, 0x07, 0x10, 0x19, 0x22, 0x2B, 0x34, 0x3D,
    0x46, 0x4F, 0x58, 0x61, 0x6A, 0x73, 0x7C, 0x85, 0x8E, 0x97, 0xA0, 0xA9, 0xB2, 0xBB, 0xC4, 0xCD,
    0xD6, 0xDF, 0xE8, 0xF1, 0xFA, 0x03, 0x0C, 0x15, 0x1E, 0x27, 0x30, 0x39, 0x42, 0x4B, 0x54, 0x5D,
    0x66, 0x6F, 0x78, 0x81, 0x8A, 0x93, 0x9C, 0xA5, 0xAE, 0xB7, 0xC0, 0xC9, 0xD2, 0xDB, 0xE4, 0xED,
    0xF6, 0xFF, 0x08, 0x11, 0x1A, 0x23, 0x2C, 0x35, 0x3E, 0x47, 0x50, 0x59, 0x62, 0x6B, 0x74, 0x7D,
    0x86, 0x8F, 0x98, 0xA1, 0xAA, 0xB3, 0xBC, 0xC5, 0xCE, 0xD7, 0xE0, 0xE9, 0xF2, 0xFB, 0x04, 0x0D,
    0x16, 0x1F, 0x28, 0x31, 0x3A, 0x43, 0x4C, 0x55, 0x5E, 0x67, 0x70, 0x79, 0x82, 0x8B, 0x94, 0x9D,
    0xA6, 0xAF, 0xB8, 0xC1, 0xCA, 0xD3, 0xDC, 0xE5, 0xEE, 0xF7, 0x00, 0x09, 0x12, 0x1B, 0x24, 0x2D,
    0x36, 0x3F, 0x48, 0x51, 0x5A, 0x63, 0x6C, 0x75, 0x7E, 0x87, 0x90, 0x99, 0xA2, 0xAB, 0xB4, 0xBD,
    0xC6, 0xCF, 0xD8, 0xE1, 0xEA, 0xF3, 0xFC, 0x05, 0x0E, 0x17, 0x20, 0x29, 0x32, 0x3B, 0x44, 0x4D,
    0x56, 0x5F, 0x68, 0x71, 0x7A, 0x83, 0x8C, 0x95, 0x9E, 0xA7, 0xB0, 0xB9, 0xC2, 0xCB, 0xD4, 0xDD,
    0xE6, 0xEF, 0xF8, 0x01, 0x0A, 0x13, 0x1C, 0x25, 0x2E, 0x37, 0x40, 0x49, 0x52, 0x5B, 0x64, 0x6D,
    0x76, 0x7F, 0x88, 0x91, 0x9A, 0xA3, 0xAC, 0xB5, 0xBE, 0xC7, 0xD0, 0xD9, 0xE2, 0xEB, 0xF4, 0xFD,
    0x06, 0x0F, 0x18, 0x21, 0x2A, 0x33, 0x3C, 0x45, 0x4E, 0x57, 0x60, 0x69, 0x72, 0x7B, 0x84, 0x8D,
    0x96, 0x9F, 0xA8, 0xB1, 0xBA, 0xC3, 0xCC, 0xD5, 0xDE, 0xE7, 0xF0, 0xF9, 0x02, 0x0B, 0x14, 0x1D,
    0x26, 0x2F, 0x38, 0x41, 0x4A, 0x53, 0x5C, 0x65,
];
const INVOCATION_INFO_BYTES: [u8; 64] = [
    0xA4, 0x31, 0x73, 0xB5, 0xAD, 0x38, 0x79, 0xBA, 0xB6, 0x3F, 0x7F, 0xBF, 0xBF, 0x46, 0x85, 0xC4,
    0xC8, 0x4D, 0x8B, 0xC9, 0x07, 0x46, 0x84, 0xC2, 0xD1, 0x54, 0x91, 0xCE, 0x0B, 0x49, 0x86, 0xC3,
    0xDA, 0x5B, 0x97, 0xD3, 0x0F, 0x4C, 0x88, 0xC4, 0xE3, 0x62, 0x9D, 0xD8, 0x13, 0x4F, 0x8A, 0xC5,
    0xEC, 0x69, 0xA3, 0xDD, 0x17, 0x52, 0x8C, 0xC6, 0xF5, 0x70, 0xA9, 0xE2, 0x1B, 0x55, 0x8E, 0xC7,
];
const RECEIPT_RECORD_BYTES: [u8; 96] = [
    0x3D, 0xA9, 0xD9, 0x0A, 0x46, 0xB0, 0xDF, 0x0F, 0x4F, 0xB7, 0xE5, 0x14, 0x44, 0x73, 0xA2, 0xD1,
    0x58, 0xBE, 0xEB, 0x19, 0x48, 0x76, 0xA4, 0xD2, 0x61, 0xC5, 0xF1, 0x1E, 0x4C, 0x79, 0xA6, 0xD3,
    0x6A, 0xCC, 0xF7, 0x23, 0x50, 0x7C, 0xA8, 0xD4, 0x73, 0xD3, 0xFD, 0x28, 0x54, 0x7F, 0xAA, 0xD5,
    0x7C, 0xDA, 0x03, 0x2E, 0x58, 0x82, 0xAC, 0xD6, 0x85, 0xE1, 0x09, 0x33, 0x5C, 0x85, 0xAE, 0xD7,
    0x8E, 0xE8, 0x0F, 0x38, 0x60, 0x88, 0xB0, 0xD8, 0x1C, 0xFA, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xA0, 0xF6, 0x1B, 0x42, 0x68, 0x8E, 0xB4, 0xDA, 0xA9, 0xFD, 0x21, 0x47, 0x6C, 0x91, 0xB6, 0xDB,
];
const LOG_READ_RESULT_BYTES: [u8; 400] = [
    0xD6, 0x20, 0x40, 0x60, 0xDF, 0x27, 0x46, 0x65, 0xE8, 0x2E, 0x4C, 0x6A, 0x88, 0xA6, 0xC4, 0xE2,
    0xFA, 0x3C, 0x58, 0x74, 0x03, 0x44, 0x5E, 0x79, 0x0C, 0x4B, 0x64, 0x7E, 0x98, 0xB2, 0xCC, 0xE6,
    0x15, 0x52, 0x6A, 0x83, 0x9C, 0xB5, 0xCE, 0xE7, 0x1E, 0x59, 0x70, 0x88, 0xA0, 0xB8, 0xD0, 0xE8,
    0x27, 0x60, 0x76, 0x8D, 0xA4, 0xBB, 0xD2, 0xE9, 0x30, 0x67, 0x7C, 0x92, 0xA8, 0xBE, 0xD4, 0xEA,
    0x39, 0x6E, 0x82, 0x97, 0xAC, 0xC1, 0xD6, 0xEB, 0x42, 0x75, 0x88, 0x9C, 0xB0, 0xC4, 0xD8, 0xEC,
    0x4B, 0x7C, 0x8E, 0xA1, 0xB4, 0xC7, 0xDA, 0xED, 0x89, 0xF9, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x5D, 0x8A, 0x9A, 0xAB, 0xBC, 0xCD, 0xDE, 0xEF, 0x66, 0x91, 0xA0, 0xB0, 0xC0, 0xD0, 0xE0, 0xF0,
    0x15, 0x52, 0x6A, 0x83, 0x1E, 0x59, 0x70, 0x88, 0x27, 0x60, 0x76, 0x8D, 0xA4, 0xBB, 0xD2, 0xE9,
    0x30, 0x67, 0x7C, 0x92, 0xA8, 0xBE, 0xD4, 0xEA, 0x39, 0x6E, 0x82, 0x97, 0xAC, 0xC1, 0xD6, 0xEB,
    0x42, 0x75, 0x88, 0x9C, 0xB0, 0xC4, 0xD8, 0xEC, 0x4B, 0x7C, 0x8E, 0xA1, 0xB4, 0xC7, 0xDA, 0xED,
    0x54, 0x83, 0x94, 0xA6, 0xB8, 0xCA, 0xDC, 0xEE, 0x5D, 0x8A, 0x9A, 0xAB, 0xBC, 0xCD, 0xDE, 0xEF,
    0x66, 0x91, 0xA0, 0xB0, 0xC0, 0xD0, 0xE0, 0xF0, 0x74, 0xF9, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x78, 0x9F, 0xAC, 0xBA, 0xC8, 0xD6, 0xE4, 0xF2, 0x81, 0xA6, 0xB2, 0xBF, 0xCC, 0xD9, 0xE6, 0xF3,
    0x30, 0x67, 0x7C, 0x92, 0x39, 0x6E, 0x82, 0x97, 0x42, 0x75, 0x88, 0x9C, 0xB0, 0xC4, 0xD8, 0xEC,
    0x4B, 0x7C, 0x8E, 0xA1, 0xB4, 0xC7, 0xDA, 0xED, 0x54, 0x83, 0x94, 0xA6, 0xB8, 0xCA, 0xDC, 0xEE,
    0x5D, 0x8A, 0x9A, 0xAB, 0xBC, 0xCD, 0xDE, 0xEF, 0x66, 0x91, 0xA0, 0xB0, 0xC0, 0xD0, 0xE0, 0xF0,
    0x6F, 0x98, 0xA6, 0xB5, 0xC4, 0xD3, 0xE2, 0xF1, 0x78, 0x9F, 0xAC, 0xBA, 0xC8, 0xD6, 0xE4, 0xF2,
    0x81, 0xA6, 0xB2, 0xBF, 0xCC, 0xD9, 0xE6, 0xF3, 0x5F, 0xF9, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0x93, 0xB4, 0xBE, 0xC9, 0xD4, 0xDF, 0xEA, 0xF5, 0x9C, 0xBB, 0xC4, 0xCE, 0xD8, 0xE2, 0xEC, 0xF6,
    0x4B, 0x7C, 0x8E, 0xA1, 0x54, 0x83, 0x94, 0xA6, 0x5D, 0x8A, 0x9A, 0xAB, 0xBC, 0xCD, 0xDE, 0xEF,
    0x66, 0x91, 0xA0, 0xB0, 0xC0, 0xD0, 0xE0, 0xF0, 0x6F, 0x98, 0xA6, 0xB5, 0xC4, 0xD3, 0xE2, 0xF1,
    0x78, 0x9F, 0xAC, 0xBA, 0xC8, 0xD6, 0xE4, 0xF2, 0x81, 0xA6, 0xB2, 0xBF, 0xCC, 0xD9, 0xE6, 0xF3,
    0x8A, 0xAD, 0xB8, 0xC4, 0xD0, 0xDC, 0xE8, 0xF4, 0x93, 0xB4, 0xBE, 0xC9, 0xD4, 0xDF, 0xEA, 0xF5,
    0x9C, 0xBB, 0xC4, 0xCE, 0xD8, 0xE2, 0xEC, 0xF6, 0x4A, 0xF9, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xAE, 0xC9, 0xD0, 0xD8, 0xE0, 0xE8, 0xF0, 0xF8, 0xB7, 0xD0, 0xD6, 0xDD, 0xE4, 0xEB, 0xF2, 0xF9,
];
const FAULT_REPORT_BYTES: [u8; 72] = [
    0x6F, 0x98, 0xA6, 0xB5, 0xC4, 0xD3, 0xE2, 0xF1, 0x78, 0x9F, 0xAC, 0xBA, 0xC8, 0xD6, 0xE4, 0xF2,
    0x81, 0xA6, 0xB2, 0xBF, 0xCC, 0xD9, 0xE6, 0xF3, 0x8A, 0xAD, 0xB8, 0xC4, 0xD0, 0xDC, 0xE8, 0xF4,
    0x93, 0xB4, 0xBE, 0xC9, 0xD4, 0xDF, 0xEA, 0xF5, 0x9C, 0xBB, 0xC4, 0xCE, 0xD8, 0xE2, 0xEC, 0xF6,
    0xA5, 0xC2, 0xCA, 0xD3, 0xDC, 0xE5, 0xEE, 0xF7, 0xAE, 0xC9, 0xD0, 0xD8, 0xE0, 0xE8, 0xF0, 0xF8,
    0xB7, 0xD0, 0xD6, 0xDD, 0xC0, 0xD7, 0xDC, 0xE2,
];

/// Every fixture the schema defines.
pub const FIXTURES: [Fixture; 15] = [
    Fixture {
        name: "DescriptorHeader",
        bytes: &DESCRIPTOR_HEADER_BYTES,
        size: 32,
    },
    Fixture {
        name: "Limits",
        bytes: &LIMITS_BYTES,
        size: 88,
    },
    Fixture {
        name: "CapInfo",
        bytes: &CAP_INFO_BYTES,
        size: 64,
    },
    Fixture {
        name: "DeriveRequest",
        bytes: &DERIVE_REQUEST_BYTES,
        size: 24,
    },
    Fixture {
        name: "ScopeInfo",
        bytes: &SCOPE_INFO_BYTES,
        size: 144,
    },
    Fixture {
        name: "DrainReport",
        bytes: &DRAIN_REPORT_BYTES,
        size: 64,
    },
    Fixture {
        name: "MapRequest",
        bytes: &MAP_REQUEST_BYTES,
        size: 32,
    },
    Fixture {
        name: "MemoryInfo",
        bytes: &MEMORY_INFO_BYTES,
        size: 56,
    },
    Fixture {
        name: "SendRequest",
        bytes: &SEND_REQUEST_BYTES,
        size: 312,
    },
    Fixture {
        name: "MessageHeader",
        bytes: &MESSAGE_HEADER_BYTES,
        size: 80,
    },
    Fixture {
        name: "ReceiveResult",
        bytes: &RECEIVE_RESULT_BYTES,
        size: 376,
    },
    Fixture {
        name: "InvocationInfo",
        bytes: &INVOCATION_INFO_BYTES,
        size: 64,
    },
    Fixture {
        name: "ReceiptRecord",
        bytes: &RECEIPT_RECORD_BYTES,
        size: 96,
    },
    Fixture {
        name: "LogReadResult",
        bytes: &LOG_READ_RESULT_BYTES,
        size: 400,
    },
    Fixture {
        name: "FaultReport",
        bytes: &FAULT_REPORT_BYTES,
        size: 72,
    },
];

/// Decodes every fixture and compares each field with the generator's value.
///
/// Returns `(checked, failed)`. A failure means this build's layout differs
/// from the schema the bytes were produced from.
#[must_use]
pub fn verify() -> (u32, u32) {
    let mut checked = 0u32;
    let mut failed = 0u32;
    // DescriptorHeader
    {
        let bytes = &DESCRIPTOR_HEADER_BYTES;
        // SAFETY: the array is 32 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: DescriptorHeader =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<DescriptorHeader>()) };
        checked += 1;
        if value.major != 3601u16 {
            failed += 1;
        }
        checked += 1;
        if value.minor != 5402u16 {
            failed += 1;
        }
        checked += 1;
        if value.opcode != 337124387u32 {
            failed += 1;
        }
        checked += 1;
        if value.flags != 421405484u32 {
            failed += 1;
        }
        checked += 1;
        if value.total_len != 505686581u32 {
            failed += 1;
        }
        checked += 1;
        if value.cookie != 508367018532679998u64 {
            failed += 1;
        }
        checked += 1;
        if value.reserved != 580990878323062855u64 {
            failed += 1;
        }
    }
    // Limits
    {
        let bytes = &LIMITS_BYTES;
        // SAFETY: the array is 88 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: Limits = unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<Limits>()) };
        checked += 1;
        if value.major != 34218u16 {
            failed += 1;
        }
        checked += 1;
        if value.minor != 36019u16 {
            failed += 1;
        }
        checked += 1;
        if value.max_descriptor_len != 1769903036u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_inline_payload != 1854184133u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_caps_per_message != 1938465230u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_scope_depth != 2022746327u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_derive_depth != 2107027424u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_handles_per_domain != 2191308521u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_endpoint_queue != 2275589618u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_memory_pages_per_object != 2359870715u32 {
            failed += 1;
        }
        checked += 1;
        if value.control_log_capacity != 2444151812u32 {
            failed += 1;
        }
        checked += 1;
        if value.control_log_reserved != 2528432909u32 {
            failed += 1;
        }
        checked += 1;
        if value.receipt_batch != 2612714006u32 {
            failed += 1;
        }
        checked += 1;
        if value.cpu_window_ns != 2323963513292251423u64 {
            failed += 1;
        }
        checked += 1;
        if value.cpu_quantum_ns != 2396587373082634280u64 {
            failed += 1;
        }
        checked += 1;
        if value.page_size != 2469211232873017137u64 {
            failed += 1;
        }
        checked += 1;
        if value.boot_epoch != 2541835092663399994u64 {
            failed += 1;
        }
        checked += 1;
        if value.cpus_online != 3034119491u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 3118400588u32 {
            failed += 1;
        }
    }
    // CapInfo
    {
        let bytes = &CAP_INFO_BYTES;
        // SAFETY: the array is 64 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: CapInfo = unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<CapInfo>()) };
        checked += 1;
        if value.object_type != 3034119491u32 {
            failed += 1;
        }
        checked += 1;
        if value.rights != 3118400588u32 {
            failed += 1;
        }
        checked += 1;
        if value.derive_depth != 3202681685u32 {
            failed += 1;
        }
        checked += 1;
        if value.lineage_state != 3286962782u32 {
            failed += 1;
        }
        checked += 1;
        if value.grant_id != 2904954391615314279u64 {
            failed += 1;
        }
        checked += 1;
        if value.parent_grant_id != 2977578251405697136u64 {
            failed += 1;
        }
        checked += 1;
        if value.deadline_ns != 3050202111196079993u64 {
            failed += 1;
        }
        checked += 1;
        if value.life_scope_id != 3122825970986462850u64 {
            failed += 1;
        }
        checked += 1;
        if value.object_id != 3195449830776845707u64 {
            failed += 1;
        }
        checked += 1;
        if value.facet != 3268073690567228564u64 {
            failed += 1;
        }
    }
    // DeriveRequest
    {
        let bytes = &DERIVE_REQUEST_BYTES;
        // SAFETY: the array is 24 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: DeriveRequest =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<DeriveRequest>()) };
        checked += 1;
        if value.rights_mask != 171930844u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 256211941u32 {
            failed += 1;
        }
        checked += 1;
        if value.deadline_ns != 3994312288471057134u64 {
            failed += 1;
        }
        checked += 1;
        if value.life_scope != 4066936148261439991u64 {
            failed += 1;
        }
    }
    // ScopeInfo
    {
        let bytes = &SCOPE_INFO_BYTES;
        // SAFETY: the array is 144 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: ScopeInfo =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<ScopeInfo>()) };
        checked += 1;
        if value.limits.memory_pages != 5156294045117182846u64 {
            failed += 1;
        }
        checked += 1;
        if value.limits.metadata_objects != 5228917904907565703u64 {
            failed += 1;
        }
        checked += 1;
        if value.limits.cpu_budget_ns != 5301541764697948560u64 {
            failed += 1;
        }
        checked += 1;
        if value.limits.queue_bytes != 5374165624488331417u64 {
            failed += 1;
        }
        checked += 1;
        if value.limits.closure_reserve_ns != 5446789484278714274u64 {
            failed += 1;
        }
        checked += 1;
        if value.limits.parallelism != 2110396075u32 {
            failed += 1;
        }
        checked += 1;
        if value.limits.reserved0 != 2194677172u32 {
            failed += 1;
        }
        checked += 1;
        if value.state != 2026114978u32 {
            failed += 1;
        }
        checked += 1;
        if value.depth != 2110396075u32 {
            failed += 1;
        }
        checked += 1;
        if value.parallelism_used != 2194677172u32 {
            failed += 1;
        }
        checked += 1;
        if value.threads != 2278958269u32 {
            failed += 1;
        }
        checked += 1;
        if value.scope_id != 5737284923440245702u64 {
            failed += 1;
        }
        checked += 1;
        if value.parent_scope_id != 5809908783230628559u64 {
            failed += 1;
        }
        checked += 1;
        if value.memory_pages_used != 5882532643021011416u64 {
            failed += 1;
        }
        checked += 1;
        if value.metadata_used != 5955156502811394273u64 {
            failed += 1;
        }
        checked += 1;
        if value.queue_bytes_used != 6027780362601777130u64 {
            failed += 1;
        }
        checked += 1;
        if value.cpu_window_used_ns != 6100404222392159987u64 {
            failed += 1;
        }
        checked += 1;
        if value.cpu_total_ns != 6173028082182542844u64 {
            failed += 1;
        }
        checked += 1;
        if value.cpu_debt_ns != 6245651941972925701u64 {
            failed += 1;
        }
        checked += 1;
        if value.closure_used_ns != 6318275801763308558u64 {
            failed += 1;
        }
        checked += 1;
        if value.window_index != 6390899661553691415u64 {
            failed += 1;
        }
    }
    // DrainReport
    {
        let bytes = &DRAIN_REPORT_BYTES;
        // SAFETY: the array is 64 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: DrainReport =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<DrainReport>()) };
        checked += 1;
        if value.state != 3037488142u32 {
            failed += 1;
        }
        checked += 1;
        if value.threads_running != 3121769239u32 {
            failed += 1;
        }
        checked += 1;
        if value.invocations_pending != 3206050336u32 {
            failed += 1;
        }
        checked += 1;
        if value.effects_pending != 3290331433u32 {
            failed += 1;
        }
        checked += 1;
        if value.maps_pending != 3374612530u32 {
            failed += 1;
        }
        checked += 1;
        if value.undelivered_cancelled != 3458893627u32 {
            failed += 1;
        }
        checked += 1;
        if value.external_unknown != 3543174724u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 3627455821u32 {
            failed += 1;
        }
        checked += 1;
        if value.retained_pages != 6899266680086371414u64 {
            failed += 1;
        }
        checked += 1;
        if value.retained_metadata != 6971890539876754271u64 {
            failed += 1;
        }
        checked += 1;
        if value.last_progress_ns != 7044514399667137128u64 {
            failed += 1;
        }
        checked += 1;
        if value.token != 7117138259457519985u64 {
            failed += 1;
        }
    }
    // MapRequest
    {
        let bytes = &MAP_REQUEST_BYTES;
        // SAFETY: the array is 32 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: MapRequest =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<MapRequest>()) };
        checked += 1;
        if value.memory_handle != 7552881418199817127u64 {
            failed += 1;
        }
        checked += 1;
        if value.vaddr != 7625505277990199984u64 {
            failed += 1;
        }
        checked += 1;
        if value.offset_pages != 343861689u32 {
            failed += 1;
        }
        checked += 1;
        if value.page_count != 428142786u32 {
            failed += 1;
        }
        checked += 1;
        if value.rights != 512423883u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 596704980u32 {
            failed += 1;
        }
    }
    // MemoryInfo
    {
        let bytes = &MEMORY_INFO_BYTES;
        // SAFETY: the array is 56 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: MemoryInfo =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<MemoryInfo>()) };
        checked += 1;
        if value.state != 1608078144u32 {
            failed += 1;
        }
        checked += 1;
        if value.max_rights != 1692359241u32 {
            failed += 1;
        }
        checked += 1;
        if value.map_count != 1776640338u32 {
            failed += 1;
        }
        checked += 1;
        if value.writable_maps != 1860921435u32 {
            failed += 1;
        }
        checked += 1;
        if value.pages != 9077982473797857124u64 {
            failed += 1;
        }
        checked += 1;
        if value.object_id != 9150606333588239981u64 {
            failed += 1;
        }
        checked += 1;
        if value.sponsor_scope_id != 9223230193378622838u64 {
            failed += 1;
        }
        checked += 1;
        if value.label[0] != 127u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[1] != 136u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[2] != 145u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[3] != 154u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[4] != 163u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[5] != 172u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[6] != 181u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[7] != 190u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[8] != 199u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[9] != 208u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[10] != 217u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[11] != 226u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[12] != 235u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[13] != 244u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[14] != 253u8 {
            failed += 1;
        }
        checked += 1;
        if value.label[15] != 6u8 {
            failed += 1;
        }
    }
    // SendRequest
    {
        let bytes = &SEND_REQUEST_BYTES;
        // SAFETY: the array is 312 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: SendRequest =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<SendRequest>()) };
        checked += 1;
        if value.payload_len != 3040856793u32 {
            failed += 1;
        }
        checked += 1;
        if value.cap_count != 3125137890u32 {
            failed += 1;
        }
        checked += 1;
        if value.caps[0] != 10167340370653599979u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[1] != 10239964230443982836u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[2] != 10312588090234365693u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[3] != 10385211950024748550u64 {
            failed += 1;
        }
        checked += 1;
        if value.cap_ops[0] != 3546543375u32 {
            failed += 1;
        }
        checked += 1;
        if value.cap_ops[1] != 3630824472u32 {
            failed += 1;
        }
        checked += 1;
        if value.cap_ops[2] != 3715105569u32 {
            failed += 1;
        }
        checked += 1;
        if value.cap_ops[3] != 3799386666u32 {
            failed += 1;
        }
        checked += 1;
        if value.payload[0] != 51u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[1] != 60u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[2] != 69u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[3] != 78u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[4] != 87u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[5] != 96u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[6] != 105u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[7] != 114u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[8] != 123u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[9] != 132u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[10] != 141u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[11] != 150u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[12] != 159u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[13] != 168u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[14] != 177u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[15] != 186u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[16] != 195u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[17] != 204u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[18] != 213u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[19] != 222u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[20] != 231u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[21] != 240u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[22] != 249u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[23] != 2u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[24] != 11u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[25] != 20u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[26] != 29u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[27] != 38u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[28] != 47u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[29] != 56u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[30] != 65u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[31] != 74u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[32] != 83u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[33] != 92u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[34] != 101u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[35] != 110u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[36] != 119u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[37] != 128u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[38] != 137u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[39] != 146u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[40] != 155u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[41] != 164u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[42] != 173u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[43] != 182u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[44] != 191u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[45] != 200u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[46] != 209u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[47] != 218u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[48] != 227u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[49] != 236u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[50] != 245u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[51] != 254u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[52] != 7u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[53] != 16u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[54] != 25u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[55] != 34u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[56] != 43u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[57] != 52u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[58] != 61u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[59] != 70u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[60] != 79u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[61] != 88u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[62] != 97u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[63] != 106u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[64] != 115u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[65] != 124u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[66] != 133u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[67] != 142u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[68] != 151u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[69] != 160u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[70] != 169u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[71] != 178u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[72] != 187u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[73] != 196u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[74] != 205u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[75] != 214u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[76] != 223u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[77] != 232u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[78] != 241u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[79] != 250u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[80] != 3u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[81] != 12u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[82] != 21u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[83] != 30u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[84] != 39u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[85] != 48u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[86] != 57u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[87] != 66u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[88] != 75u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[89] != 84u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[90] != 93u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[91] != 102u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[92] != 111u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[93] != 120u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[94] != 129u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[95] != 138u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[96] != 147u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[97] != 156u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[98] != 165u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[99] != 174u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[100] != 183u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[101] != 192u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[102] != 201u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[103] != 210u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[104] != 219u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[105] != 228u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[106] != 237u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[107] != 246u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[108] != 255u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[109] != 8u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[110] != 17u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[111] != 26u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[112] != 35u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[113] != 44u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[114] != 53u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[115] != 62u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[116] != 71u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[117] != 80u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[118] != 89u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[119] != 98u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[120] != 107u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[121] != 116u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[122] != 125u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[123] != 134u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[124] != 143u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[125] != 152u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[126] != 161u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[127] != 170u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[128] != 179u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[129] != 188u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[130] != 197u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[131] != 206u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[132] != 215u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[133] != 224u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[134] != 233u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[135] != 242u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[136] != 251u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[137] != 4u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[138] != 13u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[139] != 22u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[140] != 31u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[141] != 40u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[142] != 49u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[143] != 58u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[144] != 67u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[145] != 76u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[146] != 85u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[147] != 94u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[148] != 103u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[149] != 112u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[150] != 121u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[151] != 130u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[152] != 139u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[153] != 148u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[154] != 157u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[155] != 166u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[156] != 175u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[157] != 184u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[158] != 193u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[159] != 202u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[160] != 211u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[161] != 220u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[162] != 229u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[163] != 238u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[164] != 247u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[165] != 0u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[166] != 9u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[167] != 18u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[168] != 27u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[169] != 36u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[170] != 45u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[171] != 54u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[172] != 63u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[173] != 72u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[174] != 81u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[175] != 90u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[176] != 99u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[177] != 108u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[178] != 117u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[179] != 126u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[180] != 135u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[181] != 144u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[182] != 153u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[183] != 162u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[184] != 171u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[185] != 180u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[186] != 189u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[187] != 198u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[188] != 207u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[189] != 216u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[190] != 225u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[191] != 234u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[192] != 243u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[193] != 252u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[194] != 5u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[195] != 14u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[196] != 23u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[197] != 32u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[198] != 41u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[199] != 50u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[200] != 59u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[201] != 68u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[202] != 77u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[203] != 86u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[204] != 95u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[205] != 104u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[206] != 113u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[207] != 122u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[208] != 131u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[209] != 140u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[210] != 149u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[211] != 158u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[212] != 167u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[213] != 176u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[214] != 185u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[215] != 194u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[216] != 203u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[217] != 212u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[218] != 221u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[219] != 230u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[220] != 239u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[221] != 248u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[222] != 1u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[223] != 10u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[224] != 19u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[225] != 28u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[226] != 37u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[227] != 46u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[228] != 55u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[229] != 64u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[230] != 73u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[231] != 82u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[232] != 91u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[233] != 100u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[234] != 109u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[235] != 118u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[236] != 127u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[237] != 136u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[238] != 145u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[239] != 154u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[240] != 163u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[241] != 172u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[242] != 181u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[243] != 190u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[244] != 199u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[245] != 208u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[246] != 217u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[247] != 226u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[248] != 235u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[249] != 244u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[250] != 253u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[251] != 6u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[252] != 15u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[253] != 24u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[254] != 33u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[255] != 42u8 {
            failed += 1;
        }
    }
    // MessageHeader
    {
        let bytes = &MESSAGE_HEADER_BYTES;
        // SAFETY: the array is 80 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: MessageHeader =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<MessageHeader>()) };
        checked += 1;
        if value.epoch != 11256698267509342834u64 {
            failed += 1;
        }
        checked += 1;
        if value.invocation_id != 11329322127299725691u64 {
            failed += 1;
        }
        checked += 1;
        if value.sender_domain_id != 11401945987090108548u64 {
            failed += 1;
        }
        checked += 1;
        if value.sender_scope_id != 11474569846880491405u64 {
            failed += 1;
        }
        checked += 1;
        if value.parent_invocation_id != 11547193706670874262u64 {
            failed += 1;
        }
        checked += 1;
        if value.facet != 11619817566461257119u64 {
            failed += 1;
        }
        checked += 1;
        if value.grant_id != 11692441426251639976u64 {
            failed += 1;
        }
        checked += 1;
        if value.sent_ns != 11765065286042022833u64 {
            failed += 1;
        }
        checked += 1;
        if value.rights_transferred != 852916922u32 {
            failed += 1;
        }
        checked += 1;
        if value.cancel_state != 937198019u32 {
            failed += 1;
        }
        checked += 1;
        if value.kind != 1021479116u32 {
            failed += 1;
        }
        checked += 1;
        if value.payload_len != 1105760213u32 {
            failed += 1;
        }
    }
    // ReceiveResult
    {
        let bytes = &RECEIVE_RESULT_BYTES;
        // SAFETY: the array is 376 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: ReceiveResult =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<ReceiveResult>()) };
        checked += 1;
        if value.header.epoch != 12563927743736234260u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.invocation_id != 12636551603526617117u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.sender_domain_id != 12709175463316999974u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.sender_scope_id != 12781799323107382831u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.parent_invocation_id != 12854423182897765688u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.facet != 12927047042688148545u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.grant_id != 12999670902478531402u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.sent_ns != 13072294762268914259u64 {
            failed += 1;
        }
        checked += 1;
        if value.header.rights_transferred != 2369976668u32 {
            failed += 1;
        }
        checked += 1;
        if value.header.cancel_state != 2454257765u32 {
            failed += 1;
        }
        checked += 1;
        if value.header.kind != 2538538862u32 {
            failed += 1;
        }
        checked += 1;
        if value.header.payload_len != 2622819959u32 {
            failed += 1;
        }
        checked += 1;
        if value.cap_count != 2032852280u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 2117133377u32 {
            failed += 1;
        }
        checked += 1;
        if value.caps[0] != 12999670902478531402u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[1] != 13072294762268914259u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[2] != 13144918622059297116u64 {
            failed += 1;
        }
        checked += 1;
        if value.caps[3] != 13217542481849679973u64 {
            failed += 1;
        }
        checked += 1;
        if value.payload[0] != 110u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[1] != 119u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[2] != 128u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[3] != 137u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[4] != 146u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[5] != 155u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[6] != 164u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[7] != 173u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[8] != 182u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[9] != 191u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[10] != 200u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[11] != 209u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[12] != 218u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[13] != 227u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[14] != 236u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[15] != 245u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[16] != 254u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[17] != 7u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[18] != 16u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[19] != 25u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[20] != 34u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[21] != 43u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[22] != 52u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[23] != 61u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[24] != 70u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[25] != 79u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[26] != 88u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[27] != 97u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[28] != 106u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[29] != 115u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[30] != 124u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[31] != 133u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[32] != 142u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[33] != 151u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[34] != 160u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[35] != 169u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[36] != 178u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[37] != 187u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[38] != 196u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[39] != 205u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[40] != 214u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[41] != 223u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[42] != 232u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[43] != 241u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[44] != 250u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[45] != 3u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[46] != 12u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[47] != 21u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[48] != 30u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[49] != 39u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[50] != 48u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[51] != 57u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[52] != 66u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[53] != 75u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[54] != 84u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[55] != 93u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[56] != 102u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[57] != 111u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[58] != 120u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[59] != 129u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[60] != 138u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[61] != 147u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[62] != 156u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[63] != 165u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[64] != 174u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[65] != 183u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[66] != 192u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[67] != 201u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[68] != 210u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[69] != 219u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[70] != 228u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[71] != 237u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[72] != 246u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[73] != 255u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[74] != 8u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[75] != 17u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[76] != 26u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[77] != 35u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[78] != 44u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[79] != 53u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[80] != 62u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[81] != 71u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[82] != 80u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[83] != 89u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[84] != 98u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[85] != 107u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[86] != 116u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[87] != 125u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[88] != 134u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[89] != 143u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[90] != 152u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[91] != 161u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[92] != 170u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[93] != 179u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[94] != 188u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[95] != 197u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[96] != 206u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[97] != 215u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[98] != 224u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[99] != 233u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[100] != 242u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[101] != 251u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[102] != 4u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[103] != 13u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[104] != 22u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[105] != 31u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[106] != 40u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[107] != 49u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[108] != 58u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[109] != 67u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[110] != 76u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[111] != 85u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[112] != 94u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[113] != 103u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[114] != 112u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[115] != 121u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[116] != 130u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[117] != 139u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[118] != 148u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[119] != 157u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[120] != 166u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[121] != 175u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[122] != 184u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[123] != 193u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[124] != 202u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[125] != 211u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[126] != 220u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[127] != 229u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[128] != 238u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[129] != 247u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[130] != 0u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[131] != 9u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[132] != 18u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[133] != 27u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[134] != 36u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[135] != 45u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[136] != 54u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[137] != 63u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[138] != 72u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[139] != 81u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[140] != 90u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[141] != 99u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[142] != 108u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[143] != 117u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[144] != 126u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[145] != 135u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[146] != 144u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[147] != 153u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[148] != 162u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[149] != 171u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[150] != 180u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[151] != 189u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[152] != 198u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[153] != 207u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[154] != 216u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[155] != 225u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[156] != 234u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[157] != 243u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[158] != 252u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[159] != 5u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[160] != 14u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[161] != 23u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[162] != 32u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[163] != 41u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[164] != 50u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[165] != 59u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[166] != 68u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[167] != 77u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[168] != 86u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[169] != 95u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[170] != 104u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[171] != 113u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[172] != 122u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[173] != 131u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[174] != 140u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[175] != 149u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[176] != 158u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[177] != 167u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[178] != 176u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[179] != 185u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[180] != 194u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[181] != 203u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[182] != 212u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[183] != 221u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[184] != 230u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[185] != 239u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[186] != 248u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[187] != 1u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[188] != 10u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[189] != 19u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[190] != 28u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[191] != 37u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[192] != 46u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[193] != 55u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[194] != 64u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[195] != 73u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[196] != 82u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[197] != 91u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[198] != 100u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[199] != 109u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[200] != 118u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[201] != 127u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[202] != 136u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[203] != 145u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[204] != 154u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[205] != 163u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[206] != 172u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[207] != 181u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[208] != 190u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[209] != 199u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[210] != 208u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[211] != 217u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[212] != 226u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[213] != 235u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[214] != 244u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[215] != 253u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[216] != 6u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[217] != 15u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[218] != 24u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[219] != 33u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[220] != 42u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[221] != 51u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[222] != 60u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[223] != 69u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[224] != 78u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[225] != 87u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[226] != 96u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[227] != 105u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[228] != 114u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[229] != 123u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[230] != 132u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[231] != 141u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[232] != 150u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[233] != 159u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[234] != 168u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[235] != 177u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[236] != 186u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[237] != 195u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[238] != 204u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[239] != 213u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[240] != 222u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[241] != 231u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[242] != 240u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[243] != 249u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[244] != 2u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[245] != 11u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[246] != 20u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[247] != 29u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[248] != 38u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[249] != 47u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[250] != 56u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[251] != 65u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[252] != 74u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[253] != 83u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[254] != 92u8 {
            failed += 1;
        }
        checked += 1;
        if value.payload[255] != 101u8 {
            failed += 1;
        }
    }
    // InvocationInfo
    {
        let bytes = &INVOCATION_INFO_BYTES;
        // SAFETY: the array is 64 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: InvocationInfo =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<InvocationInfo>()) };
        checked += 1;
        if value.state != 3044225444u32 {
            failed += 1;
        }
        checked += 1;
        if value.cancel_state != 3128506541u32 {
            failed += 1;
        }
        checked += 1;
        if value.effect_state != 3212787638u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 3297068735u32 {
            failed += 1;
        }
        checked += 1;
        if value.invocation_id != 14016404939543891400u64 {
            failed += 1;
        }
        checked += 1;
        if value.origin_domain_id != 14089028799334274257u64 {
            failed += 1;
        }
        checked += 1;
        if value.origin_scope_id != 14161652659124657114u64 {
            failed += 1;
        }
        checked += 1;
        if value.facet != 14234276518915039971u64 {
            failed += 1;
        }
        checked += 1;
        if value.grant_id != 14306900378705422828u64 {
            failed += 1;
        }
        checked += 1;
        if value.admitted_ns != 14379524238495805685u64 {
            failed += 1;
        }
    }
    // ReceiptRecord
    {
        let bytes = &RECEIPT_RECORD_BYTES;
        // SAFETY: the array is 96 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: ReceiptRecord =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<ReceiptRecord>()) };
        checked += 1;
        if value.schema != 182036797u32 {
            failed += 1;
        }
        checked += 1;
        if value.kind != 266317894u32 {
            failed += 1;
        }
        checked += 1;
        if value.sequence != 15105762836399634255u64 {
            failed += 1;
        }
        checked += 1;
        if value.epoch != 15178386696190017112u64 {
            failed += 1;
        }
        checked += 1;
        if value.ns != 15251010555980399969u64 {
            failed += 1;
        }
        checked += 1;
        if value.origin_domain_id != 15323634415770782826u64 {
            failed += 1;
        }
        checked += 1;
        if value.origin_scope_id != 15396258275561165683u64 {
            failed += 1;
        }
        checked += 1;
        if value.object_id != 15468882135351548540u64 {
            failed += 1;
        }
        checked += 1;
        if value.grant_id != 15541505995141931397u64 {
            failed += 1;
        }
        checked += 1;
        if value.parent_invocation_id != 15614129854932314254u64 {
            failed += 1;
        }
        checked += 1;
        if value.result != -1508i64 {
            failed += 1;
        }
        checked += 1;
        if value.a != 15759377574513079968u64 {
            failed += 1;
        }
        checked += 1;
        if value.b != 15832001434303462825u64 {
            failed += 1;
        }
    }
    // LogReadResult
    {
        let bytes = &LOG_READ_RESULT_BYTES;
        // SAFETY: the array is 400 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: LogReadResult =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<LogReadResult>()) };
        checked += 1;
        if value.count != 1614815446u32 {
            failed += 1;
        }
        checked += 1;
        if value.lost != 1699096543u32 {
            failed += 1;
        }
        checked += 1;
        if value.next_sequence != 16340368452836142824u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].schema != 1951939834u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].kind != 2036220931u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].sequence != 16630863891997674252u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].epoch != 16703487751788057109u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].ns != 16776111611578439966u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].origin_domain_id != 16848735471368822823u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].origin_scope_id != 16921359331159205680u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].object_id != 16993983190949588537u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].grant_id != 17066607050739971394u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].parent_invocation_id != 17139230910530354251u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].result != -1655i64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].a != 17284478630111119965u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[0].b != 17357102489901502822u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].schema != 2204783125u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].kind != 2289064222u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].sequence != 16848735471368822823u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].epoch != 16921359331159205680u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].ns != 16993983190949588537u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].origin_domain_id != 17066607050739971394u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].origin_scope_id != 17139230910530354251u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].object_id != 17211854770320737108u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].grant_id != 17284478630111119965u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].parent_invocation_id != 17357102489901502822u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].result != -1676i64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].a != 17502350209482268536u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[1].b != 17574974069272651393u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].schema != 2457626416u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].kind != 2541907513u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].sequence != 17066607050739971394u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].epoch != 17139230910530354251u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].ns != 17211854770320737108u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].origin_domain_id != 17284478630111119965u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].origin_scope_id != 17357102489901502822u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].object_id != 17429726349691885679u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].grant_id != 17502350209482268536u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].parent_invocation_id != 17574974069272651393u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].result != -1697i64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].a != 17720221788853417107u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[2].b != 17792845648643799964u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].schema != 2710469707u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].kind != 2794750804u32 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].sequence != 17284478630111119965u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].epoch != 17357102489901502822u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].ns != 17429726349691885679u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].origin_domain_id != 17502350209482268536u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].origin_scope_id != 17574974069272651393u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].object_id != 17647597929063034250u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].grant_id != 17720221788853417107u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].parent_invocation_id != 17792845648643799964u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].result != -1718i64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].a != 17938093368224565678u64 {
            failed += 1;
        }
        checked += 1;
        if value.records[3].b != 18010717228014948535u64 {
            failed += 1;
        }
    }
    // FaultReport
    {
        let bytes = &FAULT_REPORT_BYTES;
        // SAFETY: the array is 72 bytes, the exact size of
        // the structure, every field of which is an integer, so any bit
        // pattern is a valid value. The read is unaligned by construction.
        let value: FaultReport =
            unsafe { core::ptr::read_unaligned(bytes.as_ptr().cast::<FaultReport>()) };
        checked += 1;
        if value.domain_id != 17429726349691885679u64 {
            failed += 1;
        }
        checked += 1;
        if value.thread_id != 17502350209482268536u64 {
            failed += 1;
        }
        checked += 1;
        if value.generation != 17574974069272651393u64 {
            failed += 1;
        }
        checked += 1;
        if value.vector != 17647597929063034250u64 {
            failed += 1;
        }
        checked += 1;
        if value.error_code != 17720221788853417107u64 {
            failed += 1;
        }
        checked += 1;
        if value.rip != 17792845648643799964u64 {
            failed += 1;
        }
        checked += 1;
        if value.rsp != 17865469508434182821u64 {
            failed += 1;
        }
        checked += 1;
        if value.address != 17938093368224565678u64 {
            failed += 1;
        }
        checked += 1;
        if value.class != 3721842871u32 {
            failed += 1;
        }
        checked += 1;
        if value.reserved0 != 3806123968u32 {
            failed += 1;
        }
    }
    (checked, failed)
}
