[package]
name = "thalyx-user-trespasser"
description = "K1 user domain: trespasser."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "trespasser"
path = "src/main.rs"

[dependencies]
thalyx-abi.workspace = true
thalyx-user-rt.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
