#!/usr/bin/env python3
"""Derive both sides of the K6 paired benchmarks from one schema.

K6 measures the same work on two backends -- this kernel and Linux on the same
virtual machine -- from one C source. The benchmark identities, the plan a boot
follows, and the notes that carry samples back to the host are read by three
programs in two languages: the C benchmark compiled for the native target, the
same C compiled for Linux, and the Rust supervisor that builds the native
domains. Two hand-written copies of one layout is the arrangement that drifts,
so neither is hand-written. `abi/schema/k6-bench-v1.json` decides; this writes:

  user/native/include/thalyx/k6.h   what both C builds include, with
                                    `_Static_assert` on every offset
  user/k6super/src/generated.rs     what the native supervisor encodes with

The layout rules are K5's and so is the code that applies them: a field that
would need padding is refused. `tools/check_k6_bench.py` regenerates and
compares.

Usage: tools/gen_k6_bench.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "abi/schema/k6-bench-v1.json"

sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_k5_proto as k5  # noqa: E402

EQUIVALENCE = ("equivalent", "comparable", "different", "native_only")


K5_SCHEMA = ROOT / "abi/schema/k5-proto-v1.json"


def ident(name: str) -> str:
    """`ipc.call` -> `IPC_CALL`."""
    return name.replace(".", "_").replace("-", "_").upper()


def engine_questions() -> tuple[dict, list[tuple[str, int]]]:
    """The engine's questions, from the one place both backends read them.

    K5's fixture decides what the engine is asked; K6 measures the same
    questions rather than choosing its own. Flattened in fixture order, case by
    case and prompt by prompt, so `engine.infer`'s parameter is an index into
    it."""
    engine = json.loads(K5_SCHEMA.read_text())["fixtures"]["engine"]
    flat = [(prompt, case["predict"]) for case in engine["cases"] for prompt in case["prompts"]]
    return engine, flat


def generate_c(schema: dict) -> str:
    out = [
        "/* Generated by tools/gen_k6_bench.py from abi/schema/k6-bench-v1.json.",
        " * Do not edit.",
        " *",
        " * The K6 paired benchmarks, as both C builds see them: the benchmark",
        " * compiled for the native target and the same benchmark compiled for",
        " * Linux include this one header, so the two sides of a comparison cannot",
        " * disagree about what a benchmark is called or how a plan is laid out.",
        " * The native supervisor has the same layout in user/k6super/src/",
        " * generated.rs, from the same schema.",
        " */",
        "#ifndef THALYX_K6_H",
        "#define THALYX_K6_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
    ]
    version = schema["version"]
    out.append(f"#define K6_VERSION_MAJOR {version['major']}u")
    out.append(f"#define K6_VERSION_MINOR {version['minor']}u")
    out.append("")
    for name, value in schema["constants"].items():
        out.append(f"#define K6_{name} {value}ull")
    out.append("")
    for name, item in schema["notes"].items():
        if item.get("doc"):
            out.append(f"/* {item['doc']} */")
        out.append(f"#define K6_NOTE_{name} 0x{item['value']:04X}ull")
    out.append("")
    out.append("/* Benchmark identities. What each side does for one is in the schema. */")
    for bench in schema["benchmarks"]:
        out.append(f"#define K6_BENCH_{ident(bench['name'])} {bench['id']}u")
    out.append("")
    engine, flat = engine_questions()
    out.append("/* The engine's questions, from the K5 fixture in abi/schema/k5-proto-v1.json,")
    out.append(" * case by case and prompt by prompt. engine.infer's parameter indexes them. */")
    out.append(f"#define K6_ENGINE_CONTEXT_TOKENS {engine['context_tokens']}u")
    out.append(f"#define K6_ENGINE_COMPUTE_THREADS {engine['compute_threads']}u")
    prompts = ", ".join(json.dumps(prompt) for prompt, _ in flat)
    predicts = ", ".join(f"{predict}u" for _, predict in flat)
    out.append("__attribute__((unused))")
    out.append(f"static const char *const k6_engine_prompt[{len(flat)}] = {{{prompts}}};")
    out.append("__attribute__((unused))")
    out.append(f"static const uint32_t k6_engine_predict[{len(flat)}] = {{{predicts}}};")
    out.append("/* A grammar under which no answer ends, for the request that is cancelled. */")
    out.append(f"#define K6_CANCEL_GRAMMAR {json.dumps(schema['cancel_grammar'])}")
    out.append("")
    for definition in schema["structs"]:
        fields, size, align = k5.layout(definition)
        typedef = "k6_" + k5.snake(definition["name"])
        if definition.get("doc"):
            out.append(f"/* {definition['doc']} */")
        out.append("typedef struct {")
        for field in fields:
            declared = k5.C_NAME[field["base"]]
            suffix = f"[{field['count']}]" if field["count"] else ""
            comment = f" /* {field['doc']} */" if field.get("doc") else ""
            out.append(f"    {declared} {field['name']}{suffix};{comment}")
        out.append(f"}} {typedef};")
        out.append(f'_Static_assert(sizeof({typedef}) == {size}, "{definition["name"]} size");')
        out.append(
            f'_Static_assert(_Alignof({typedef}) == {align}, "{definition["name"]} alignment");'
        )
        for field in fields:
            out.append(
                f"_Static_assert(offsetof({typedef}, {field['name']}) == {field['offset']}, "
                f'"{definition["name"]}.{field["name"]} offset");'
            )
        out.append("")
    out.append("#endif /* THALYX_K6_H */")
    return "\n".join(out) + "\n"


def generate_rust(schema: dict) -> str:
    out = [
        "//! Generated by tools/gen_k6_bench.py from abi/schema/k6-bench-v1.json.",
        "//! Do not edit.",
        "//!",
        "//! The K6 paired benchmarks, as the native supervisor encodes them. Both C",
        "//! builds of the benchmark read the same layout from",
        "//! `user/native/include/thalyx/k6.h`, with static assertions on every offset.",
        "",
        "// The schema is generated whole; a program uses the part it needs.",
        "#![allow(dead_code)]",
        "",
        "use thalyx_user_k4fmt::Pod;",
        "",
    ]
    version = schema["version"]
    out.append("/// Protocol version this revision speaks.")
    out.append(f"pub const VERSION_MAJOR: u32 = {version['major']};")
    out.append("/// Minor version.")
    out.append(f"pub const VERSION_MINOR: u32 = {version['minor']};")
    out.append("")
    for name, value in schema["constants"].items():
        out.append(f"/// Schema constant `{name}`.")
        out.append(f"pub const {name}: u64 = {value};")
    out.append("")
    out.append("/// Notes the K6 programs emit on the diagnostic plane, in their own range.")
    out.append("pub mod note {")
    for name, item in schema["notes"].items():
        out.extend(k5.doc(item.get("doc"), "    ", "///"))
        out.append(f"    pub const {name}: u64 = 0x{item['value']:04X};")
    out.append("}")
    out.append("")
    out.append("/// Benchmark identities.")
    out.append("pub mod bench {")
    for bench in schema["benchmarks"]:
        out.append(f"    /// `{bench['name']}`: {bench['family']}, {bench['equivalence']}.")
        out.append(f"    pub const {ident(bench['name'])}: u32 = {bench['id']};")
    out.append("}")
    out.append("")
    _, flat = engine_questions()
    prompts = ", ".join(json.dumps(prompt) for prompt, _ in flat)
    predicts = ", ".join(str(predict) for _, predict in flat)
    out.append("/// The engine's questions, from the K5 fixture, case by case and prompt by")
    out.append("/// prompt. `engine.infer`'s parameter indexes them.")
    out.append(f"pub const ENGINE_PROMPT: [&str; {len(flat)}] = [{prompts}];")
    out.append("/// Tokens each of those questions may be answered with.")
    out.append(f"pub const ENGINE_PREDICT: [u32; {len(flat)}] = [{predicts}];")
    out.append("/// A grammar under which no answer ends, for the request that is cancelled.")
    out.append(f"pub const CANCEL_GRAMMAR: &str = {json.dumps(schema['cancel_grammar'])};")
    out.append("")
    for definition in schema["structs"]:
        fields, size, align = k5.layout(definition)
        out.extend(k5.doc(definition.get("doc"), "", "///"))
        out.append("#[repr(C)]")
        out.append("#[derive(Clone, Copy)]")
        out.append(f"pub struct {definition['name']} {{")
        for field in fields:
            out.extend(k5.doc(field.get("doc"), "    ", "///"))
            rust = k5.RUST_NAME[field["base"]]
            declared = f"[{rust}; {field['count']}]" if field["count"] else rust
            out.append(f"    pub {field['name']}: {declared},")
        out.append("}")
        out.append("")
        out.append(f"const _: () = assert!(size_of::<{definition['name']}>() == {size});")
        out.append(f"const _: () = assert!(align_of::<{definition['name']}>() == {align});")
        out.append("")
        out.append("// SAFETY: `repr(C)`, integers and integer arrays only, no implicit padding:")
        out.append("// the schema refuses a field that would need any.")
        out.append(f"unsafe impl Pod for {definition['name']} {{}}")
        out.append("")
    return "\n".join(out) + "\n"


def problems(schema: dict) -> list[str]:
    """What makes a schema unusable as the judge of a comparison."""
    found = []
    ids = [bench["id"] for bench in schema["benchmarks"]]
    names = [bench["name"] for bench in schema["benchmarks"]]
    if len(set(ids)) != len(ids):
        found.append("benchmark ids repeat")
    if len(set(names)) != len(names):
        found.append("benchmark names repeat")
    for bench in schema["benchmarks"]:
        where = bench["name"]
        if bench["family"] not in schema["families"]:
            found.append(f"{where}: family {bench['family']!r} is not declared")
        if bench["equivalence"] not in EQUIVALENCE:
            found.append(f"{where}: equivalence {bench['equivalence']!r} is not one of {EQUIVALENCE}")
        if not bench["params"]:
            found.append(f"{where}: no parameter to run")
        if not bench["native"]:
            found.append(f"{where}: says nothing about the native side")
        if bench["equivalence"] != "native_only" and not bench["linux"]:
            found.append(f"{where}: compared with Linux but says nothing about the Linux side")
        if bench["equivalence"] == "native_only" and bench["linux"]:
            found.append(f"{where}: native_only but describes a Linux side")
        if bench["equivalence"] in ("comparable", "different") and not bench["differences"]:
            found.append(f"{where}: {bench['equivalence']} without the differences that make it so")
        if bench["id"] >= 1 << 16 or any(p >= 1 << 16 for p in bench["params"]):
            found.append(f"{where}: an id or parameter does not fit the 16 bits BEGIN gives it")
    if not schema.get("cancel_grammar"):
        found.append("no cancel_grammar for the request engine.cancel cuts short")
    _, flat = engine_questions()
    if schema["constants"].get("ENGINE_PROMPTS") != len(flat):
        found.append(f"ENGINE_PROMPTS is not the {len(flat)} prompts the K5 fixture holds")
    for bench in schema["benchmarks"]:
        if bench["name"] == "engine.infer" and any(p >= len(flat) for p in bench["params"]):
            found.append("engine.infer names a prompt the K5 fixture does not have")
    return found


def outputs() -> dict[Path, str]:
    schema = json.loads(SCHEMA.read_text())
    return {
        ROOT / "user/native/include/thalyx/k6.h": generate_c(schema),
        ROOT / "user/k6super/src/generated.rs": k5.rustfmt(generate_rust(schema)),
    }


def main() -> int:
    schema = json.loads(SCHEMA.read_text())
    found = problems(schema)
    if found:
        for line in found:
            print(f"schema: {line}", file=sys.stderr)
        return 1
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
