#!/usr/bin/env python3
"""Derive both sides of the K5 protocols from one schema.

Two languages meet in the K5 package: the supervisor, the work and the services
are Rust on the kernel's target, and the language runtime, the validation tool
and the inference engine are C on the native one. Everything they say to each
other crosses that seam, and two hand-written definitions of one layout is the
arrangement that drifts.

So neither is hand-written. `abi/schema/k5-proto-v1.json` decides every field,
every offset and every number; this writes:

  user/k5pkg/src/generated.rs   what the Rust side encodes with
  user/native/include/thalyx/k5.h   what the C side encodes with, with
                                    `_Static_assert` on every size and offset

Generating both does not make them agree by argument -- they share offsets, so
of course they agree about those. What it buys is that neither side *defines*
the layout, and the assertions in the C header fail the build if the compiler
lays a structure out differently from what the schema says.

`tools/check_k5_proto.py` regenerates and compares, so a committed file that
drifted from the schema fails a check rather than a run.

Usage: tools/gen_k5_proto.py
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "abi/schema/k5-proto-v1.json"

WIDTH = {"u8": 1, "u16": 2, "u32": 4, "u64": 8, "i64": 8}
C_NAME = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t",
          "i64": "int64_t"}
RUST_NAME = {"u8": "u8", "u16": "u16", "u32": "u32", "u64": "u64", "i64": "i64"}


def parse_type(text: str) -> tuple[str, int | None]:
    if text.endswith("]"):
        base, _, count = text[:-1].partition("[")
        return base, int(count)
    return text, None


def layout(definition: dict) -> tuple[list[dict], int, int]:
    """Offsets, size and alignment, refusing any field that would need padding.

    The refusal is the point: a schema that admitted implicit padding would be a
    schema whose bytes depend on a compiler's opinion."""
    offset = 0
    align = 1
    fields = []
    for field in definition["fields"]:
        base, count = parse_type(field["type"])
        width = WIDTH[base]
        if offset % width != 0:
            raise SystemExit(
                f"{definition['name']}.{field['name']} would need padding at {offset}; "
                "reorder the fields or declare a reserved one"
            )
        align = max(align, width)
        fields.append(dict(field, base=base, count=count, offset=offset))
        offset += width * (count if count is not None else 1)
    if offset % align != 0:
        raise SystemExit(
            f"{definition['name']} is {offset} bytes and aligns to {align}; "
            "add a reserved field"
        )
    return fields, offset, align


def snake(name: str) -> str:
    out = []
    for index, letter in enumerate(name):
        if letter.isupper() and index:
            out.append("_")
        out.append(letter.lower())
    return "".join(out)


def doc(text: str | None, indent: str, marker: str) -> list[str]:
    if not text:
        return []
    return [f"{indent}{marker} {text}"]


def generate_rust(schema: dict) -> str:
    out = [
        "//! Generated by tools/gen_k5_proto.py from abi/schema/k5-proto-v1.json.",
        "//! Do not edit.",
        "//!",
        "//! The K5 protocols, as the Rust side of the package encodes them. The C",
        "//! side has the same layout in `user/native/include/thalyx/k5.h`, derived",
        "//! from the same schema, with static assertions on every offset.",
        "",
        "use thalyx_user_k4fmt::Pod;",
        "",
    ]
    version = schema["version"]
    out.append(f"/// Protocol version this revision speaks.")
    out.append(f"pub const VERSION_MAJOR: u32 = {version['major']};")
    out.append(f"/// Minor version.")
    out.append(f"pub const VERSION_MINOR: u32 = {version['minor']};")
    out.append("")
    for name, value in schema["constants"].items():
        out.append(f"/// Schema constant `{name}`.")
        out.append(f"pub const {name}: usize = {value};")
    out.append("")
    out.append("/// Notes the K5 programs emit on the diagnostic plane.")
    out.append("///")
    out.append("/// Their own range, so a K5 note can never be read as a K2, K3 or K4 one by")
    out.append("/// a gate looking at one log. Two integers each, which is all the plane")
    out.append("/// carries: anything a program wants remembered goes into managed state.")
    out.append("pub mod note {")
    for name, item in schema["notes"].items():
        out.extend(doc(item.get("doc"), "    ", "///"))
        out.append(f"    pub const {name}: u64 = 0x{item['value']:04X};")
    out.append("}")
    out.append("")
    for enum_name, entries in schema["enums"].items():
        out.append(f"/// `{enum_name}` values crossing the boundary as integers.")
        out.append(f"pub mod {snake(enum_name)} {{")
        for item in entries:
            out.extend(doc(item.get("doc"), "    ", "///"))
            out.append(f"    /// `{enum_name}::{item['name']}`.")
            out.append(f"    pub const {item['name']}: u32 = {item['value']};")
        out.append("}")
        out.append("")
    engine = schema.get("fixtures", {}).get("engine")
    if engine:
        out.append("/// What the engine is asked, on both backends.")
        out.append("///")
        out.append("/// From the schema's fixture, so the native program, the Linux reference")
        out.append("/// and the gate ask one question from one source.")
        out.append("pub mod engine_case {")
        out.append("    /// Context the engine builds, in tokens.")
        out.append(f"    pub const CONTEXT_TOKENS: u64 = {engine['context_tokens']};")
        out.append("    /// Threads the engine computes a graph with.")
        out.append(f"    pub const COMPUTE_THREADS: u64 = {engine['compute_threads']};")
        for case in engine["cases"]:
            name = case["name"].upper()
            prompts = ", ".join(json.dumps(prompt) for prompt in case["prompts"])
            out.extend(doc(case.get("doc"), "    ", "///"))
            out.append(f"    pub const {name}_PROMPTS: [&str; {len(case['prompts'])}] = [{prompts}];")
            out.append(f"    /// Tokens each answer of the `{case['name']}` case may run to.")
            out.append(f"    pub const {name}_PREDICT: u32 = {case['predict']};")
        out.append("}")
        out.append("")
    for definition in schema["structs"]:
        fields, size, align = layout(definition)
        out.extend(doc(definition.get("doc"), "", "///"))
        out.append("#[repr(C)]")
        out.append("#[derive(Clone, Copy)]")
        out.append(f"pub struct {definition['name']} {{")
        for field in fields:
            out.extend(doc(field.get("doc"), "    ", "///"))
            rust = RUST_NAME[field["base"]]
            declared = f"[{rust}; {field['count']}]" if field["count"] else rust
            out.append(f"    pub {field['name']}: {declared},")
        out.append("}")
        out.append("")
        out.append(f"const _: () = assert!(size_of::<{definition['name']}>() == {size});")
        out.append(f"const _: () = assert!(align_of::<{definition['name']}>() == {align});")
        out.append("")
        out.append("// SAFETY: `repr(C)`, integers and byte arrays only, no implicit padding:")
        out.append("// the schema refuses a field that would need any.")
        out.append(f"unsafe impl Pod for {definition['name']} {{}}")
        out.append("")
    return "\n".join(out) + "\n"


def generate_c(schema: dict) -> str:
    out = [
        "/* Generated by tools/gen_k5_proto.py from abi/schema/k5-proto-v1.json.",
        " * Do not edit.",
        " *",
        " * The K5 protocols, as the C side of the package encodes them. The Rust",
        " * side has the same layout in user/k5pkg/src/generated.rs, derived from",
        " * the same schema. The assertions below are what makes that a checked",
        " * fact rather than an intention: if this compiler lays a structure out",
        " * differently from what the schema says, the build stops here.",
        " */",
        "#ifndef THALYX_K5_H",
        "#define THALYX_K5_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "/* C++ spells both of these differently; the inference engine is C++ and",
        " * reads this header. The assertions are the same checks in either. */",
        "#if defined(__cplusplus) && !defined(_Static_assert)",
        "#define _Static_assert static_assert",
        "#endif",
        "#if defined(__cplusplus) && !defined(_Alignof)",
        "#define _Alignof alignof",
        "#endif",
        "",
    ]
    version = schema["version"]
    out.append(f"#define K5_VERSION_MAJOR {version['major']}u")
    out.append(f"#define K5_VERSION_MINOR {version['minor']}u")
    out.append("")
    for name, value in schema["constants"].items():
        out.append(f"#define K5_{name} {value}u")
    out.append("")
    for name, item in schema["notes"].items():
        if item.get("doc"):
            out.append(f"/* {item['doc']} */")
        out.append(f"#define K5_NOTE_{name} 0x{item['value']:04X}ull")
    out.append("")
    for enum_name, entries in schema["enums"].items():
        prefix = snake(enum_name).upper()
        for item in entries:
            if item.get("doc"):
                out.append(f"/* {item['doc']} */")
            out.append(f"#define K5_{prefix}_{item['name']} {item['value']}u")
        out.append("")
    engine = schema.get("fixtures", {}).get("engine")
    if engine:
        out.append("/* What the engine is asked, on both backends: the fixture's parameters. */")
        out.append(f"#define K5_ENGINE_CONTEXT_TOKENS {engine['context_tokens']}u")
        out.append(f"#define K5_ENGINE_COMPUTE_THREADS {engine['compute_threads']}u")
        out.append("")
    for definition in schema["structs"]:
        fields, size, align = layout(definition)
        typedef = "k5_" + snake(definition["name"])
        if definition.get("doc"):
            out.append(f"/* {definition['doc']} */")
        out.append("typedef struct {")
        for field in fields:
            declared = C_NAME[field["base"]]
            suffix = f"[{field['count']}]" if field["count"] else ""
            comment = f" /* {field['doc']} */" if field.get("doc") else ""
            out.append(f"    {declared} {field['name']}{suffix};{comment}")
        out.append(f"}} {typedef};")
        out.append(f'_Static_assert(sizeof({typedef}) == {size}, "{definition["name"]} size");')
        out.append(
            f'_Static_assert(_Alignof({typedef}) == {align}, "{definition["name"]} alignment");'
        )
        for field in fields:
            out.append(
                f"_Static_assert(offsetof({typedef}, {field['name']}) == {field['offset']}, "
                f'"{definition["name"]}.{field["name"]} offset");'
            )
        out.append("")
    out.append("#endif /* THALYX_K5_H */")
    return "\n".join(out) + "\n"


def rustfmt(text: str) -> str:
    try:
        done = subprocess.run(
            ["rustfmt", "--edition", "2024", "--emit", "stdout"],
            input=text, capture_output=True, text=True, check=False,
        )
        return done.stdout if done.returncode == 0 and done.stdout else text
    except OSError:
        return text


def outputs() -> dict[Path, str]:
    schema = json.loads(SCHEMA.read_text())
    return {
        ROOT / "user/k5pkg/src/generated.rs": rustfmt(generate_rust(schema)),
        ROOT / "user/native/include/thalyx/k5.h": generate_c(schema),
    }


def main() -> int:
    for path, text in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
