[package]
name = "thalyx-user-k2super"
description = "K2 user domain: k2super."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "k2super"
path = "src/main.rs"

[dependencies]
thalyx-abi.workspace = true
thalyx-user-rt.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
